import type { Chapter, Season } from '../domain/types';
import { seasons as baseSeasons } from './story';

const chapter3: Chapter = {
  id: 's01-c03',
  season: 1,
  number: 3,
  title: 'Please Stop Protecting Me',
  summary: 'Jian Yue begins her supervision. Xu Kai survives his first assassination attempt with observation, shamelessness, and absolutely no useful combat ability.',
  readingMinutes: 9,
  tags: ['xu-kai', 'jian-yue', 'assassins', 'wit', 'romance'],
  segments: [
    { kind: 'paragraph', text: 'Xu Kai arrived at the south gate twenty-three minutes after sunrise carrying breakfast.' },
    { kind: 'paragraph', text: 'Jian Yue had been waiting for twenty-four.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You are late.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I brought buns.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'That does not change time.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Have you tried one?', accent: 'primary' },
    { kind: 'paragraph', text: 'She looked at the paper bag.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'No.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Then your conclusion lacks evidence.', accent: 'primary' },
    { kind: 'paragraph', text: 'Jian Yue took one.' },
    { kind: 'paragraph', text: 'Xu Kai smiled.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Do not look pleased.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You accepted a bribe.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'It is a bun.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Corruption always starts small.', accent: 'primary' },
    { kind: 'paragraph', text: 'They left Qingshi with two Ministry agents following at a respectful distance.' },
    { kind: 'paragraph', text: 'By midmorning Jian Yue had learned that Xu Kai could complain about a saddle for longer than most diplomats could discuss a treaty.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Oi.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'No.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I have not asked anything yet.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'I am getting ahead of the problem.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'How proactive.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'My name is Jian Yue.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I remember.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Use it.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'That sounds unnecessarily intimate.', accent: 'primary' },
    { kind: 'paragraph', text: 'Her horse sped up.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Oi, wait.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Walk.', accent: 'secondary' },
    { kind: 'break', label: 'By evening' },
    { kind: 'paragraph', text: 'Rain drove them into a roadside inn two hours short of the nearest town.' },
    { kind: 'paragraph', text: 'Jian Yue disliked the place before she crossed the threshold.' },
    { kind: 'paragraph', text: 'Xu Kai disliked the soup.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Too much ginger.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Three men near the door are armed.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'That does not excuse the ginger.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Two upstairs. One behind the kitchen curtain.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Six assassins?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Seven.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Where is seven?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Serving you soup.', accent: 'secondary' },
    { kind: 'paragraph', text: 'Xu Kai looked at the innkeeper.' },
    { kind: 'paragraph', text: 'The innkeeper looked at the soup.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'That explains the ginger.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Stay behind me.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I dislike that sentence.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You dislike most useful sentences.', accent: 'secondary' },
    { kind: 'paragraph', text: 'The first dart came from the second-floor railing.' },
    { kind: 'paragraph', text: 'Jian Yue caught it between two fingers.' },
    { kind: 'paragraph', text: 'Then the inn erupted.' },
    { kind: 'paragraph', text: 'Crimson steel flashed. A table split. A sword spun into a ceiling beam. One attacker crossed three steps toward Jian Yue and somehow finished the journey without his weapon.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You know, I was going to eat there.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Behind me.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'That table was innocent.', accent: 'primary' },
    { kind: 'paragraph', text: 'Jian Yue kicked a chair backward without looking. It hit Xu Kai in the shin and shoved him farther from the fight.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Ow.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Good.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Cruel woman.', accent: 'primary' },
    { kind: 'paragraph', text: 'The seventh assassin had never planned to fight Jian Yue.' },
    { kind: 'paragraph', text: 'He waited until she was occupied, slid behind the overturned tables, and approached Xu Kai from the kitchen side.' },
    { kind: 'paragraph', text: 'Xu Kai noticed him in the reflection of his soup spoon.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Before you stab me, a question.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Assassin', text: 'What?' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Why did your employer pay you in new southern-mint silver when the road south has been closed for twelve days?', accent: 'primary' },
    { kind: 'paragraph', text: 'The assassin hesitated.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Ah. So you did not know that was unusual.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Assassin', text: 'Shut up.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'And that knot on your wrist. Ministry courier knot. Poorly copied, but still. Did Minister Lu hire you directly, or did someone want me to think he did?', accent: 'primary' },
    { kind: 'paragraph', text: 'The assassin looked down.' },
    { kind: 'paragraph', text: 'That was the second mistake.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Oi.', accent: 'primary' },
    { kind: 'paragraph', text: 'Jian Yue turned.' },
    { kind: 'paragraph', text: 'The assassin moved.' },
    { kind: 'paragraph', text: 'He made it half a step.' },
    { kind: 'paragraph', text: 'Jian Yue crossed the room before the next breath and drove the flat of her blade into his ribs. He folded around it and hit the floor.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Are you hurt?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You hit me with a chair.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'From the assassins.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'No. Your chair attack was extremely successful.', accent: 'primary' },
    { kind: 'paragraph', text: 'She caught his wrist and checked his pulse anyway.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Oi.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'What?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Dinner first.', accent: 'primary' },
    { kind: 'paragraph', text: 'She released him instantly.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Idiot.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'That sounded affectionate.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'It was a diagnosis.', accent: 'secondary' },
    { kind: 'break', label: 'Later' },
    { kind: 'paragraph', text: 'Seven assassins sat bound against the inn wall.' },
    { kind: 'paragraph', text: 'Xu Kai sat opposite them with a fresh bowl of soup.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Why are you eating that?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I complained. They made another.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'The innkeeper tried to poison you.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Customer feedback works.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You are impossible.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Yet supervised.', accent: 'primary' },
    { kind: 'paragraph', text: 'Later that night Xu Kai opened his room door.' },
    { kind: 'paragraph', text: 'Jian Yue sat opposite with her sword across her knees.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You are keeping watch?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'I am preventing a state security concern from getting murdered in his sleep.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You worry too much, Oi.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'I am not worried.', accent: 'secondary' },
    { kind: 'paragraph', text: 'He tossed her a steamed bun.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'For the corruption.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Go to sleep, idiot.', accent: 'secondary' },
    { kind: 'paragraph', text: 'She ate the bun anyway.' },
  ],
};

const chapter4: Chapter = {
  id: 's01-c04',
  season: 1,
  number: 4,
  title: 'Seven Assassins and One Terrible Liar',
  summary: 'Jian Yue wants a confession. Xu Kai wants breakfast. The assassins would prefer both of them to leave.',
  readingMinutes: 8,
  tags: ['interrogation', 'wit', 'jian-yue', 'banter'],
  segments: [
    { kind: 'paragraph', text: 'At dawn, Jian Yue arranged seven assassins in a straight line beneath the inn awning.' },
    { kind: 'paragraph', text: 'Xu Kai arranged three breakfast dishes in front of himself.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Which one is the leader?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'The one pretending not to be.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'That describes six of them.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Then we have narrowed it down.', accent: 'primary' },
    { kind: 'paragraph', text: 'The assassins stared at him with the quiet hatred of men who had spent the night tied to a wall while listening to him sleep comfortably.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Who hired you?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Assassin Leader', text: 'No one.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Terrible start.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Assassin Leader', text: 'We are travelers.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Worse.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Do you want to conduct this interrogation?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Not particularly. Yours is going beautifully.', accent: 'primary' },
    { kind: 'paragraph', text: 'Jian Yue rested one hand on her sword.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'See? Very persuasive.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Assassin Leader', text: 'We do not know the client.' },
    { kind: 'paragraph', text: 'Xu Kai stopped eating.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'That part is true.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'How can you tell?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'He stopped trying to sound brave.', accent: 'primary' },
    { kind: 'paragraph', text: 'The leader looked at him.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You received half payment in southern-mint silver, instructions through a copied Ministry courier knot, and a target description that emphasized my route but not Lady Jian\'s presence.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Assassin Leader', text: 'We were told she might be with you.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'No, you were told a guard might be with me. You only realized who she was when she caught the dart.', accent: 'primary' },
    { kind: 'paragraph', text: 'One of the younger assassins glanced at the leader.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Thank you.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Young Assassin', text: 'For what?' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Confirming it.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You did not know.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Knowing is expensive. Guessing is free.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You say that as if it makes this better.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'It makes breakfast more interesting.', accent: 'primary' },
    { kind: 'paragraph', text: 'He turned back to the assassins.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'The person who hired you wanted me dead and Minister Lu blamed.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Assassin Leader', text: 'We never heard that name.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Exactly.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Explain.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'The copied Ministry knot is too obvious. Real couriers do not wear it on their wrists. Someone wanted us to notice it after the bodies were found.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'And the southern silver?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Also too obvious. Minister Lu controls southern procurement. Convenient evidence is usually evidence someone carried for you.', accent: 'primary' },
    { kind: 'paragraph', text: 'Jian Yue was silent for several breaths.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You noticed all of that while complaining about soup?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I can multitask.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You nearly got stabbed.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Also multitasking.', accent: 'primary' },
    { kind: 'paragraph', text: 'Her expression hardened.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Do not joke about that.', accent: 'secondary' },
    { kind: 'paragraph', text: 'Xu Kai looked at her.' },
    { kind: 'paragraph', text: 'For once, he let the joke die.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Fine.', accent: 'primary' },
    { kind: 'paragraph', text: 'Jian Yue seemed almost surprised he had listened.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Oi.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'What?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Your porridge is getting cold.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'I hate you.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'That sounded less convincing than their traveler story.', accent: 'primary' },
    { kind: 'paragraph', text: 'The young assassin coughed to hide a laugh.' },
    { kind: 'paragraph', text: 'Jian Yue turned her head.' },
    { kind: 'paragraph', text: 'He immediately remembered he was a prisoner.' },
    { kind: 'break', label: 'On the road' },
    { kind: 'paragraph', text: 'They sent the prisoners ahead under Ministry guard and continued toward the capital.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'If Minister Lu was framed, who benefits?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Everyone who wants you angry at Minister Lu.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'That list is long.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'He sounds charming.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'He is National Tier #4.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'That was not what I asked.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'It is usually enough information for people to stop asking.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Poor conversational design again.', accent: 'primary' },
    { kind: 'paragraph', text: 'Jian Yue looked ahead.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Do not call him Oi.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Jealous?', accent: 'primary' },
    { kind: 'paragraph', text: 'Her horse immediately moved three lengths ahead.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Walk.', accent: 'secondary' },
  ],
};

const chapter5: Chapter = {
  id: 's01-c05',
  season: 1,
  number: 5,
  title: 'The Capital Has Heard About Oi',
  summary: 'Xu Kai reaches the capital and discovers that Jian Yue\'s least favorite nickname has arrived before him.',
  readingMinutes: 8,
  tags: ['capital', 'jian-yue', 'oi', 'comedy'],
  segments: [
    { kind: 'paragraph', text: 'The capital had three walls, nine ceremonial gates, four hundred years of defensive planning, and absolutely no defense against gossip.' },
    { kind: 'paragraph', text: 'Xu Kai learned this before his horse crossed the eastern bridge.' },
    { kind: 'dialogue', speaker: 'Gate Captain', text: 'Lady Jian. Welcome back.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Captain.', accent: 'secondary' },
    { kind: 'paragraph', text: 'The gate captain glanced at Xu Kai.' },
    { kind: 'paragraph', text: 'Then he glanced away too quickly.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'He knows.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Knows what?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Oi.', accent: 'primary' },
    { kind: 'paragraph', text: 'The gate captain made a sound suspiciously like a cough.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Captain.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Gate Captain', text: 'My lady.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Who told you?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Gate Captain', text: 'Told me what?' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Excellent survival instincts.', accent: 'primary' },
    { kind: 'paragraph', text: 'Jian Yue closed her eyes.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'I am going to find the Ministry courier responsible.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'National Tier #2 versus a gossip network. Finally, an even fight.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Keep talking.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Threatening a civilian at the city gate. Very statesmanlike.', accent: 'primary' },
    { kind: 'paragraph', text: 'The gate captain abruptly became fascinated by paperwork.' },
    { kind: 'break', label: 'Ministry of State Security' },
    { kind: 'paragraph', text: 'The Ministry occupied a grey compound with no decorative carvings, no garden, and windows narrow enough to make optimism difficult.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Cheerful place.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Try not to offend anyone.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You ask impossible things.', accent: 'primary' },
    { kind: 'paragraph', text: 'A clerk met them at the entrance.' },
    { kind: 'dialogue', speaker: 'Ministry Clerk', text: 'Minister Lu is waiting in Chamber Three.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'The framed one?', accent: 'primary' },
    { kind: 'paragraph', text: 'The clerk froze.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Xu Kai.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'What? It saves time.', accent: 'primary' },
    { kind: 'paragraph', text: 'Chamber Three contained a long table, six empty chairs, and a man dressed entirely in charcoal grey.' },
    { kind: 'paragraph', text: 'Lu Chen looked younger than Xu Kai expected and more tired than anyone National Tier #4 had a right to look.' },
    { kind: 'paragraph', text: 'He was also smiling.' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Xu Kai.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You have the advantage.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Lu Chen.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'My condolences.', accent: 'primary' },
    { kind: 'paragraph', text: 'Jian Yue slowly looked at the ceiling.' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'He did that to you too?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Worse.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You two are becoming very close.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Sit down.', accent: 'secondary' },
    { kind: 'paragraph', text: 'Xu Kai sat.' },
    { kind: 'paragraph', text: 'Jian Yue blinked at the immediate obedience.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'There was a chair.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Seven assassins used a counterfeit Ministry signal, southern silver tied to my procurement office, and a route known only to six officials.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Five.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Six.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'One of them did not know the route.', accent: 'primary' },
    { kind: 'paragraph', text: 'Lu Chen\'s smile disappeared.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Which one?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Deputy Secretary Fang.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Why?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Because he asked the gate office yesterday whether I was still in Qingshi.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'How do you know that?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'The gate captain complained about him while stamping my travel paper.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'That proves he did not know your location.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Exactly. So whoever leaked it sits among the other five.', accent: 'primary' },
    { kind: 'paragraph', text: 'Silence settled over Chamber Three.' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'You eliminated a suspect because of a complaint at a gate.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You wanted me because I listen when boring people talk.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'No one said we wanted you.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You personally traveled two provinces to collect me.', accent: 'primary' },
    { kind: 'paragraph', text: 'The tips of Jian Yue\'s ears colored.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Official assignment.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Of course.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Do not start.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I said nothing.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Your face did.', accent: 'secondary' },
    { kind: 'paragraph', text: 'Lu Chen smiled again.' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'I understand why the file keeps getting longer.', accent: 'neutral' },
  ],
};

const chapter6: Chapter = {
  id: 's01-c06',
  season: 1,
  number: 6,
  title: 'The Weakest Man in the Room',
  summary: 'Lu Chen tests Xu Kai in front of senior officials. Jian Yue discovers she dislikes people threatening her state security concern.',
  readingMinutes: 9,
  tags: ['lu-chen', 'ministry', 'wit', 'tsundere'],
  segments: [
    { kind: 'paragraph', text: 'The next morning, six senior officials gathered to decide what to do with Xu Kai.' },
    { kind: 'paragraph', text: 'Xu Kai had not been invited to the first half of the meeting.' },
    { kind: 'paragraph', text: 'He attended anyway.' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'How did you get in here?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Your western corridor guard is in love with the records clerk.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'That does not answer my question.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'It answers several future questions.', accent: 'primary' },
    { kind: 'paragraph', text: 'Jian Yue was already seated near the window.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Sit.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You have become very commanding since yesterday.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Since yesterday?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Fair.', accent: 'primary' },
    { kind: 'paragraph', text: 'The oldest official at the table, Minister Qiao, tapped a dossier with one finger.' },
    { kind: 'dialogue', speaker: 'Minister Qiao', text: 'Combat assessment: negligible.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Accurate and hurtful.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Minister Qiao', text: 'No registered sect. No military school. No known teacher. No recorded internal cultivation.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I had a very peaceful childhood.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Minister Qiao', text: 'Yet you destabilized Qingshi in forty-eight hours.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Qingshi destabilized itself. I merely charged admission.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Enough jokes.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'That sounds grim.', accent: 'primary' },
    { kind: 'paragraph', text: 'Lu Chen placed five sealed envelopes on the table.' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'One contains the name of the official who leaked your route.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'And the other four?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Nothing useful.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'So this is a test.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Open one.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'No.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Minister Qiao', text: 'You refuse?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I already know which envelope matters.', accent: 'primary' },
    { kind: 'paragraph', text: 'Lu Chen leaned back.' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Which?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'None of them.', accent: 'primary' },
    { kind: 'paragraph', text: 'Minister Qiao frowned.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'If you knew the leaker, I would not be here. If one envelope truly held the answer, this meeting would be an arrest, not theatre.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Perhaps I wanted to see whether you could identify information from incomplete evidence.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Then you would not tell me one envelope was correct. You would let me believe all five might be.', accent: 'primary' },
    { kind: 'paragraph', text: 'One of the officials quietly lowered his tea.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'This is not an intelligence test. You wanted to know whether I would pretend certainty to impress you.', accent: 'primary' },
    { kind: 'paragraph', text: 'Lu Chen was silent.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'And?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I am already impressive.', accent: 'primary' },
    { kind: 'paragraph', text: 'Jian Yue covered her eyes.' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'I was almost beginning to respect you.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Dangerous habit.', accent: 'primary' },
    { kind: 'paragraph', text: 'Minister Qiao shoved the dossier aside.' },
    { kind: 'dialogue', speaker: 'Minister Qiao', text: 'Then answer something useful. If you are so clever, identify the leak.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I need the five officials who knew our route in one room.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'And then?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Lunch.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Minister Qiao', text: 'Lunch?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Hungry people make bad liars.', accent: 'primary' },
    { kind: 'paragraph', text: 'Minister Qiao stood abruptly.' },
    { kind: 'dialogue', speaker: 'Minister Qiao', text: 'This is absurd.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You invited the man who ended a rebellion over cabbage. Expectations should have been managed.', accent: 'primary' },
    { kind: 'paragraph', text: 'Minister Qiao stepped toward him.' },
    { kind: 'paragraph', text: 'Jian Yue stood.' },
    { kind: 'paragraph', text: 'Nothing dramatic happened. She did not release killing intent. She did not touch her sword.' },
    { kind: 'paragraph', text: 'She simply placed herself between them.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Enough.', accent: 'secondary' },
    { kind: 'paragraph', text: 'Minister Qiao stopped.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Oi.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Not now.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Are you protecting me?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'I am protecting the investigation.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'From an elderly finance minister?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'From you making it worse.', accent: 'secondary' },
    { kind: 'paragraph', text: 'Xu Kai smiled.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Stop smiling.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'This is going to become a problem.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'There is no problem.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'She means me.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'I definitely mean you.', accent: 'secondary' },
  ],
};

const chapter7: Chapter = {
  id: 's01-c07',
  season: 1,
  number: 7,
  title: 'National Security, Apparently',
  summary: 'Xu Kai invites five suspects to lunch. Jian Yue discovers that jealousy can be filed under national security if one is sufficiently shameless.',
  readingMinutes: 10,
  tags: ['mystery', 'romance', 'tsundere', 'wit'],
  segments: [
    { kind: 'paragraph', text: 'Xu Kai\'s interrogation room was a restaurant.' },
    { kind: 'paragraph', text: 'Lu Chen objected to this on principle.' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'The Ministry has twelve interrogation chambers.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'And yet none serves roast duck.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'That is intentional.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Institutional failure.', accent: 'primary' },
    { kind: 'paragraph', text: 'The five officials who had known Xu Kai\'s route sat around a private dining table under the impression they were attending an informal Ministry review.' },
    { kind: 'paragraph', text: 'Jian Yue stood behind Xu Kai.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Sit.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'No.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You are making everyone nervous.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Good.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You see why I prefer vegetables.', accent: 'primary' },
    { kind: 'paragraph', text: 'The first course arrived.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Eat.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Official Peng', text: 'Are we under investigation?' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Everyone is under investigation if you are sufficiently unpleasant.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Answer properly.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'No.', accent: 'primary' },
    { kind: 'paragraph', text: 'Five officials relaxed by five different amounts.' },
    { kind: 'paragraph', text: 'Xu Kai noticed all of them.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Deputy Han, pass the vinegar.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Deputy Han', text: 'Certainly.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Secretary Mo, did the northern post receive my revised route notice?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Secretary Mo', text: 'Revised route?' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Never mind.', accent: 'primary' },
    { kind: 'paragraph', text: 'The second course arrived.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Lady Su, you are not eating.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lady Su', text: 'I dislike duck.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Tragic.', accent: 'primary' },
    { kind: 'paragraph', text: 'Lady Su was young, elegant, and apparently immune to Jian Yue\'s reputation.' },
    { kind: 'dialogue', speaker: 'Lady Su', text: 'Master Xu, I confess I expected someone older.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I disappoint professionally.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lady Su', text: 'Not in every respect.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Jian Yue\'s eyes shifted toward her.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Oi.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'What?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You are glaring at the duck.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'I am not.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Lady Su', text: 'Does he always call you that?', accent: 'neutral' },
    { kind: 'paragraph', text: 'The table went silent.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Unfortunately.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Lady Su', text: 'How intimate.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'It is not intimate.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'She says that often.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Eat your duck.', accent: 'secondary' },
    { kind: 'paragraph', text: 'Xu Kai obediently ate his duck.' },
    { kind: 'paragraph', text: 'For reasons she refused to examine, this irritated Jian Yue more.' },
    { kind: 'break', label: 'Third course' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Interesting.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'What?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'The leak was not about my route.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Explain.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Someone leaked Jian Yue\'s absence from the capital. My route was incidental.', accent: 'primary' },
    { kind: 'paragraph', text: 'No one moved.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Why?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Because every suspect reacted when I mentioned route details except one. Official Peng only relaxed when I said this was not an investigation.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Official Peng', text: 'That means nothing.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Agreed.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Official Peng', text: 'Then—' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'But when Lady Su mentioned the National Tier rotations, you stopped chewing.', accent: 'primary' },
    { kind: 'paragraph', text: 'Official Peng\'s face changed.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'There it is.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Peng.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Official Peng', text: 'You have no proof.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Correct again.', accent: 'primary' },
    { kind: 'paragraph', text: 'Xu Kai poured himself tea.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Which is why Deputy Han has spent the last hour searching your office.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Deputy Han', text: 'I have?', accent: 'neutral' },
    { kind: 'paragraph', text: 'Xu Kai looked at him.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Not you.', accent: 'primary' },
    { kind: 'paragraph', text: 'The door opened.' },
    { kind: 'paragraph', text: 'A second Deputy Han entered carrying a locked dispatch box.' },
    { kind: 'paragraph', text: 'The first Deputy Han stared.' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'You used one of my agents as a decoy.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'He has a trustworthy face.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'You met him ten minutes before lunch.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Very trustworthy ten minutes.', accent: 'primary' },
    { kind: 'paragraph', text: 'Official Peng stood.' },
    { kind: 'paragraph', text: 'Jian Yue rested one hand on his shoulder.' },
    { kind: 'paragraph', text: 'He sat again.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Stay.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Official Peng', text: 'Yes, my lady.' },
    { kind: 'paragraph', text: 'Lu Chen opened the dispatch box.' },
    { kind: 'paragraph', text: 'Inside were coded schedules for the Five National Tiers, copied over six months.' },
    { kind: 'paragraph', text: 'The assassination attempt had never been about Xu Kai alone.' },
    { kind: 'paragraph', text: 'Someone was mapping when the country\'s five strongest guardians were away from the capital.' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'This is larger than Qingshi.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Most annoying things are.', accent: 'primary' },
    { kind: 'paragraph', text: 'Lady Su leaned toward Xu Kai.' },
    { kind: 'dialogue', speaker: 'Lady Su', text: 'You are rather interesting.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'He is under supervision.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Lady Su', text: 'I did not ask whether he was under arrest.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Close enough.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Is this the national emergency?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'What?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Me speaking to another woman.', accent: 'primary' },
    { kind: 'paragraph', text: 'Jian Yue stared at him.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You are a national security concern.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'There it is.', accent: 'primary' },
    { kind: 'paragraph', text: 'Lu Chen quietly decided not to intervene.' },
  ],
};

const extraChapters = [chapter3, chapter4, chapter5, chapter6, chapter7];

export const seasons: Season[] = baseSeasons.map((season) => {
  if (season.number !== 1) {
    return season;
  }

  return {
    ...season,
    subtitle: 'A dangerous civilian acquires a National-Tier supervisor. Neither is happy about it.',
    description: 'Xu Kai solves problems with observation, manipulation, nerve, and deeply questionable conversational choices. National Tier #2 Jian Yue is assigned to supervise the apparently non-martial civilian and becomes increasingly protective while insisting this is purely official.',
    chapters: [season.chapters[0], season.chapters[1], ...extraChapters],
  };
});
