import type { Chapter, Season } from '../domain/types';
import { seasons as baseSeasons } from './story-v10';

const chapter55: Chapter = {
  id: 's01-c55',
  season: 1,
  number: 55,
  title: 'Oi, You Are Supposed to Be Outside',
  summary: 'Xu Kai and Jian Yue are finally in the same cell. She is furious, he is delighted to see her alive, and neither is emotionally mature enough to say the important part directly.',
  readingMinutes: 10,
  tags: ['reunion', 'jian-yue', 'xu-kai', 'romance', 'captivity'],
  segments: [
    { kind: 'paragraph', text: 'For the first minute after Xu Kai was chained beside her, Jian Yue said nothing.' },
    { kind: 'paragraph', text: 'This frightened him more than the kidnapping.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Oi.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'No.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You have not heard my defense.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You came alone into the place where I was kidnapped.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Technically I was escorted.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'I am going to strangle you with these chains.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Good. You are recovering.', accent: 'primary' },
    { kind: 'paragraph', text: 'Her anger cracked for half a second.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Are you hurt?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Emotionally.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Xu Kai.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'No.', accent: 'primary' },
    { kind: 'paragraph', text: 'She stared.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I am not hurt.', accent: 'primary' },
    { kind: 'paragraph', text: 'Only then did her shoulders loosen.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'That looked suspiciously like concern.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'I was checking state property.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I am an Examiner now. I have upgraded to office equipment.', accent: 'primary' },
    { kind: 'paragraph', text: 'Qin Ruo was held in a separate chamber beyond the wall.' },
    { kind: 'paragraph', text: 'Xu Kai knew because every fourth knock from the pipe behind them was deliberate.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'What are you listening to?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Our neighbor has opinions.', accent: 'primary' },
    { kind: 'paragraph', text: 'He tapped twice against the wall.' },
    { kind: 'paragraph', text: 'Three taps answered.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'That means something?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Not yet. I am making it up as we go.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Wonderful.', accent: 'secondary' },
    { kind: 'paragraph', text: 'He looked at the tonic bowl.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'How often?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Every six hours.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'And if you refuse?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'They threaten the other prisoners.', accent: 'secondary' },
    { kind: 'paragraph', text: 'His expression changed.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Do not do that.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Do what?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'The quiet thing.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You complain when I talk. You complain when I do not.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Yes.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Very consistent.', accent: 'primary' },
    { kind: 'paragraph', text: 'He leaned back against the wall.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I am getting you out.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Us.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'What?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You are getting us out.', accent: 'secondary' },
    { kind: 'paragraph', text: 'He smiled.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Bossy even in chains.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Especially in chains.', accent: 'secondary' },
  ],
};

const chapter56: Chapter = {
  id: 's01-c56',
  season: 1,
  number: 56,
  title: 'The Common Scale Breaks in Half',
  summary: 'Xu Kai discovers the kidnapping coalition is already fracturing and starts a civil war made entirely of questions.',
  readingMinutes: 11,
  tags: ['common-scale', 'qin-ruo', 'wei-cang', 'psychology', 'rescue'],
  segments: [
    { kind: 'paragraph', text: 'The Common Scale had one fatal weakness.' },
    { kind: 'paragraph', text: 'Most of its members believed their own pamphlets.' },
    { kind: 'paragraph', text: 'Wei Cang no longer did.' },
    { kind: 'dialogue', speaker: 'Wei Cang', text: 'The capital is functioning without her.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Is it?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Wei Cang', text: 'Markets are open. Provincial offices continue operating. No riots. No panic.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Excellent. Release her.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Wei Cang', text: 'Not yet.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Then the experiment ended and the kidnapping began.', accent: 'primary' },
    { kind: 'paragraph', text: 'Two guards looked at each other.' },
    { kind: 'dialogue', speaker: 'Wei Cang', text: 'We need seventy-two hours.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Why?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Wei Cang', text: 'That was the agreed period.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Agreed by whom?', accent: 'primary' },
    { kind: 'paragraph', text: 'A third guard looked away.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'There it is.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Wei Cang', text: 'There is what?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Half your people thought this ended when the point was proven.', accent: 'primary' },
    { kind: 'paragraph', text: 'Wei Cang said nothing.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Qin Ruo certainly did.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Wei Cang', text: 'Qin Ruo lacked resolve.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'He lacked kidnapping.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'An underrated quality.', accent: 'primary' },
    { kind: 'paragraph', text: 'Wei Cang ordered them separated.' },
    { kind: 'paragraph', text: 'Xu Kai objected loudly enough for everyone in the corridor to hear.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Before I go, ask him one thing.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Common Scale Guard', text: 'What?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'If the demonstration succeeded, why are you still hiding?', accent: 'primary' },
    { kind: 'paragraph', text: 'Nobody answered.' },
    { kind: 'paragraph', text: 'That question reached three chambers before Xu Kai did.' },
    { kind: 'paragraph', text: 'By evening, Common Scale volunteers were arguing in the corridors.' },
    { kind: 'paragraph', text: 'One group wanted Jian Yue released.' },
    { kind: 'paragraph', text: 'Another wanted a public statement first.' },
    { kind: 'paragraph', text: 'Wei Cang wanted control.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You started a mutiny while chained to a wall.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I asked a question.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You asked it maliciously.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Tone is important.', accent: 'primary' },
    { kind: 'paragraph', text: 'A hidden latch clicked in the neighboring wall.' },
    { kind: 'paragraph', text: 'Qin Ruo stepped through a maintenance panel with one wrist still tied.' },
    { kind: 'dialogue', speaker: 'Qin Ruo', text: 'Your tracking bells are driving them mad.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Good. I paid for three.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You paid?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Lu Chen will reimburse me.', accent: 'primary' },
    { kind: 'paragraph', text: 'Far above, a bell rang again.' },
    { kind: 'paragraph', text: 'The Common Scale started moving prisoners.' },
  ],
};

const chapter57: Chapter = {
  id: 's01-c57',
  season: 1,
  number: 57,
  title: 'The Problem with Killing a Civilian',
  summary: 'Wei Cang abandons the demonstration and decides a dead Pillar will make a stronger point. Xu Kai uses every argument he has before reaching the one answer he hates using.',
  readingMinutes: 11,
  tags: ['wei-cang', 'danger', 'jian-yue', 'xu-kai', 'turning-point'],
  segments: [
    { kind: 'paragraph', text: 'At the sixty-first hour, Wei Cang changed the experiment.' },
    { kind: 'paragraph', text: 'He did it because he was losing control.' },
    { kind: 'paragraph', text: 'People who lose control often rename panic as conviction.' },
    { kind: 'dialogue', speaker: 'Wei Cang', text: 'The Five will never permit reform after this.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Qin Ruo', text: 'Because you kidnapped one of them.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Wei Cang', text: 'Because power protects itself.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You are making a very strong argument for arresting you.', accent: 'primary' },
    { kind: 'paragraph', text: 'Wei Cang entered the chamber wearing old mountain-command armor and carrying a broad saber.' },
    { kind: 'paragraph', text: 'Even with her meridians suppressed, Jian Yue shifted between him and Xu Kai.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Oi.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Quiet.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You can barely stand.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Still standing.', accent: 'secondary' },
    { kind: 'paragraph', text: 'Wei Cang looked almost sad.' },
    { kind: 'dialogue', speaker: 'Wei Cang', text: 'That is the disease. Even weakened, everyone expects you to stand in front.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Nobody asked me.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Wei Cang', text: 'Exactly.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You are confusing choice with structure.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Wei Cang', text: 'And you are defending the structure because you sit at its table now.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I hate that table.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Wei Cang', text: 'You became an Examiner. You gained the sixth chair. The system absorbed you.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Or I sat down because chairs are easier to move from inside the room.', accent: 'primary' },
    { kind: 'paragraph', text: 'Qin Ruo stepped beside Xu Kai.' },
    { kind: 'dialogue', speaker: 'Qin Ruo', text: 'Release her. We proved the point.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Wei Cang', text: 'No. We proved they can survive without one Pillar. Now we prove the Five themselves are not sacred.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Jian Yue understood first.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You are going to kill me.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Wei Cang', text: 'I am going to make the country choose what comes after you.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Bad plan.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Wei Cang', text: 'You have said that about better men than me.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Yes. Most listened eventually.', accent: 'primary' },
    { kind: 'paragraph', text: 'Wei Cang raised the saber.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'If you kill her, every reform you wanted becomes her funeral procession.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Wei Cang', text: 'Then people will finally ask why one death matters so much.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Because she is a person.', accent: 'primary' },
    { kind: 'paragraph', text: 'Wei Cang hesitated.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'That is the part both sides keep forgetting.', accent: 'primary' },
    { kind: 'paragraph', text: 'For a moment, it almost worked.' },
    { kind: 'paragraph', text: 'Then an alarm bell rang above.' },
    { kind: 'paragraph', text: 'Wei Cang thought the Five had arrived.' },
    { kind: 'paragraph', text: 'Panic won.' },
    { kind: 'paragraph', text: 'He struck.' },
  ],
};

const chapter58: Chapter = {
  id: 's01-c58',
  season: 1,
  number: 58,
  title: 'For Once, Stay Behind Me',
  summary: 'Jian Yue cannot fight, Wei Cang refuses to stop, and Xu Kai finally uses the solution he has avoided for the entire story.',
  readingMinutes: 10,
  tags: ['martial-reveal', 'xu-kai', 'jian-yue', 'rescue', 'romance'],
  segments: [
    { kind: 'paragraph', text: 'Wei Cang\'s saber came down fast enough to split the stone bench behind Jian Yue.' },
    { kind: 'paragraph', text: 'Jian Yue tried to move.' },
    { kind: 'paragraph', text: 'Black reed locked her meridians before her body cleared the first step.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Xu Kai, move!', accent: 'secondary' },
    { kind: 'paragraph', text: 'He did.' },
    { kind: 'paragraph', text: 'Forward.' },
    { kind: 'paragraph', text: 'For the first time since she had met him, Xu Kai stepped in front of Jian Yue.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Oi.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'What are you doing?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'For once, stay behind me.', accent: 'primary' },
    { kind: 'paragraph', text: 'Wei Cang\'s saber reached him.' },
    { kind: 'paragraph', text: 'Xu Kai caught the blade between two fingers.' },
    { kind: 'paragraph', text: 'The chamber became very quiet.' },
    { kind: 'paragraph', text: 'Wei Cang pulled.' },
    { kind: 'paragraph', text: 'The saber did not move.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: '...What?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'This is why I prefer arguments.', accent: 'primary' },
    { kind: 'paragraph', text: 'He twisted his wrist.' },
    { kind: 'paragraph', text: 'The broad saber snapped at the midpoint.' },
    { kind: 'paragraph', text: 'Wei Cang stared at the broken steel.' },
    { kind: 'dialogue', speaker: 'Wei Cang', text: 'Who are you?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'We spent forty-four chapters on that problem.', accent: 'primary' },
    { kind: 'paragraph', text: 'Wei Cang drove both palms forward.' },
    { kind: 'paragraph', text: 'The strike carried enough internal force to crater the floor.' },
    { kind: 'paragraph', text: 'Xu Kai touched one palm with two fingers.' },
    { kind: 'paragraph', text: 'Wei Cang\'s internal energy vanished from the attack as if someone had closed a door.' },
    { kind: 'paragraph', text: 'Xu Kai tapped him once in the chest.' },
    { kind: 'paragraph', text: 'Wei Cang crossed the chamber, went through the wooden partition, and stopped inside the next wall.' },
    { kind: 'paragraph', text: 'He remained conscious just long enough to look offended by physics.' },
    { kind: 'paragraph', text: 'Then he slid to the floor.' },
    { kind: 'dialogue', speaker: 'Qin Ruo', text: '...', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You saw nothing useful.', accent: 'primary' },
    { kind: 'paragraph', text: 'Qin Ruo looked at the wall.' },
    { kind: 'dialogue', speaker: 'Qin Ruo', text: 'I saw a structural failure.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Excellent civic instinct.', accent: 'primary' },
    { kind: 'paragraph', text: 'He turned back to Jian Yue.' },
    { kind: 'paragraph', text: 'She was staring at him.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Oi.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Do not oi me.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You appear upset.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'YOU CAUGHT A SABER.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'It was coming toward you.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'WITH YOUR FINGERS.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I only had the two available hands.', accent: 'primary' },
    { kind: 'paragraph', text: 'She made a sound usually associated with people discovering tax fraud in their own name.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'I have been protecting you.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Very well, too.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'I HAVE BEEN PROTECTING YOU.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I heard the first version.', accent: 'primary' },
    { kind: 'paragraph', text: 'Another alarm sounded above.' },
    { kind: 'paragraph', text: 'Xu Kai crouched in front of her.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Can you walk?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'I can murder you.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Promising. Can you walk while doing it?', accent: 'primary' },
    { kind: 'paragraph', text: 'She tried.' },
    { kind: 'paragraph', text: 'Her knees failed.' },
    { kind: 'paragraph', text: 'Xu Kai caught her before she hit the floor.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Do not get used to this.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You are surprisingly heavy.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Put me down.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'No.', accent: 'primary' },
    { kind: 'paragraph', text: 'For once, she was the one being carried out.' },
  ],
};

const chapter59: Chapter = {
  id: 's01-c59',
  season: 1,
  number: 59,
  title: 'I Have Been Protecting You for Months',
  summary: 'Xu Kai carries Jian Yue through a collapsing rescue operation while she processes betrayal, relief, embarrassment, and an unreasonable amount of hidden strength.',
  readingMinutes: 10,
  tags: ['escape', 'romance', 'martial-secret', 'jian-yue', 'xu-kai'],
  segments: [
    { kind: 'paragraph', text: 'Jian Yue spent the first corridor in Xu Kai\'s arms planning his murder.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Put me down.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You said that.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'I mean it more now.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Your legs disagree.', accent: 'primary' },
    { kind: 'paragraph', text: 'Qin Ruo led them through a maintenance route while Common Scale members argued at every junction.' },
    { kind: 'paragraph', text: 'Most lowered their weapons when they saw Wei Cang unconscious.' },
    { kind: 'paragraph', text: 'The few who did not were talked down by Qin Ruo before Xu Kai needed to do anything inconvenient.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'How strong are you?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'This seems like a poor time.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'How. Strong.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Strong enough to carry a very angry woman through a tunnel.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Xu Kai.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Later.', accent: 'primary' },
    { kind: 'paragraph', text: 'She went quiet.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'That was easier than expected.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'I am saving energy so I can hit you later.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'There she is.', accent: 'primary' },
    { kind: 'paragraph', text: 'At the upper freight gate, a dozen armed volunteers blocked the passage.' },
    { kind: 'paragraph', text: 'Xu Kai stopped.' },
    { kind: 'dialogue', speaker: 'Common Scale Captain', text: 'Put her down.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Popular request today.', accent: 'primary' },
    { kind: 'paragraph', text: 'Qin Ruo stepped forward and held up Wei Cang\'s command seal.' },
    { kind: 'dialogue', speaker: 'Qin Ruo', text: 'The demonstration is over. Anyone who continues is not acting for the Common Scale.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Nine lowered weapons.' },
    { kind: 'paragraph', text: 'Three did not.' },
    { kind: 'paragraph', text: 'Jian Yue felt Xu Kai shift his weight.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Do not.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Do not what?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Whatever ridiculous thing you were about to do.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I was going to ask politely.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Liar.', accent: 'secondary' },
    { kind: 'paragraph', text: 'Qin Ruo talked the last three down.' },
    { kind: 'paragraph', text: 'The freight gate opened.' },
    { kind: 'paragraph', text: 'Cold night air reached them.' },
    { kind: 'paragraph', text: 'Jian Yue closed her eyes for one second.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Oi.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'What?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I was scared.', accent: 'primary' },
    { kind: 'paragraph', text: 'She opened her eyes.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'When the yard collapsed. I was scared.', accent: 'primary' },
    { kind: 'paragraph', text: 'Her anger lost its shape.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Idiot.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Yes.', accent: 'primary' },
    { kind: 'paragraph', text: 'She stopped asking to be put down.' },
  ],
};

const chapter60: Chapter = {
  id: 's01-c60',
  season: 1,
  number: 60,
  title: 'The Lie Jian Yue Tells the Five',
  summary: 'The other Pillars arrive to recover Jian Yue. She immediately decides that Xu Kai\'s impossible secret belongs to her before it belongs to the state.',
  readingMinutes: 10,
  tags: ['five-pillars', 'secret', 'jian-yue', 'xu-kai', 'trust'],
  segments: [
    { kind: 'paragraph', text: 'Han Zhen arrived twelve minutes after the freight gate opened.' },
    { kind: 'paragraph', text: 'He arrived through a wall.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Architecture continues to suffer under government service.', accent: 'primary' },
    { kind: 'paragraph', text: 'Yan Shuo came through the actual gate.' },
    { kind: 'paragraph', text: 'Lu Chen came with physicians.' },
    { kind: 'paragraph', text: 'Bai Ren came with a blanket.' },
    { kind: 'dialogue', speaker: 'Bai Ren', text: 'You look terrible.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Thank you.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Bai Ren', text: 'Him too.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Unnecessary.', accent: 'primary' },
    { kind: 'paragraph', text: 'Han Zhen saw the broken inner wall.' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'What happened?', accent: 'neutral' },
    { kind: 'paragraph', text: 'Xu Kai looked at Jian Yue.' },
    { kind: 'paragraph', text: 'Jian Yue looked at Xu Kai.' },
    { kind: 'paragraph', text: 'One entire conversation happened without sound.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'I recovered enough internal energy to stop Wei Cang.', accent: 'secondary' },
    { kind: 'paragraph', text: 'Xu Kai blinked once.' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'With black reed still active?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Briefly.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'That explains the wall?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Yes.', accent: 'secondary' },
    { kind: 'paragraph', text: 'Qin Ruo examined the ceiling with profound civic interest.' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'And Xu Kai?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Was useless.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Cruel.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'He complained and got in the way.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Historically accurate.', accent: 'primary' },
    { kind: 'paragraph', text: 'Lu Chen narrowed his eyes.' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'You are both lying.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Prove it.', accent: 'secondary' },
    { kind: 'paragraph', text: 'Lu Chen looked at Xu Kai.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I am deeply offended by the atmosphere of distrust.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'That did not help.', accent: 'neutral' },
    { kind: 'paragraph', text: 'The physicians carried Jian Yue toward the waiting carriage.' },
    { kind: 'paragraph', text: 'As they passed, she caught Xu Kai by the sleeve.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You are coming.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Concern.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Evidence control.', accent: 'secondary' },
    { kind: 'paragraph', text: 'Han Zhen watched her hand on his sleeve.' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'I see.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You see nothing.', accent: 'secondary' },
    { kind: 'paragraph', text: 'Xu Kai smiled because some things survived every crisis.' },
  ],
};

const chapter61: Chapter = {
  id: 's01-c61',
  season: 1,
  number: 61,
  title: 'The Common Scale, Measured Properly',
  summary: 'The kidnapping ends, but Xu Kai refuses to let the government answer a bad reform movement with an easy purge.',
  readingMinutes: 11,
  tags: ['aftermath', 'reform', 'qin-ruo', 'common-scale', 'politics'],
  segments: [
    { kind: 'paragraph', text: 'Han Zhen wanted the Common Scale dismantled before sunrise.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'No.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'They kidnapped a Pillar.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Wei Cang\'s cell kidnapped a Pillar.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'They shared his ideology.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Half the Finance Council shares your ideology. We have not arrested them for military conquest yet.', accent: 'primary' },
    { kind: 'paragraph', text: 'Jian Yue was supposed to be resting.' },
    { kind: 'paragraph', text: 'She attended the meeting under a blanket anyway.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'He is right.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'You were kidnapped.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'I noticed.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Qin Ruo', text: 'The Common Scale should face investigation. But if every provincial reformer is treated as a conspirator, Wei Cang wins after losing.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Xu Kai proposed an alternative.' },
    { kind: 'paragraph', text: 'Separate criminal responsibility from political reform.' },
    { kind: 'paragraph', text: 'Arrest everyone involved in the abduction, poisoning, coercion, and unlawful detention.' },
    { kind: 'paragraph', text: 'Audit the Common Scale\'s finances.' },
    { kind: 'paragraph', text: 'Then publicly adopt the reforms that were sensible anyway.' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'You want to reward them?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I want to avoid making kidnapping the only successful route to policy change.', accent: 'primary' },
    { kind: 'paragraph', text: 'That stopped the room.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'If the government rejects every good idea because a criminal also liked it, criminals gain veto power over good ideas.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Bai Ren', text: 'Annoyingly sensible.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'That is his worst habit.', accent: 'secondary' },
    { kind: 'paragraph', text: 'The final reform package established provincial emergency teams, redundant communications, local evacuation authority, and mandatory response exercises without National-Tier participation.' },
    { kind: 'paragraph', text: 'Qin Ruo agreed to chair the civilian commission.' },
    { kind: 'paragraph', text: 'Wei Cang was placed under state custody pending trial.' },
    { kind: 'dialogue', speaker: 'Wei Cang', text: 'You preserved the system.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'No. I made it harder to need you next time.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Wei Cang', text: 'And the Five?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Still useful.', accent: 'primary' },
    { kind: 'paragraph', text: 'Wei Cang almost smiled.' },
    { kind: 'dialogue', speaker: 'Wei Cang', text: 'That will disappoint them.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Good institutions should occasionally disappoint powerful people.', accent: 'primary' },
  ],
};

const chapter62: Chapter = {
  id: 's01-c62',
  season: 1,
  number: 62,
  title: 'State Security, Revised',
  summary: 'Jian Yue returns home knowing Xu Kai\'s secret. Publicly nothing changes. Privately, absolutely everything does.',
  readingMinutes: 10,
  tags: ['slice-of-life', 'romance', 'martial-secret', 'jian-yue', 'xu-kai'],
  segments: [
    { kind: 'paragraph', text: 'Three days after the rescue, Jian Yue returned to the residence next door.' },
    { kind: 'paragraph', text: 'Xu Kai had replaced her door latch.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Why?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'The old one offended me.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You were worried.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'The old one was structurally judgmental.', accent: 'primary' },
    { kind: 'paragraph', text: 'She opened her door.' },
    { kind: 'paragraph', text: 'A basket of food sat inside.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You cooked?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I hired competence.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Coward.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Alive coward.', accent: 'primary' },
    { kind: 'paragraph', text: 'She turned slowly.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'We are discussing it now.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'The food?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Your fingers.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'All ten remain present.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You caught Wei Cang\'s saber with two of them.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Efficient use of resources.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'I hate you.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'No, you do not.', accent: 'primary' },
    { kind: 'paragraph', text: 'She froze.' },
    { kind: 'paragraph', text: 'So did he.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'That came out more confident than intended.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Good.', accent: 'secondary' },
    { kind: 'paragraph', text: 'Now he froze properly.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Do not look so pleased.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'State security has improved dramatically.', accent: 'primary' },
    { kind: 'paragraph', text: 'She threw a cushion at him.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'From now on, if I step in front of you in public, you stay behind me.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You know that is unnecessary.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'It preserves your secret.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'And your dignity?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Mostly my dignity.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Understood, Oi.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'And do not think this means I am done being angry.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I would never insult your stamina.', accent: 'primary' },
  ],
};

const chapter63: Chapter = {
  id: 's01-c63',
  season: 1,
  number: 63,
  title: 'How Strong Are You?',
  summary: 'Jian Yue drags Xu Kai outside the capital at dawn and demands the answer he has spent months avoiding.',
  readingMinutes: 10,
  tags: ['martial-secret', 'sparring', 'jian-yue', 'xu-kai', 'romance'],
  segments: [
    { kind: 'paragraph', text: 'Jian Yue woke Xu Kai before sunrise.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'This is violence.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Get dressed.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Threatening civilians at dawn. The Common Scale was right about institutional abuse.', accent: 'primary' },
    { kind: 'paragraph', text: 'She took him to an abandoned military practice ground beyond the western wall.' },
    { kind: 'paragraph', text: 'No guards. No witnesses. No buildings close enough for Lu Chen to hide inside.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Fight me.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'No.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'That answer has become irritating.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'It was always irritating.', accent: 'primary' },
    { kind: 'paragraph', text: 'She drew her sword.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Oi.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You lied to me for months.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I carefully avoided answering questions you did not ask.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Fight me.', accent: 'secondary' },
    { kind: 'paragraph', text: 'She attacked.' },
    { kind: 'paragraph', text: 'Not at full National-Tier strength.' },
    { kind: 'paragraph', text: 'At first.' },
    { kind: 'paragraph', text: 'Xu Kai stepped aside.' },
    { kind: 'paragraph', text: 'Second strike.' },
    { kind: 'paragraph', text: 'He was somewhere else.' },
    { kind: 'paragraph', text: 'Third.' },
    { kind: 'paragraph', text: 'Fourth.' },
    { kind: 'paragraph', text: 'Jian Yue stopped being polite.' },
    { kind: 'paragraph', text: 'The practice field erupted beneath a crimson arc.' },
    { kind: 'paragraph', text: 'Xu Kai moved through it without drawing a weapon.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Stop smiling.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You are very serious before breakfast.', accent: 'primary' },
    { kind: 'paragraph', text: 'She appeared directly in front of him.' },
    { kind: 'paragraph', text: 'Her sword stopped one finger from his throat.' },
    { kind: 'paragraph', text: 'Because Xu Kai was holding her wrist.' },
    { kind: 'paragraph', text: 'Jian Yue looked down.' },
    { kind: 'paragraph', text: 'She had not seen him move.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Let go.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You asked me to fight.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'I am reconsidering.', accent: 'secondary' },
    { kind: 'paragraph', text: 'He released her immediately.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Compared to Han Zhen?', accent: 'secondary' },
    { kind: 'paragraph', text: 'Xu Kai looked toward the sunrise.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Do you actually want the answer?', accent: 'primary' },
    { kind: 'paragraph', text: 'Jian Yue studied him.' },
    { kind: 'paragraph', text: 'For the first time, she understood the shape of the question.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'No.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Good.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'That was not comforting.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'It was not meant to be.', accent: 'primary' },
    { kind: 'paragraph', text: 'She sheathed her sword.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Why hide it?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Because the moment people know you can break the board, they stop asking whether the game was stupid.', accent: 'primary' },
    { kind: 'paragraph', text: 'She thought about Qingshi, White Bridge, the frontier, Heshan, and Gao Wen.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You really would rather argue.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Much more entertaining.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You are insane.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'That has always been public information.', accent: 'primary' },
  ],
};

const chapter64: Chapter = {
  id: 's01-c64',
  season: 1,
  number: 64,
  title: 'The Sixth Chair Has a Secret',
  summary: 'Xu Kai returns to the Hall of Five with Jian Yue as the only Pillar who knows what he really is. Then a letter arrives from a past that finally knows how to find him.',
  readingMinutes: 11,
  tags: ['hall-of-five', 'secret', 'next-arc', 'martial-past', 'romance'],
  segments: [
    { kind: 'paragraph', text: 'The Hall of Five met two days later to review Common Scale reforms.' },
    { kind: 'paragraph', text: 'Xu Kai occupied the sixth chair.' },
    { kind: 'paragraph', text: 'Jian Yue sat beside him and discovered that knowing his secret made every ordinary sentence absurd.' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'If another armed cell targets the capital, Xu Kai remains behind the Pillars.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Agreed.', accent: 'secondary' },
    { kind: 'paragraph', text: 'Xu Kai looked at her.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Enthusiastic.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'State security.', accent: 'secondary' },
    { kind: 'paragraph', text: 'She kicked his ankle under the table.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Abuse.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'You two have become more suspicious since the kidnapping.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'No.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Definitely.', accent: 'primary' },
    { kind: 'paragraph', text: 'Jian Yue kicked him again.' },
    { kind: 'dialogue', speaker: 'Bai Ren', text: 'Healthy recovery.', accent: 'neutral' },
    { kind: 'paragraph', text: 'The reforms passed.' },
    { kind: 'paragraph', text: 'Provincial emergency commands gained authority to act for the first six hours of a crisis without waiting for central approval.' },
    { kind: 'paragraph', text: 'Every region would run quarterly exercises without Pillar participation.' },
    { kind: 'paragraph', text: 'The Five remained guardians, but no longer the first item in every emergency manual.' },
    { kind: 'dialogue', speaker: 'Qin Ruo', text: 'It is less than I wanted.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Then it is probably legislation.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Qin Ruo', text: 'You joke about everything.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Unfortunately.', accent: 'secondary' },
    { kind: 'paragraph', text: 'A palace courier entered before the meeting ended.' },
    { kind: 'paragraph', text: 'He carried no ministry seal.' },
    { kind: 'paragraph', text: 'The envelope was plain black paper closed with white wax.' },
    { kind: 'dialogue', speaker: 'Courier', text: 'For Examiner Xu Kai.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'That color scheme feels judgmental.', accent: 'primary' },
    { kind: 'paragraph', text: 'He opened it.' },
    { kind: 'paragraph', text: 'There was one sheet inside.' },
    { kind: 'paragraph', text: 'No greeting.' },
    { kind: 'paragraph', text: 'No signature.' },
    { kind: 'paragraph', text: 'Only one line.' },
    { kind: 'paragraph', text: 'TO THE MAN WHO ENDED BLACK RAIN IN ONE NIGHT: WE FOUND YOU.' },
    { kind: 'paragraph', text: 'Xu Kai stopped moving.' },
    { kind: 'paragraph', text: 'Jian Yue noticed.' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'What is Black Rain?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Weather.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'No.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Worth trying.', accent: 'primary' },
    { kind: 'paragraph', text: 'Jian Yue held out her hand.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Let me see.', accent: 'secondary' },
    { kind: 'paragraph', text: 'He gave her the letter.' },
    { kind: 'paragraph', text: 'Her eyes met his after reading it.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Later.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Later.', accent: 'primary' },
    { kind: 'paragraph', text: 'Han Zhen looked between them.' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'You know something.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'No.', accent: 'secondary' },
    { kind: 'paragraph', text: 'Xu Kai looked at her.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Terrible liar.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Oi.', accent: 'secondary' },
    { kind: 'paragraph', text: 'He went silent immediately.' },
    { kind: 'paragraph', text: 'Bai Ren slowly smiled.' },
    { kind: 'paragraph', text: 'The secret at the sixth chair had just become much harder to keep.' },
  ],
};

const newChapters = [chapter55, chapter56, chapter57, chapter58, chapter59, chapter60, chapter61, chapter62, chapter63, chapter64];

export const seasons: Season[] = baseSeasons.map((season) => {
  if (season.number !== 1) {
    return season;
  }

  return {
    ...season,
    subtitle: 'A dangerous civilian acquires a National-Tier supervisor, rescues her, and accidentally gives her the most inconvenient secret in the country.',
    description: 'Xu Kai still prefers wit, systems, and shameless manipulation to force. Jian Yue now knows there was always another reason he found violence boring: when he finally uses it, even National-Tier assumptions stop making sense.',
    chapters: [...season.chapters, ...newChapters],
  };
});
