import type { Chapter, Season } from '../domain/types';
import { seasons as baseSeasons } from './story-v13';

const chapter81: Chapter = {
  id: 's01-c81',
  season: 1,
  number: 81,
  title: 'Dinner Is Also State Business',
  summary: 'Liangbei wants Xu Kai immediately. Jian Yue wants the dinner he promised first. For once, the smaller diplomatic crisis wins.',
  readingMinutes: 10,
  tags: ['romance', 'liangbei', 'transition', 'xu-kai', 'jian-yue'],
  segments: [
    { kind: 'paragraph', text: 'The palace clerk made the mistake of believing an international emergency outranked dinner.' },
    { kind: 'dialogue', speaker: 'Palace Clerk', text: 'Liangbei requests departure before dawn.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Tomorrow has a dawn too.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Diplomacy begins with compromise.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Palace Clerk', text: 'This is an emergency treaty negotiation.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'He owes me dinner.', accent: 'secondary' },
    { kind: 'paragraph', text: 'The clerk looked at Xu Kai for help.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I advise surrender.', accent: 'primary' },
    { kind: 'paragraph', text: 'They ate noodles at a small shop three streets from the Hall of Five.' },
    { kind: 'paragraph', text: 'Jian Yue ordered for both of them because Xu Kai had spent eleven minutes pretending to study a menu he already knew.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You chose the spicy broth.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You survived Black Rain.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Different threat profile.', accent: 'primary' },
    { kind: 'paragraph', text: 'She almost smiled.' },
    { kind: 'paragraph', text: 'Then the gold-edged Liangbei scroll on the table caught her eye.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You have been avoiding opening the second page.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I dislike sequels.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Open it.', accent: 'secondary' },
    { kind: 'paragraph', text: 'He did.' },
    { kind: 'paragraph', text: 'The formal request concerned tariff guarantees, border arbitration, and a mutual emergency-response pact.' },
    { kind: 'paragraph', text: 'The handwritten postscript did not.' },
    { kind: 'paragraph', text: 'COME PERSONALLY. THE EMPTY THRONE HAS BEEN OPENED.' },
    { kind: 'paragraph', text: 'Xu Kai stopped turning his chopsticks.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Empty Throne?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'An old archive.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'That was a bad lie.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I am tired.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Try again.', accent: 'secondary' },
    { kind: 'paragraph', text: 'For several breaths, he watched steam rise from the noodles.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Seven years ago Liangbei nearly tore itself apart choosing an emperor.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'I know the succession war.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You know the version they print.', accent: 'primary' },
    { kind: 'paragraph', text: 'That changed the air between them.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Were you there?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Unfortunately.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'What did you do?', accent: 'secondary' },
    { kind: 'paragraph', text: 'Xu Kai looked down at his bowl.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Dinner first.', accent: 'primary' },
    { kind: 'paragraph', text: 'She could have pushed.' },
    { kind: 'paragraph', text: 'She did not.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Fine.', accent: 'secondary' },
    { kind: 'paragraph', text: 'Three bites later, Xu Kai spoke without looking up.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Oi.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'What?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'When we get there, people will tell you things about me.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'People already tell me things about you.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'These will be worse.', accent: 'primary' },
    { kind: 'paragraph', text: 'She set down her chopsticks.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Are they lies?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Not all of them.', accent: 'primary' },
    { kind: 'paragraph', text: 'That answer frightened her more than denial would have.' },
  ],
};

const chapter82: Chapter = {
  id: 's01-c82',
  season: 1,
  number: 82,
  title: 'Liangbei Remembers a Monster',
  summary: 'Xu Kai returns to a capital that once taught children to fear a faceless conspirator called the Black Minister. Jian Yue discovers the resemblance is not metaphorical.',
  readingMinutes: 11,
  tags: ['liangbei', 'mystery', 'black-minister', 'history', 'suspense'],
  segments: [
    { kind: 'paragraph', text: 'Liangbei greeted foreign dignitaries with white stone gates, bronze bells, and a mural depicting the worst political criminals in its modern history.' },
    { kind: 'paragraph', text: 'Xu Kai was third from the left.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'That one has your posture.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Rude posture.', accent: 'primary' },
    { kind: 'paragraph', text: 'The painted figure wore black robes and had no face.' },
    { kind: 'paragraph', text: 'Behind him, seven burning sect banners leaned over a cracked throne.' },
    { kind: 'paragraph', text: 'Beneath the mural, old characters read: THE BLACK MINISTER KAI, ENEMY OF THRONE AND ORTHODOXY.' },
    { kind: 'paragraph', text: 'Jian Yue read it twice.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Kai.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Common name.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Seven sect banners.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Coincidence remains underfunded.', accent: 'primary' },
    { kind: 'paragraph', text: 'Lin Shuying waited beyond the gate.' },
    { kind: 'paragraph', text: 'For once she did not look amused.' },
    { kind: 'dialogue', speaker: 'Lin Shuying', text: 'Welcome back.', accent: 'neutral' },
    { kind: 'paragraph', text: 'The words were addressed to Xu Kai.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You knew?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Lin Shuying', text: 'Not when we first met. The Empty Throne archive was sealed even from foreign affairs.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'It should have stayed that way.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lin Shuying', text: 'Three witnesses disappeared after it was opened.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Xu Kai stopped.' },
    { kind: 'dialogue', speaker: 'Lin Shuying', text: 'Each received the same message first.', accent: 'neutral' },
    { kind: 'paragraph', text: 'She handed him a square of black paper.' },
    { kind: 'paragraph', text: 'Silver ink covered one side.' },
    { kind: 'paragraph', text: 'THE BOARD REMEMBERS YOU.' },
    { kind: 'paragraph', text: 'Xu Kai did not blink.' },
    { kind: 'paragraph', text: 'That was worse.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You know it.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Yes.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lin Shuying', text: 'The Black Minister used those words during the succession war.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Once.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'To whom?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Seven sect leaders, two princes, one royal treasurer, and a grain consortium.', accent: 'primary' },
    { kind: 'paragraph', text: 'Lin Shuying stared.' },
    { kind: 'dialogue', speaker: 'Lin Shuying', text: 'The textbooks say it was sent to hundreds.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'The textbooks enjoy scale.', accent: 'primary' },
    { kind: 'paragraph', text: 'They entered the capital under escort.' },
    { kind: 'paragraph', text: 'People bowed to Jian Yue.' },
    { kind: 'paragraph', text: 'A few older people stared at Xu Kai.' },
    { kind: 'paragraph', text: 'One dropped a basket.' },
    { kind: 'paragraph', text: 'Another crossed the street.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'They recognize you.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Some people remember inconveniently well.', accent: 'primary' },
    { kind: 'paragraph', text: 'At the palace steps, an old man in white sect robes blocked their path.' },
    { kind: 'paragraph', text: 'His right sleeve was empty below the elbow.' },
    { kind: 'dialogue', speaker: 'Old Sect Master', text: 'Undertaker.', accent: 'neutral' },
    { kind: 'paragraph', text: 'For the first time since Jian Yue had known him, Xu Kai looked tired before he looked amused.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Master Du.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Master Du', text: 'You should have stayed dead.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'He was never dead.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Master Du', text: 'That is not what I meant.', accent: 'neutral' },
  ],
};

const chapter83: Chapter = {
  id: 's01-c83',
  season: 1,
  number: 83,
  title: 'The Empty Throne',
  summary: 'Liangbei opens the sealed record of its succession crisis. The official villain has Xu Kai’s name, his methods, and almost none of his reasons.',
  readingMinutes: 12,
  tags: ['empty-throne', 'royalty', 'seven-sects', 'xu-kai-past', 'mystery'],
  segments: [
    { kind: 'paragraph', text: 'Empress Zhao Mei received them without a crown.' },
    { kind: 'paragraph', text: 'She was in her early forties, dressed plainly, and had the calm expression of someone who had survived becoming history.' },
    { kind: 'dialogue', speaker: 'Empress Zhao Mei', text: 'Kai.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Your Majesty.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Empress Zhao Mei', text: 'You finally acquired a family name.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'It was on sale.', accent: 'primary' },
    { kind: 'paragraph', text: 'The Empress did not smile.' },
    { kind: 'dialogue', speaker: 'Empress Zhao Mei', text: 'Still hiding inside jokes.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'They are less effective than he thinks.', accent: 'secondary' },
    { kind: 'paragraph', text: 'Zhao Mei looked at Jian Yue for several seconds.' },
    { kind: 'dialogue', speaker: 'Empress Zhao Mei', text: 'Good.', accent: 'neutral' },
    { kind: 'paragraph', text: 'The Empty Throne archive lay beneath the old audience hall.' },
    { kind: 'paragraph', text: 'Seven lacquered cabinets represented the Seven Great Sects.' },
    { kind: 'paragraph', text: 'Three iron chests represented the three royal claimants who had nearly divided Liangbei.' },
    { kind: 'paragraph', text: 'A final black box had no crest.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Yours?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Apparently I was decorative.', accent: 'primary' },
    { kind: 'paragraph', text: 'Lin Shuying opened the official chronology.' },
    { kind: 'paragraph', text: 'Seven years earlier Emperor Zhao Guang died without a universally accepted successor.' },
    { kind: 'paragraph', text: 'The Crown Prince held the central army. A younger prince controlled the northern garrisons. Zhao Mei commanded no army but held support from three provincial governors and two sects.' },
    { kind: 'paragraph', text: 'The remaining five great sects divided themselves among the claimants, neutrality, and profit.' },
    { kind: 'dialogue', speaker: 'Lin Shuying', text: 'Official history says the Black Minister forged correspondence between the factions until alliances collapsed.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I rarely forged anything.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Rarely?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Standards matter.', accent: 'primary' },
    { kind: 'paragraph', text: 'Zhao Mei opened the first cabinet.' },
    { kind: 'paragraph', text: 'Inside were letters proving Iron Bell Monastery had accepted funding from two rival princes.' },
    { kind: 'paragraph', text: 'The second cabinet held proof that Azure Cliff had blamed White Heron Pavilion for an assassination actually ordered by the royal intelligence bureau.' },
    { kind: 'paragraph', text: 'The third documented a sect patriarch selling his own disciples into private military service.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'These are real.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'That was the problem.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Empress Zhao Mei', text: 'He did not create the rot. He removed the floorboards above it.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Master Du stood at the back of the archive.' },
    { kind: 'dialogue', speaker: 'Master Du', text: 'And watched the house collapse.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'The house was already collapsing.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Master Du', text: 'So you chose who stood beneath it.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Xu Kai did not answer.' },
    { kind: 'paragraph', text: 'Jian Yue noticed that too.' },
    { kind: 'break', label: 'The black box' },
    { kind: 'paragraph', text: 'The first document bearing Kai’s own handwriting contained a list of thirteen names.' },
    { kind: 'paragraph', text: 'Beside each name was one sentence describing what the person wanted most.' },
    { kind: 'paragraph', text: 'Recognition. Revenge. Safety for a daughter. Restoration of a sect. Debt forgiveness. A governorship. A quiet retirement.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You reduced them to motives.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Yes.', accent: 'primary' },
    { kind: 'paragraph', text: 'No joke.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'At the time I thought understanding what someone wanted was the same as understanding them.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'And now?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Now I know people also order terrible noodles for reasons no rational model can explain.', accent: 'primary' },
    { kind: 'paragraph', text: 'The joke landed badly on purpose.' },
    { kind: 'dialogue', speaker: 'Empress Zhao Mei', text: 'He was eighteen.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Jian Yue turned.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Eighteen?', accent: 'secondary' },
    { kind: 'paragraph', text: 'Zhao Mei nodded.' },
    { kind: 'dialogue', speaker: 'Empress Zhao Mei', text: 'And by winter, every claimant, every great sect, and most of the court believed he was the most dangerous man in Liangbei.', accent: 'neutral' },
  ],
};

const chapter84: Chapter = {
  id: 's01-c84',
  season: 1,
  number: 84,
  title: 'Seven Sects Against One Boy',
  summary: 'A witness hearing reconstructs the months when royalty and the orthodox martial world jointly decided Kai had to die. The witnesses cannot agree whether he saved them or destroyed them.',
  readingMinutes: 12,
  tags: ['seven-sects', 'royalty', 'witnesses', 'undertaker', 'xu-kai-past'],
  segments: [
    { kind: 'paragraph', text: 'The first witness called Xu Kai a savior.' },
    { kind: 'paragraph', text: 'The second called him a butcher.' },
    { kind: 'paragraph', text: 'Both had been standing in the same city.' },
    { kind: 'dialogue', speaker: 'Former Quartermaster', text: 'He prevented the Crown Army from entering the southern refugee wards.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Retired Sect Elder', text: 'By starving three barracks until they mutinied.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Former Quartermaster', text: 'He redirected their grain.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Retired Sect Elder', text: 'Without permission.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'The permission office was attempting a coup.', accent: 'primary' },
    { kind: 'paragraph', text: 'No one laughed.' },
    { kind: 'paragraph', text: 'The third witness had been a junior disciple of White Heron Pavilion.' },
    { kind: 'dialogue', speaker: 'White Heron Elder', text: 'We were told he intended to destroy all seven sects.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Did he?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'White Heron Elder', text: 'Three withdrew from the war. Two removed their own patriarchs. One split. One tried to kill him.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'That was not my question.', accent: 'secondary' },
    { kind: 'paragraph', text: 'The elder looked at Xu Kai.' },
    { kind: 'dialogue', speaker: 'White Heron Elder', text: 'No.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Master Du struck the floor once with his cane.' },
    { kind: 'dialogue', speaker: 'Master Du', text: 'He made us destroy ourselves.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I mailed your disciples your accounting records.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Master Du', text: 'You knew what would happen.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Yes.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Master Du', text: 'My master died by his own students.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Xu Kai’s expression changed almost imperceptibly.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Your master ordered the execution of nine disciples who discovered he sold conscripts to Prince Zhao Wen.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Master Du', text: 'And that made his death just?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'No.', accent: 'primary' },
    { kind: 'paragraph', text: 'The word landed harder than argument.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'It made exposing him necessary. What happened after belongs to the people who chose it.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Master Du', text: 'Convenient.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'No.', accent: 'primary' },
    { kind: 'paragraph', text: 'He looked at the empty sleeve.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Nothing about that year was convenient.', accent: 'primary' },
    { kind: 'break', label: 'The vote to kill Kai' },
    { kind: 'paragraph', text: 'The sealed minutes were almost absurd in their unanimity.' },
    { kind: 'paragraph', text: 'Three royal factions and six of the Seven Great Sects agreed on exactly one policy.' },
    { kind: 'paragraph', text: 'KAI MUST BE REMOVED BEFORE SUCCESSION NEGOTIATIONS CONTINUE.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You united them.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Temporarily.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Against you.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'They were being difficult about alternatives.', accent: 'primary' },
    { kind: 'paragraph', text: 'Lin Shuying read the next line.' },
    { kind: 'dialogue', speaker: 'Lin Shuying', text: 'The Black Minister subsequently leaked a memorandum claiming he intended to abolish the royal house and dissolve the Seven Sects.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Did you write it?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Yes.', accent: 'primary' },
    { kind: 'paragraph', text: 'Jian Yue stared at him.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'They needed something to agree on.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'So you made yourself the enemy of the entire country.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Not the entire country.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'That is your objection?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Accuracy matters.', accent: 'primary' },
    { kind: 'paragraph', text: 'Empress Zhao Mei spoke from the end of the chamber.' },
    { kind: 'dialogue', speaker: 'Empress Zhao Mei', text: 'For nineteen days, the civil war paused because everyone wanted Kai dead first.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'What did you do with nineteen days?', accent: 'secondary' },
    { kind: 'paragraph', text: 'Xu Kai finally smiled, but there was no humor in it.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Everything.', accent: 'primary' },
  ],
};

const chapter85: Chapter = {
  id: 's01-c85',
  season: 1,
  number: 85,
  title: 'The Night of Ten Thousand Lanterns',
  summary: 'Jian Yue reads the sealed account of the night four National-Tier masters, royal guards, and thousands of soldiers converged on Kai. The official massacre and the real battle are not the same story.',
  readingMinutes: 12,
  tags: ['ten-thousand-lanterns', 'martial-past', 'undertaker', 'jian-yue', 'sealed-records'],
  segments: [
    { kind: 'paragraph', text: 'The public memorial claimed one thousand three hundred and twelve people died on the Night of Ten Thousand Lanterns.' },
    { kind: 'paragraph', text: 'The sealed casualty register listed two hundred and forty-one.' },
    { kind: 'paragraph', text: 'Jian Yue read both numbers twice.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Why the difference?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Empress Zhao Mei', text: 'Fear was politically useful after the war.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Xu Kai leaned against a cabinet with his arms folded.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Did you correct it?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'No.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Of course you did not.', accent: 'secondary' },
    { kind: 'paragraph', text: 'The surviving battle plans explained why.' },
    { kind: 'paragraph', text: 'Kai had spent eleven days bribing wagon masters, arranging false arrival times, negotiating surrender corridors, moving physicians into abandoned temples, and ensuring the seven major forces approached the capital district at different hours.' },
    { kind: 'paragraph', text: 'Three thousand soldiers never reached the battlefield because their quartermasters discovered their ammunition carts contained flour.' },
    { kind: 'paragraph', text: 'Two sect contingents arrived to find written proof that their own patriarchs planned to sacrifice them first.' },
    { kind: 'paragraph', text: 'A royal cavalry brigade encountered a bridge under repair because Xu Kai had paid the masons three weeks early.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You planned a battle so most of the army would miss it.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Battles improve significantly when fewer people attend.', accent: 'primary' },
    { kind: 'paragraph', text: 'But four National-Tier masters arrived exactly when expected.' },
    { kind: 'paragraph', text: 'Master Du had been one of them.' },
    { kind: 'dialogue', speaker: 'Master Du', text: 'He gave us three chances to leave.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'And you attacked anyway.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Master Du', text: 'We believed every hour he lived made the kingdom less governable.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Were you wrong?', accent: 'secondary' },
    { kind: 'paragraph', text: 'Master Du looked at Xu Kai.' },
    { kind: 'dialogue', speaker: 'Master Du', text: 'No.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Xu Kai did not object.' },
    { kind: 'dialogue', speaker: 'Master Du', text: 'We attacked together. Four National Tiers. Twenty-three grandmasters. Royal guards behind us.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'What happened?', accent: 'secondary' },
    { kind: 'paragraph', text: 'Master Du’s eyes went distant.' },
    { kind: 'dialogue', speaker: 'Master Du', text: 'He stopped pretending.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Silence filled the archive.' },
    { kind: 'dialogue', speaker: 'Master Du', text: 'There was no technique name. No declaration. No pressure. He simply walked forward.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Jian Yue felt the memory of Wei Cang’s broken saber in her hands.' },
    { kind: 'dialogue', speaker: 'Master Du', text: 'The first master lost before his sword cleared the sheath. The second struck him and broke his own arm. I remember reaching for him. I remember the ceiling afterward.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'And the fourth?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Master Du', text: 'Ran.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Xu Kai looked mildly offended.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Sensible man.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Master Du', text: 'You could have killed all of us.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Yes.', accent: 'primary' },
    { kind: 'paragraph', text: 'Jian Yue turned toward him.' },
    { kind: 'dialogue', speaker: 'Master Du', text: 'Then why spend six months manipulating letters, grain, sect politics, and royal marriages?', accent: 'neutral' },
    { kind: 'paragraph', text: 'Xu Kai’s answer came immediately.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Because beating you was easy.', accent: 'primary' },
    { kind: 'paragraph', text: 'Master Du flinched as though struck again.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Making sure your disciples still had homes afterward was difficult.', accent: 'primary' },
    { kind: 'paragraph', text: 'Jian Yue understood then why old men crossed streets when they saw him.' },
    { kind: 'paragraph', text: 'Not because the legends were entirely false.' },
    { kind: 'paragraph', text: 'Because the truth was harder to survive.' },
  ],
};

const chapter86: Chapter = {
  id: 's01-c86',
  season: 1,
  number: 86,
  title: 'The Decision Nobody Forgave',
  summary: 'The archive finally reaches the decision Xu Kai never let history soften: he shattered one royal army to prevent a capital massacre, knowing the frontier would bleed during the transition.',
  readingMinutes: 12,
  tags: ['moral-choice', 'xu-kai-depth', 'royalty', 'frontier', 'jian-yue'],
  segments: [
    { kind: 'paragraph', text: 'The worst document in the Empty Throne archive was only four pages long.' },
    { kind: 'paragraph', text: 'It concerned the Eastern Banner Army.' },
    { kind: 'paragraph', text: 'Sixty thousand soldiers controlled the roads into the capital.' },
    { kind: 'paragraph', text: 'Their claimant had ordered them to enter the southern districts and arrest every household suspected of supporting Zhao Mei.' },
    { kind: 'dialogue', speaker: 'Lin Shuying', text: 'Estimated civilian exposure was eighty-two thousand.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Jian Yue’s jaw tightened.' },
    { kind: 'paragraph', text: 'Kai possessed proof that the claimant had ordered an earlier refugee massacre and blamed it on a rival prince.' },
    { kind: 'paragraph', text: 'Publishing that proof would destroy the claimant’s legitimacy and fracture the Eastern Banner Army.' },
    { kind: 'paragraph', text: 'It would also leave the northeastern frontier without unified command.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'How long?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Four days if everything worked.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'And if it did not?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Longer.', accent: 'primary' },
    { kind: 'paragraph', text: 'He had tried to create a third option.' },
    { kind: 'paragraph', text: 'Three great sects had secretly accepted decades of royal subsidies in exchange for frontier obligations they had never fulfilled.' },
    { kind: 'paragraph', text: 'Kai prepared the subsidy ledgers for public release.' },
    { kind: 'paragraph', text: 'If the Eastern Banner Army broke, those sects could either admit corruption or assume the frontier defense their contracts required.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You forced them to replace the army.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I gave them an unpleasant choice.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'And it worked.', accent: 'secondary' },
    { kind: 'paragraph', text: 'Nobody answered.' },
    { kind: 'paragraph', text: 'That was how she knew the next part mattered.' },
    { kind: 'dialogue', speaker: 'Lin Shuying', text: 'The sects reached the frontier on the fifth day.', accent: 'neutral' },
    { kind: 'paragraph', text: 'One day late.' },
    { kind: 'paragraph', text: 'During that day, raiders crossed three undefended passes.' },
    { kind: 'paragraph', text: 'Five villages were hit.' },
    { kind: 'paragraph', text: 'Eighty-three civilians died.' },
    { kind: 'paragraph', text: 'Jian Yue looked at Xu Kai.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Did you know that could happen?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Yes.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'And you released the proof anyway.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Yes.', accent: 'primary' },
    { kind: 'paragraph', text: 'She hated how steady his voice was.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Would you do it again?', accent: 'secondary' },
    { kind: 'paragraph', text: 'For the first time that morning, Xu Kai looked away.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'If everything were exactly the same?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Yes.', accent: 'secondary' },
    { kind: 'paragraph', text: 'A long silence.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Yes.', accent: 'primary' },
    { kind: 'paragraph', text: 'Jian Yue closed her eyes.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'I hate that answer.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'So do I.', accent: 'primary' },
    { kind: 'paragraph', text: 'That was the first crack.' },
    { kind: 'paragraph', text: 'Not in the argument.' },
    { kind: 'paragraph', text: 'In him.' },
    { kind: 'break', label: 'Later' },
    { kind: 'paragraph', text: 'Xu Kai found Jian Yue alone on the palace roof after sunset.' },
    { kind: 'paragraph', text: 'He carried a narrow black notebook.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You asked if it hurt.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'I did not.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You were going to.', accent: 'primary' },
    { kind: 'paragraph', text: 'He handed her the notebook.' },
    { kind: 'paragraph', text: 'Eighty-three names filled the first pages.' },
    { kind: 'paragraph', text: 'Not numbers.' },
    { kind: 'paragraph', text: 'Names.' },
    { kind: 'paragraph', text: 'Beside many were tiny notes.' },
    { kind: 'paragraph', text: 'Two daughters. Made plum wine. Could not read. Kept geese. Wanted to move south. Hated winter radish.' },
    { kind: 'paragraph', text: 'Jian Yue stopped turning pages.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You knew them?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Not then.', accent: 'primary' },
    { kind: 'paragraph', text: 'His voice was very quiet.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'That was the problem.', accent: 'primary' },
    { kind: 'paragraph', text: 'She understood.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I could make the correct decision while seeing eighty-three as a cost.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Afterward I decided that if I ever had to make that kind of decision again, I would at least know what the cost was called.', accent: 'primary' },
    { kind: 'paragraph', text: 'Jian Yue held the notebook carefully.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'I still hate the decision.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Good.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Good?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Someone should.', accent: 'primary' },
  ],
};

const chapter87: Chapter = {
  id: 's01-c87',
  season: 1,
  number: 87,
  title: 'The Villain the Kingdom Needed',
  summary: 'The disappearances are solved, but the truth is another political compromise: Liangbei’s throne helped build the Black Minister myth, and Xu Kai knowingly let it happen.',
  readingMinutes: 11,
  tags: ['mystery', 'black-minister', 'empress-zhao-mei', 'politics', 'truth'],
  segments: [
    { kind: 'paragraph', text: 'The first missing witness was found in a monastery wine cellar.' },
    { kind: 'paragraph', text: 'He was annoyed, healthy, and halfway through an excellent bottle.' },
    { kind: 'dialogue', speaker: 'Missing Witness', text: 'I was told men from Iron Bell were coming to kill me.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Lin Shuying', text: 'Who told you?', accent: 'neutral' },
    { kind: 'paragraph', text: 'The witness produced a black card.' },
    { kind: 'paragraph', text: 'THE BOARD REMEMBERS YOU.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'This handwriting is too neat.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'That is your clue?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I was eighteen. My handwriting looked like a spider regretting its education.', accent: 'primary' },
    { kind: 'paragraph', text: 'The other two witnesses were found before midnight.' },
    { kind: 'paragraph', text: 'One in an abandoned tax office. One aboard a grain barge registered to the palace kitchens.' },
    { kind: 'paragraph', text: 'All three had been hidden rather than kidnapped.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'The palace.', accent: 'secondary' },
    { kind: 'paragraph', text: 'Xu Kai looked toward the imperial residence.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Yes.', accent: 'primary' },
    { kind: 'break', label: 'Midnight audience' },
    { kind: 'dialogue', speaker: 'Empress Zhao Mei', text: 'I moved them.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'And used his old message.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Empress Zhao Mei', text: 'It ensured they obeyed quickly.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You used his reputation to frighten your own witnesses.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Empress Zhao Mei', text: 'His reputation has served Liangbei for seven years.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Jian Yue stood.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Oi.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Do not Oi me.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'She is not wrong.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'That does not make it acceptable.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'No.', accent: 'primary' },
    { kind: 'paragraph', text: 'Again, he refused to make it easy for her.' },
    { kind: 'dialogue', speaker: 'Empress Zhao Mei', text: 'Sect hardliners began searching the Empty Throne records the moment the archive opened. The three witnesses were vulnerable. I moved them before anyone else could.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Lin Shuying', text: 'And summoned Xu Kai.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Empress Zhao Mei', text: 'Because the same hardliners threatened to block the Wuyuan treaty unless Liangbei formally charged the Black Minister as a war criminal.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'So this was bait.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Empress Zhao Mei', text: 'Partly.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Xu Kai rubbed his forehead.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Royalty remains exhausting.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Empress Zhao Mei', text: 'You once reorganized my government without permission.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You were welcome.', accent: 'primary' },
    { kind: 'paragraph', text: 'Zhao Mei opened a sealed decree.' },
    { kind: 'dialogue', speaker: 'Empress Zhao Mei', text: 'There is something else she should know.', accent: 'neutral' },
    { kind: 'paragraph', text: 'The decree was dated three days after the succession settlement.' },
    { kind: 'paragraph', text: 'It established the official historical commission that blamed the Black Minister for the worst excesses of the crisis.' },
    { kind: 'paragraph', text: 'At the bottom were two signatures.' },
    { kind: 'paragraph', text: 'Zhao Mei.' },
    { kind: 'paragraph', text: 'Kai.' },
    { kind: 'paragraph', text: 'Jian Yue read the second signature until the ink seemed offensive.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You agreed.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Yes.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'They blamed you for massacres you prevented.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Some.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'They blamed you for breaking the Seven Sects.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'That part had some merit.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Why?', accent: 'secondary' },
    { kind: 'paragraph', text: 'Xu Kai looked at the old decree.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Because the new government needed to be legitimate tomorrow.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'And I did not.', accent: 'primary' },
    { kind: 'paragraph', text: 'That was when Jian Yue finally understood the most frightening thing about his old reputation.' },
    { kind: 'paragraph', text: 'Xu Kai had not merely tolerated becoming the monster in the story.' },
    { kind: 'paragraph', text: 'He had helped write the monster.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Fear was useful. Fortresses surrendered when they heard I was coming. Sect elders negotiated before sending children to die. Governors discovered remarkable respect for accounting.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'And you let everyone hate you.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Hatred is survivable.', accent: 'primary' },
    { kind: 'paragraph', text: 'Jian Yue’s voice became quiet.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Was being alone?', accent: 'secondary' },
    { kind: 'paragraph', text: 'Xu Kai had no answer ready.' },
  ],
};

const chapter88: Chapter = {
  id: 's01-c88',
  season: 1,
  number: 88,
  title: 'Oi, Undertaker',
  summary: 'The treaty survives, the Black Minister remains officially unresolved, and Jian Yue refuses both easy forgiveness and easy condemnation. Xu Kai finally explains what changed after the Empty Throne.',
  readingMinutes: 12,
  tags: ['aftermath', 'romance', 'xu-kai-depth', 'treaty', 'undertaker'],
  segments: [
    { kind: 'paragraph', text: 'The emergency treaty negotiations lasted six hours.' },
    { kind: 'paragraph', text: 'The argument over Xu Kai lasted four of them.' },
    { kind: 'paragraph', text: 'Sect hardliners demanded a formal admission that the Black Minister had unlawfully coerced the royal succession.' },
    { kind: 'paragraph', text: 'Wuyuan refused to extradite its Imperial Examiner for crimes nobody could agree had occurred.' },
    { kind: 'paragraph', text: 'Xu Kai suggested everyone remove his name from the treaty and discuss the actual border.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I am flattered by the attention, but tariffs remain aggressively boring.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Master Du', text: 'You refuse judgment.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'No.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I refuse to let a trade treaty become a trial because seven old men want history to choose one emotion.', accent: 'primary' },
    { kind: 'paragraph', text: 'That ended more debate than expected.' },
    { kind: 'paragraph', text: 'The final agreement created joint border verification teams, emergency trade guarantees, and a permanent mechanism for resolving military-order disputes before mobilization.' },
    { kind: 'paragraph', text: 'The clause regarding the Black Minister was one sentence.' },
    { kind: 'paragraph', text: 'THE EVENTS OF THE EMPTY THRONE SHALL REMAIN SUBJECT TO HISTORICAL REVIEW.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'That is cowardly.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'It is diplomacy.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Same thing with better chairs.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You are learning.', accent: 'primary' },
    { kind: 'break', label: 'The old south wall' },
    { kind: 'paragraph', text: 'That evening Jian Yue made Xu Kai walk with her to the old south wall.' },
    { kind: 'paragraph', text: 'Seven years earlier, one of the royal armies had camped beyond it waiting for orders to enter the city.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'I have decided something.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Dangerous opening.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'I am not going to tell you what you did was right.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Good.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Stop saying good when I criticize you.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'It is encouraging.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'And I am not going to call you evil because other people needed you to be.', accent: 'secondary' },
    { kind: 'paragraph', text: 'Xu Kai’s smile faded.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Eighty-three people died because of a decision you made.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Tens of thousands may have lived because of the same decision.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Both are true.', accent: 'secondary' },
    { kind: 'paragraph', text: 'He looked at her.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You do not get to turn yourself into the villain just because that is easier to carry.', accent: 'secondary' },
    { kind: 'paragraph', text: 'The words landed somewhere none of her swords could reach.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You make supervision very invasive.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'State security.', accent: 'secondary' },
    { kind: 'paragraph', text: 'He laughed quietly.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Why did you change?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Change?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'The old records describe someone who entered rooms and immediately calculated everyone inside.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You still do that.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'But now you learn the cook’s name. You argue with shopkeepers. You remember which clerk hates coriander. You make terrible jokes in the middle of interrogations.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'My jokes are excellent.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Answer.', accent: 'secondary' },
    { kind: 'paragraph', text: 'Xu Kai looked over the wall toward the dark fields.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Back then I could look at twenty people and see leverage, probabilities, acceptable loss.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'It worked.', accent: 'primary' },
    { kind: 'paragraph', text: 'His expression was unreadable.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'That was what scared me.', accent: 'primary' },
    { kind: 'paragraph', text: 'Jian Yue said nothing.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'So I started making myself remember that the pieces complain about soup. They steal pears. They pack emergency sweet buns and insist they are not for anyone.', accent: 'primary' },
    { kind: 'paragraph', text: 'Jian Yue’s ears went red.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'People are much harder to sacrifice once they become annoying.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'That may be the worst sincere thing anyone has ever said to me.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I have range.', accent: 'primary' },
    { kind: 'paragraph', text: 'They walked in silence for a while.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Oi, Undertaker.', accent: 'secondary' },
    { kind: 'paragraph', text: 'Xu Kai stopped dead.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Absolutely not.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Black Minister?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Worse.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Enemy of Throne and Orthodoxy?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I am reconsidering honesty as a relationship principle.', accent: 'primary' },
    { kind: 'paragraph', text: 'She smiled.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Good.', accent: 'secondary' },
    { kind: 'paragraph', text: 'He stared at her.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You did that deliberately.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Training works.', accent: 'secondary' },
    { kind: 'paragraph', text: 'For the first time since entering Liangbei, Xu Kai laughed without anything hidden behind it.' },
  ],
};

const newChapters = [chapter81, chapter82, chapter83, chapter84, chapter85, chapter86, chapter87, chapter88];

export const seasons: Season[] = baseSeasons.map((season) => {
  if (season.number !== 1) {
    return season;
  }

  return {
    ...season,
    subtitle: 'A dangerous civilian acquires a National-Tier supervisor and accidentally becomes a national policy problem.',
    description: 'Xu Kai solves crises through observation, manipulation, economics, social engineering, and shameless conversation while Jian Yue learns that the frightening parts of his past were never as simple as the legends made them.',
    chapters: [...season.chapters, ...newChapters],
  };
});
