import type { Chapter, Season } from '../domain/types';
import { seasons as baseSeasons } from './story-v2';

const chapter8: Chapter = {
  id: 's01-c08',
  season: 1,
  number: 8,
  title: 'The Empty Places on the Map',
  summary: 'Six months of stolen National-Tier schedules look like a map of the Five. Xu Kai insists everyone is looking at the wrong thing.',
  readingMinutes: 9,
  tags: ['xu-kai', 'jian-yue', 'lu-chen', 'five-pillars', 'mystery'],
  segments: [
    { kind: 'paragraph', text: 'Lu Chen spread six months of stolen schedules across a table large enough to host a minor war.' },
    { kind: 'paragraph', text: 'Xu Kai put his tea on the only empty corner.' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Do not stain state intelligence records.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Then stop making them look like placemats.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Can you be serious for one conversation?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I was serious during lunch. It was exhausting.', accent: 'primary' },
    { kind: 'paragraph', text: 'Official Peng had been removed in chains an hour earlier. What remained in his dispatch box was worse than a confession.' },
    { kind: 'paragraph', text: 'Every journey taken by the Five Pillars had been copied: inspections, military deployments, private sect visits, imperial summons, even two funerals.' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Someone has been tracking us for half a year.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Not well enough to attack any of us.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Why would they attack you?', accent: 'primary' },
    { kind: 'paragraph', text: 'Both National Tiers looked at him.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'That is a very expensive way to die.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Then why collect the schedules?', accent: 'neutral' },
    { kind: 'paragraph', text: 'Xu Kai leaned over the table.' },
    { kind: 'paragraph', text: 'He moved Jian Yue\'s northern inspection beside Lu Chen\'s western operation, then placed two other dates beside them.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You keep looking at where the Five were.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'That is what the records show.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Exactly. So look at where you were not.', accent: 'primary' },
    { kind: 'paragraph', text: 'Silence.' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'The capital.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Sometimes.', accent: 'primary' },
    { kind: 'paragraph', text: 'He tapped four dates.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'On these days at least three Pillars were away from the southern quarter. What happened there?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Nothing significant.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'That answer should bother you.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Why?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Because people do not spend six months stealing National-Tier schedules to admire your handwriting.', accent: 'primary' },
    { kind: 'paragraph', text: 'Lu Chen called for incident ledgers.' },
    { kind: 'paragraph', text: 'The first date had a warehouse fire.' },
    { kind: 'paragraph', text: 'The second had a false report of plague.' },
    { kind: 'paragraph', text: 'The third had three escaped prisoners who surrendered before sunset.' },
    { kind: 'paragraph', text: 'The fourth had a grain cart overturn at the South Relay Gate.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Minor disturbances.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Timed disturbances.', accent: 'primary' },
    { kind: 'paragraph', text: 'He asked for response logs next.' },
    { kind: 'paragraph', text: 'The warehouse fire had drawn city guards in nine minutes.' },
    { kind: 'paragraph', text: 'The plague report had closed two streets in fourteen.' },
    { kind: 'paragraph', text: 'The escaped prisoners had brought Lu Chen\'s field agents in eleven.' },
    { kind: 'paragraph', text: 'The overturned grain cart had blocked the relay gate for twenty-three.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'They are not mapping the Five.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'They are measuring the response.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'There he is.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Do not sound proud of me.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You learn quickly.', accent: 'primary' },
    { kind: 'paragraph', text: 'Jian Yue circled the table.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'They cause small incidents while certain Pillars are absent, then record how quickly the state reacts.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'And which offices react. Which gates close. Which commanders move troops. Which routes become empty.', accent: 'primary' },
    { kind: 'paragraph', text: 'Lu Chen\'s expression flattened.' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'A rehearsal.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Several rehearsals.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'For what?', accent: 'secondary' },
    { kind: 'paragraph', text: 'Xu Kai pulled the latest schedule from the pile.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Who is leaving tomorrow?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Pillar Three remains at the eastern frontier. Pillar Five visits Mount Qiu. I was scheduled for a southern inspection.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'And Oi?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Stop calling me that in official meetings.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'So you are staying.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Because I am supervising you.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Naturally.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You too?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'I said one word.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'It was the way you said it.', accent: 'secondary' },
    { kind: 'paragraph', text: 'Xu Kai looked very pleased with the existence of language.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'And you. Stop smiling.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I am a civilian. You cannot regulate my face.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'I could draft something.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'This country truly fears freedom.', accent: 'primary' },
    { kind: 'break', label: 'An hour later' },
    { kind: 'paragraph', text: 'A clerk brought in tomorrow\'s guard rotations.' },
    { kind: 'paragraph', text: 'Xu Kai compared them to the stolen schedules and frowned for the first time that afternoon.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'What?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Nothing has been cancelled.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'I was about to cancel my inspection.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Do not.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You want him to leave the capital knowing someone is timing our responses?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I want them to believe tomorrow is still useful.', accent: 'primary' },
    { kind: 'paragraph', text: 'Lu Chen studied him.' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'You want the next test to happen.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I want to know who checks the clock.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'And if people get hurt?', accent: 'secondary' },
    { kind: 'paragraph', text: 'Xu Kai met her eyes.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Then we make sure they do not.', accent: 'primary' },
    { kind: 'paragraph', text: 'Jian Yue held his gaze for a moment, then nodded once.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Fine.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'That was suspiciously easy.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Do not ruin it.', accent: 'secondary' },
    { kind: 'paragraph', text: 'Lu Chen quietly marked three false absences into the official schedule.' },
    { kind: 'paragraph', text: 'By sunset, all three had leaked.' },
  ],
};

const chapter9: Chapter = {
  id: 's01-c09',
  season: 1,
  number: 9,
  title: 'Please Continue the National Emergency',
  summary: 'Xu Kai and Jian Yue go undercover in the capital market. Jian Yue objects to the disguise, the cover story, and several accurate observations by strangers.',
  readingMinutes: 9,
  tags: ['undercover', 'market', 'romance', 'wit', 'investigation'],
  segments: [
    { kind: 'paragraph', text: 'Jian Yue had faced armies with less hostility than she faced the blue dress.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'No.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You have not even seen the hat.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'There is a hat?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Now there is.', accent: 'primary' },
    { kind: 'paragraph', text: 'He placed a plain straw hat on the table.' },
    { kind: 'paragraph', text: 'Jian Yue looked at it as though considering whether National-Tier strength could kill an object without touching it.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Why am I wearing this?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Because Lady Jian Yue is famous.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'I know.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'That sounded very healthy.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'And you?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I am wearing brown.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You always wear brown.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Exactly. Perfect disguise.', accent: 'primary' },
    { kind: 'paragraph', text: 'Ten minutes later, National Tier #2 entered the South Market dressed like a prosperous merchant\'s daughter who had lost an argument with a hat.' },
    { kind: 'paragraph', text: 'Xu Kai walked beside her carrying a basket.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Why do you have a basket?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Undercover people buy vegetables.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Spies do not require cabbage.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'That attitude caused Qingshi.', accent: 'primary' },
    { kind: 'paragraph', text: 'Their first stop was a flower stall.' },
    { kind: 'dialogue', speaker: 'Flower Seller', text: 'For your wife?', accent: 'neutral' },
    { kind: 'paragraph', text: 'Jian Yue stopped.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Depends on the price.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'What depends on the price?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'The flowers.', accent: 'primary' },
    { kind: 'paragraph', text: 'The flower seller suddenly found the stems fascinating.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Good answer.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'There was danger in the air.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'There still is.', accent: 'secondary' },
    { kind: 'paragraph', text: 'Xu Kai bought chrysanthemums.' },
    { kind: 'paragraph', text: 'Then he told the flower seller that Lu Chen had left the capital by the eastern gate.' },
    { kind: 'paragraph', text: 'At a tea stall, he said Lu Chen had gone north.' },
    { kind: 'paragraph', text: 'At a spice shop, he complained that Lu Chen had gone west and taken half the intelligence bureau with him.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You are spreading three different lies.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Four. I told the dumpling woman he resigned.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Why?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'She looked bored.', accent: 'primary' },
    { kind: 'paragraph', text: 'They bought tea and waited.' },
    { kind: 'paragraph', text: 'Jian Yue lasted seven minutes.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'What exactly are we watching?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'People who do not care about Lu Chen.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'That is most of the market.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Correct. Which makes the one person who cares very obvious.', accent: 'primary' },
    { kind: 'paragraph', text: 'A stable boy crossed the street at a run.' },
    { kind: 'paragraph', text: 'He did not look at the flower stall, the tea stall, or the spice shop.' },
    { kind: 'paragraph', text: 'He went directly to a courier yard and rented the fastest horse available.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Which rumor did he hear?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'The flowers.', accent: 'primary' },
    { kind: 'paragraph', text: 'Jian Yue glanced at the chrysanthemums.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You bought flowers to identify a spy.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'No. I bought flowers because they were cheap. The spy was a pleasant bonus.', accent: 'primary' },
    { kind: 'paragraph', text: 'They followed the boy at a distance.' },
    { kind: 'paragraph', text: 'He delivered a message to Blue Lantern Accounting House, an ordinary building with clean windows and no sign that anyone inside had ever enjoyed themselves.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Accountants.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You sound disappointed.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I hoped for smugglers.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Why?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Better stories.', accent: 'primary' },
    { kind: 'break', label: 'Across the street' },
    { kind: 'paragraph', text: 'They rented the upper room of a pastry shop.' },
    { kind: 'paragraph', text: 'Jian Yue watched the accounting house through a narrow window while Xu Kai ate the surveillance equipment.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Those are pastries.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'We needed a reason to rent the room.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'We did not need twelve.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Operational redundancy.', accent: 'primary' },
    { kind: 'paragraph', text: 'A courier left Blue Lantern ten minutes later.' },
    { kind: 'paragraph', text: 'Then another.' },
    { kind: 'paragraph', text: 'The third carried no visible message and walked toward the East Registry.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'I will follow him.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'No.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'No?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Lady Jian Yue following a clerk through the capital is not subtle.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'I am disguised.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You are wearing a hat. You still walk like buildings should apologize for being in your way.', accent: 'primary' },
    { kind: 'paragraph', text: 'She opened her mouth.' },
    { kind: 'paragraph', text: 'Closed it.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'That is not a real thing.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'The pastry owner moved a table when you entered.', accent: 'primary' },
    { kind: 'paragraph', text: 'Jian Yue looked at the moved table.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'I dislike you.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Officially?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Deeply.', accent: 'secondary' },
    { kind: 'paragraph', text: 'A small folded paper slid beneath the pastry shop door.' },
    { kind: 'paragraph', text: 'Xu Kai picked it up.' },
    { kind: 'paragraph', text: 'There were eight words.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'If Sword Saint remains, move test to East Registry.', accent: 'primary' },
    { kind: 'paragraph', text: 'Jian Yue\'s expression changed.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'They know I stayed.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Worse.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'What is worse?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'They adjusted in less than an hour.', accent: 'primary' },
    { kind: 'paragraph', text: 'He looked toward the East Registry bell tower.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Someone is watching the watchers.', accent: 'primary' },
  ],
};

const chapter10: Chapter = {
  id: 's01-c10',
  season: 1,
  number: 10,
  title: 'The Strongest Man in the Country Has No Patience',
  summary: 'National Tier #1 Han Zhen arrives to take control of the investigation. Xu Kai immediately makes this more difficult than necessary.',
  readingMinutes: 10,
  tags: ['han-zhen', 'national-tier-1', 'xu-kai', 'jian-yue', 'politics'],
  segments: [
    { kind: 'paragraph', text: 'Grand Marshal Han Zhen entered the East Registry with forty soldiers.' },
    { kind: 'paragraph', text: 'Xu Kai counted them.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Decorative?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'What?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'The soldiers. There are forty of them for one civilian.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'They are not for you.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'That is disappointing. I felt important.', accent: 'primary' },
    { kind: 'paragraph', text: 'Han Zhen was National Tier #1, supreme commander of the central armies, and the strongest martial artist the country officially recognized.' },
    { kind: 'paragraph', text: 'He looked like a man who had been informed humor was strategically unnecessary.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You came quickly.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'Lu Chen said a civilian was altering Pillar movements.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Three fake schedules.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'You altered Pillar movements.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Fine. But only fictional Pillars.', accent: 'primary' },
    { kind: 'paragraph', text: 'Han Zhen looked at Jian Yue.' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'This is what you have been supervising?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Unfortunately.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'She is very dedicated.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Do not.', accent: 'secondary' },
    { kind: 'paragraph', text: 'Lu Chen arrived with the message from Blue Lantern.' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'They redirected to the East Registry once they realized Jian Yue remained in the capital.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'Then we close the registry, arrest every employee, and seize Blue Lantern.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'No.', accent: 'primary' },
    { kind: 'paragraph', text: 'Forty soldiers became extremely interested in being somewhere else.' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'Civilian.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Grand Marshal.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'I did not ask for your approval.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Good. I was not offering it.', accent: 'primary' },
    { kind: 'paragraph', text: 'Jian Yue pinched the bridge of her nose.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Xu Kai.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Oi.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Not now.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You started it.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'He calls you Oi?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'This is not relevant to national security.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'According to her, I am national security.', accent: 'primary' },
    { kind: 'paragraph', text: 'Han Zhen stared at both of them for a long moment.' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'I have returned from the northern front to this.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'I warned you.', accent: 'neutral' },
    { kind: 'break', label: 'The war room' },
    { kind: 'paragraph', text: 'Han Zhen put a frontier map in front of Xu Kai.' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'Three forts fall in one night. The enemy has forty thousand men. You have twelve thousand and one National Tier. What do you defend?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Whose forts?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'Ours.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Then the question is bad.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'Explain.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'If the enemy takes three forts in one night, the forts were never the objective.', accent: 'primary' },
    { kind: 'paragraph', text: 'Han Zhen said nothing.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Fortifications slow armies. Taking three quickly means someone spent enormous effort making me look at them.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'What do you look at instead?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Food.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Of course.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You say that like food has betrayed you.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'Continue.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Forty thousand men need grain. Your map has one river and two roads capable of feeding them. I do not defend the forts. I make the roads expensive, the river unreliable, and the commanders argue over which one failed.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'And the captured forts?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'They can keep them while hungry.', accent: 'primary' },
    { kind: 'paragraph', text: 'Han Zhen moved a marker.' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'The enemy burns the villages and takes grain by force.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Then they stop being an invading army and become forty thousand armed men hated by every farmer behind them.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'You are comfortable gambling with territory.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Land does not panic. People do.', accent: 'primary' },
    { kind: 'paragraph', text: 'The room went quiet.' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'You speak as though war is a market.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Everything becomes a market once people want different things badly enough.', accent: 'primary' },
    { kind: 'paragraph', text: 'Han Zhen folded the map.' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'I still do not trust you.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Healthy.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'I also do not intend to arrest you today.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Less healthy, but convenient.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You were not being arrested.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'I considered it.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'See? Communication.', accent: 'primary' },
    { kind: 'paragraph', text: 'Han Zhen turned to Lu Chen.' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'Keep Blue Lantern open. Watch everyone who enters.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'That was his recommendation.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'I know.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You can say it was mine. I will survive.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'That remains to be seen.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Jian Yue immediately looked at Han Zhen.' },
    { kind: 'paragraph', text: 'Han Zhen looked back.' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'A figure of speech.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Good.', accent: 'secondary' },
    { kind: 'paragraph', text: 'Xu Kai looked between them.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'This supervision is becoming emotionally complicated.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Be quiet.', accent: 'secondary' },
  ],
};

const chapter11: Chapter = {
  id: 's01-c11',
  season: 1,
  number: 11,
  title: 'Five Chairs, Four Pillars, One Problem',
  summary: 'Four of the Five Pillars meet to decide what to do about Xu Kai. Xu Kai is invited, which everyone soon regrets.',
  readingMinutes: 10,
  tags: ['five-pillars', 'han-zhen', 'bai-ren', 'lu-chen', 'politics'],
  segments: [
    { kind: 'paragraph', text: 'The Hall of Five had five chairs.' },
    { kind: 'paragraph', text: 'Xu Kai counted them twice.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Awkward.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Do not sit in one.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I was not going to.', accent: 'primary' },
    { kind: 'paragraph', text: 'He looked at the empty chair belonging to Pillar #3, still deployed at the eastern frontier.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'It looks lonely.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Xu Kai.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Fine.', accent: 'primary' },
    { kind: 'paragraph', text: 'He sat on the windowsill instead.' },
    { kind: 'paragraph', text: 'Han Zhen occupied the first chair.' },
    { kind: 'paragraph', text: 'Jian Yue took the second.' },
    { kind: 'paragraph', text: 'The third remained empty.' },
    { kind: 'paragraph', text: 'Lu Chen sat in the fourth.' },
    { kind: 'paragraph', text: 'The fifth chair belonged to Bai Ren, an elderly man in plain robes who arrived carrying a paper bag of roasted chestnuts.' },
    { kind: 'dialogue', speaker: 'Bai Ren', text: 'Which one is the dangerous civilian?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Depends who is asking.', accent: 'primary' },
    { kind: 'paragraph', text: 'Bai Ren smiled.' },
    { kind: 'dialogue', speaker: 'Bai Ren', text: 'I like him.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'You have known him four seconds.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Bai Ren', text: 'You disliked him in fewer.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I like him too.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'That makes one person in this room.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You traveled two provinces to fetch me.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Official assignment.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Bai Ren', text: 'Ah.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Do not ah.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Bai Ren', text: 'I said one syllable.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'It was an unnecessary syllable.', accent: 'secondary' },
    { kind: 'paragraph', text: 'Lu Chen put the Blue Lantern records on the central table.' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'The network is larger than one accounting house. Eight provincial offices, three courier firms, two grain exchanges, and at least one Ministry clerk have passed schedule information.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'Purpose?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Unknown.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Not unknown.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'You have had the records for one hour.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'A long hour.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Speak.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Xu Kai held up three expense sheets.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'They spend money like bureaucrats.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Bai Ren', text: 'Tragic.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Exactly. No hidden army. No weapons stockpile. No unusual poison purchases. No mercenary retainers.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'Then what are they buying?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Clerks. Couriers. Paper. Access to bell towers. Gate toll records. Response logs.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Information.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Proof.', accent: 'primary' },
    { kind: 'paragraph', text: 'Han Zhen frowned.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Someone wants to prove the country cannot function when the Five are elsewhere.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Bai Ren', text: 'A political argument.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Made with illegal surveillance of National Tiers.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'People become creative when legal petitions are ignored.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'Are you defending them?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Understanding is not approval.', accent: 'primary' },
    { kind: 'paragraph', text: 'That answer made the room quieter than his jokes ever did.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'What do they want to demonstrate?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'That the Five make everyone lazy.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'Careful.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'See? Excellent example.', accent: 'primary' },
    { kind: 'paragraph', text: 'Bai Ren covered a laugh with a chestnut.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Every province knows that if a disaster becomes large enough, one of you appears and ends it. So governors underfund local response. Commanders wait for central orders. Officials learn to survive until a Pillar arrives.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'And Blue Lantern wants a failure large enough to expose that dependence.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'But small enough not to become treason.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'That line is thinner than they think.', accent: 'secondary' },
    { kind: 'paragraph', text: 'A clerk rushed into the hall carrying a sheet of fresh print.' },
    { kind: 'paragraph', text: 'Han Zhen read it once and handed it to Lu Chen.' },
    { kind: 'paragraph', text: 'Lu Chen read it twice and handed it to Jian Yue.' },
    { kind: 'paragraph', text: 'Jian Yue read it and slowly looked at Xu Kai.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'That expression suggests I have done something impressive without remembering it.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Apparently you ordered the arrest of six provincial governors.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Busy morning.', accent: 'primary' },
    { kind: 'paragraph', text: 'She handed him the proclamation.' },
    { kind: 'paragraph', text: 'It carried an official seal, three forged signatures, and Xu Kai\'s name in characters twice as large as anyone else\'s.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'My handwriting is better.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'This is not funny.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'It is a little funny.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Xu Kai.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Fine. Mostly treason.', accent: 'primary' },
    { kind: 'paragraph', text: 'Outside the hall, bells began ringing across the capital.' },
    { kind: 'paragraph', text: 'By noon, half the city believed the dangerous civilian had seized control of the government.' },
  ],
};

const chapter12: Chapter = {
  id: 's01-c12',
  season: 1,
  number: 12,
  title: 'How to Lose a Reputation You Never Wanted',
  summary: 'Someone turns Xu Kai\'s reputation into a weapon. His solution is to make the rumors much, much worse.',
  readingMinutes: 10,
  tags: ['propaganda', 'wit', 'jian-yue', 'blue-lantern', 'capital'],
  segments: [
    { kind: 'paragraph', text: 'By afternoon Xu Kai had allegedly arrested six governors, dismissed two ministers, raised the tea tax, abolished the tea tax, and declared himself Acting Deputy Something.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I dislike Acting Deputy Something.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'That is the part bothering you?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Titles should have rhythm.', accent: 'primary' },
    { kind: 'paragraph', text: 'They stood in a Ministry courtyard while messengers arrived from every gate carrying copies of forged proclamations.' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'We issue an immediate denial.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'No.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'You have developed an unhealthy relationship with that word.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Denials are boring and arrive after the interesting lie.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Your alternative?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Make it ridiculous.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'It is already ridiculous.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Not enough.', accent: 'primary' },
    { kind: 'break', label: 'One hour later' },
    { kind: 'paragraph', text: 'A new proclamation appeared at the West Market.' },
    { kind: 'paragraph', text: 'It announced that Xu Kai had assumed personal control of the weather.' },
    { kind: 'paragraph', text: 'Another claimed he had appointed Jian Yue Minister of Personal Violence.' },
    { kind: 'paragraph', text: 'A third stated that all ducks in the capital were now subject to strategic registration.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Minister of Personal Violence?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'It tested well.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'With whom?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'The printer.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'I will test violence on the printer.', accent: 'secondary' },
    { kind: 'paragraph', text: 'By sunset the capital had stopped believing any proclamation bearing Xu Kai\'s name.' },
    { kind: 'paragraph', text: 'More importantly, the original forgers panicked.' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'They printed a correction.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Of course they did.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'Why is that useful?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Because liars hate losing ownership of their lie.', accent: 'primary' },
    { kind: 'paragraph', text: 'The correction used heavier paper, darker ink, and one peculiar character for governor that no official press in the capital used.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'There.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'The character?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Western copyist form. Old-fashioned. Only three commercial presses in the city still use it.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'You know printing styles?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I once owed a printer money.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Why?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Unrelated national emergency.', accent: 'primary' },
    { kind: 'paragraph', text: 'Two presses were innocent.' },
    { kind: 'paragraph', text: 'The third had printed four hundred copies overnight for a nervous man named Cheng Rui.' },
    { kind: 'break', label: 'The print shop' },
    { kind: 'paragraph', text: 'Cheng Rui was not a spy.' },
    { kind: 'paragraph', text: 'He was a debt clerk with ink on his sleeves and the expression of a man who had regretted every decision since breakfast.' },
    { kind: 'dialogue', speaker: 'Cheng Rui', text: 'They said the orders were authorized.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'By whom?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Cheng Rui', text: 'Blue Lantern. They said the Ministry wanted public reaction measured.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'You printed forged arrest orders because an accounting house asked nicely?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Cheng Rui', text: 'They paid my father\'s medical debt.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Lu Chen stopped.' },
    { kind: 'paragraph', text: 'Xu Kai did not.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'How much?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Cheng Rui', text: 'Eighty-three silver.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Too much for a printer. Too little for treason.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Meaning?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Meaning they were buying compliance, not loyalty.', accent: 'primary' },
    { kind: 'paragraph', text: 'Cheng Rui told them about provincial clerks, relay officers, accountants, and minor officials recruited the same way.' },
    { kind: 'paragraph', text: 'Medical debts. School fees. Failed harvests. Families trapped by court fines.' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'A grievance network.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'A very organized complaint.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'They endangered civilians to make a political point.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Cheng Rui', text: 'No.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Everyone looked at him.' },
    { kind: 'dialogue', speaker: 'Cheng Rui', text: 'They were obsessed with avoiding casualties. Every test had limits. Empty warehouses. False plague reports after curfew. Prisoners who agreed to surrender.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'The inn assassins?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Cheng Rui', text: 'I do not know anything about assassins.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Xu Kai and Jian Yue looked at each other.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'There are two games.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Blue Lantern and someone using them.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'See? Supervision is educational.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'I learned that before you spoke.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Proud of you.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Do not be.', accent: 'secondary' },
    { kind: 'paragraph', text: 'Cheng Rui swallowed.' },
    { kind: 'dialogue', speaker: 'Cheng Rui', text: 'There is one more thing.', accent: 'neutral' },
    { kind: 'paragraph', text: 'He produced a delivery slip.' },
    { kind: 'paragraph', text: 'Blue Lantern had ordered signal oil and harmless smoke powder for a demonstration at White Bridge Relay.' },
    { kind: 'paragraph', text: 'Someone had changed the order after it left their office.' },
    { kind: 'paragraph', text: 'The final delivery contained blasting powder.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'How much?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Cheng Rui', text: 'Enough to drop the bridge.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Xu Kai stopped joking.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'When?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Cheng Rui', text: 'Tomorrow.', accent: 'neutral' },
  ],
};

const chapter13: Chapter = {
  id: 's01-c13',
  season: 1,
  number: 13,
  title: 'Oi Is Not a Military Rank',
  summary: 'White Bridge becomes the stage for someone else\'s revolution. Xu Kai has one night to stop a demonstration from becoming a massacre.',
  readingMinutes: 11,
  tags: ['white-bridge', 'five-pillars', 'climax', 'wit', 'jian-yue'],
  segments: [
    { kind: 'paragraph', text: 'White Bridge carried three things the capital could not easily replace: military dispatches, grain traffic, and twelve thousand commuters every morning.' },
    { kind: 'paragraph', text: 'Blue Lantern intended to stop the first for twenty minutes.' },
    { kind: 'paragraph', text: 'Someone else intended to stop all three permanently.' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'We evacuate the bridge and arrest every Blue Lantern member tonight.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Then the person who replaced the smoke powder disappears.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'And if we wait, people may die.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'So we do not wait.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'You just objected to acting tonight.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I objected to acting loudly.', accent: 'primary' },
    { kind: 'paragraph', text: 'He pointed at the bridge plan.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Blue Lantern expects three response teams. Give them three response teams.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'And the explosives?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Replace them.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'We do not know every cache.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Blue Lantern does.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'They will not cooperate after we arrested their people.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'We do not need cooperation. We need panic.', accent: 'primary' },
    { kind: 'paragraph', text: 'An hour later, Lu Chen quietly released a rumor that Han Zhen planned mass arrests of Blue Lantern families at dawn.' },
    { kind: 'paragraph', text: 'Blue Lantern reacted exactly as frightened bureaucrats usually did.' },
    { kind: 'paragraph', text: 'They sent frantic couriers to every safe site.' },
    { kind: 'paragraph', text: 'Lu Chen followed all of them.' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'I dislike admitting this worked.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Growth is painful.', accent: 'primary' },
    { kind: 'break', label: 'Before dawn' },
    { kind: 'paragraph', text: 'The real blasting powder was removed from five caches beneath White Bridge.' },
    { kind: 'paragraph', text: 'A sixth cache was not on Blue Lantern\'s list.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'There.', accent: 'secondary' },
    { kind: 'paragraph', text: 'She pointed to a maintenance arch below the eastern span.' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'How did you find it?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'The mortar is newer.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'See? Useful eyes.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'I am National Tier #2.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Very useful eyes.', accent: 'primary' },
    { kind: 'paragraph', text: 'Jian Yue looked offended by the compliment and pleased by it in equal measure.' },
    { kind: 'paragraph', text: 'Lu Chen removed the sixth cache.' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'Now we arrest them.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Now we let them perform.', accent: 'primary' },
    { kind: 'paragraph', text: 'Han Zhen stared.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'If the demonstration fails quietly, the person who upgraded it learns nothing. If it appears to succeed, they reveal what they expected next.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You want to fake the bridge failure.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'For eight minutes.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'You enjoy unnecessary complexity.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Necessary complexity is just work.', accent: 'primary' },
    { kind: 'break', label: 'Morning' },
    { kind: 'paragraph', text: 'At the seventh bell, harmless smoke swallowed White Bridge.' },
    { kind: 'paragraph', text: 'The relay tower stopped sending signals.' },
    { kind: 'paragraph', text: 'A grain convoy halted at the western approach.' },
    { kind: 'paragraph', text: 'Three city units moved exactly as Blue Lantern\'s stolen response charts predicted.' },
    { kind: 'paragraph', text: 'From a rented room overlooking the river, Xu Kai watched six signal flags rise across the district.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'There.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Which one?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'The green flag on the dye warehouse.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Why?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Blue Lantern signals completion in white. Green means proceed to phase two.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'How do you know?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Because the man holding it is wearing expensive boots in a dye warehouse.', accent: 'primary' },
    { kind: 'paragraph', text: 'Han Zhen looked at Lu Chen.' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Do not ask. I have stopped asking.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Jian Yue stood beside the door, ready to move.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Oi.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'What?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Go to the east approach.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'No.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Interesting. That is usually my word.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You are staying here with two agents.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'The east approach has a thousand civilians.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Han Zhen can cover it.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'I am covering the relay tower.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Then Lu Chen.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'I am following the green flag.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Jian Yue looked betrayed by logistics.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'If you want to protect me, protect the plan.', accent: 'primary' },
    { kind: 'paragraph', text: 'Her eyes narrowed.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'And the thousand people.', accent: 'primary' },
    { kind: 'paragraph', text: 'Jian Yue held still for one more second.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Do not leave this room.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I am insulted by how often you say that.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Promise.', accent: 'secondary' },
    { kind: 'paragraph', text: 'The word came out quieter than the rest.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Fine. Promise.', accent: 'primary' },
    { kind: 'paragraph', text: 'She left.' },
    { kind: 'break', label: 'Eight minutes later' },
    { kind: 'paragraph', text: 'The green flag led Lu Chen to a courier who carried three sealed orders.' },
    { kind: 'paragraph', text: 'One ordered armed men to attack the panicked crowd at White Bridge.' },
    { kind: 'paragraph', text: 'One ordered a fire at the western granary.' },
    { kind: 'paragraph', text: 'The third ordered Blue Lantern members killed after the demonstration.' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Someone planned to turn their political stunt into an uprising.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'And blame the bodies on them.', accent: 'primary' },
    { kind: 'paragraph', text: 'Han Zhen\'s soldiers intercepted the granary team.' },
    { kind: 'paragraph', text: 'Jian Yue reached the east approach before the armed men emerged from the alleys.' },
    { kind: 'paragraph', text: 'The fight lasted less time than the crowd needed to understand there had been one.' },
    { kind: 'paragraph', text: 'At the dye warehouse, Lu Chen arrested a senior court aide named Minister Cao.' },
    { kind: 'paragraph', text: 'Cao had publicly argued for stronger central authority for twelve years.' },
    { kind: 'paragraph', text: 'He had privately decided the easiest way to strengthen it was to make provincial reformers look like terrorists.' },
    { kind: 'dialogue', speaker: 'Minister Cao', text: 'The provinces were undermining the state.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'So you tried to murder citizens to win an argument about public safety.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Minister Cao', text: 'You are a civilian. You do not understand governance.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Apparently governance is more explosive than I expected.', accent: 'primary' },
    { kind: 'paragraph', text: 'Han Zhen ordered Cao taken away.' },
    { kind: 'break', label: 'Afterward' },
    { kind: 'paragraph', text: 'Jian Yue returned with dust on her sleeve and no visible injury.' },
    { kind: 'paragraph', text: 'She walked directly past Han Zhen and Lu Chen.' },
    { kind: 'paragraph', text: 'She stopped in front of Xu Kai.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You stayed.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I promised.', accent: 'primary' },
    { kind: 'paragraph', text: 'Her shoulders relaxed by an amount no one else would have noticed.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Oi.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'What?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You came back.', accent: 'primary' },
    { kind: 'paragraph', text: 'For once, Jian Yue had no immediate answer.' },
    { kind: 'dialogue', speaker: 'Bai Ren', text: 'Oi.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Jian Yue\'s sword was at Bai Ren\'s throat before the old man finished smiling.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'No.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Bai Ren', text: 'Understood.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Xu Kai looked delighted.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Do not say anything.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Would not dream of it.', accent: 'primary' },
    { kind: 'paragraph', text: 'He was still smiling ten minutes later.' },
  ],
};

const chapter14: Chapter = {
  id: 's01-c14',
  season: 1,
  number: 14,
  title: 'The Residence Next Door',
  summary: 'After saving the capital from a manufactured crisis, Xu Kai receives the greatest punishment the state can imagine: official housing beside Jian Yue.',
  readingMinutes: 9,
  tags: ['slice-of-life', 'romance', 'jian-yue', 'capital', 'next-arc'],
  segments: [
    { kind: 'paragraph', text: 'The state rewarded Xu Kai with a house because nobody could agree what else to do with him.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'It has three rooms.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Yes.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I only have one body.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'The Ministry is aware.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Good. For a moment I worried this was another intelligence test.', accent: 'primary' },
    { kind: 'paragraph', text: 'The residence stood inside a secure government quarter, near enough to the Ministry for agents to watch it and far enough from the palace that nobody important had to admit they were watching it.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Who lives next door?', accent: 'primary' },
    { kind: 'paragraph', text: 'Lu Chen looked away.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'That is never reassuring.', accent: 'primary' },
    { kind: 'paragraph', text: 'The neighboring door opened.' },
    { kind: 'paragraph', text: 'Jian Yue stepped out carrying a box.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Oi.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'No.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You live here?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Temporarily.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'How temporary?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Until you stop being a security concern.', accent: 'secondary' },
    { kind: 'paragraph', text: 'Xu Kai looked at Lu Chen.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'So permanent.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'That was my assessment.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Both of you are irritating.', accent: 'secondary' },
    { kind: 'break', label: 'Furniture' },
    { kind: 'paragraph', text: 'Xu Kai spent the afternoon refusing state furniture.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'It is free.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'So are many diseases.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'It is a table.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'It has the personality of a tax office.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Tables do not have personalities.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'That one does. It disapproves of me.', accent: 'primary' },
    { kind: 'paragraph', text: 'They went to the market.' },
    { kind: 'paragraph', text: 'Jian Yue told herself she accompanied him because an unsupervised Xu Kai shopping for furniture could become a fiscal incident.' },
    { kind: 'paragraph', text: 'This explanation remained useful until the bedding stall.' },
    { kind: 'dialogue', speaker: 'Shopkeeper', text: 'For the newlyweds?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'No.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'She is very shy.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'I will bury you in the bedding.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Shopkeeper', text: 'Ah. Very newly married.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Xu Kai bought the blanket mostly because Jian Yue was too angry to negotiate.' },
    { kind: 'break', label: 'Dinner' },
    { kind: 'paragraph', text: 'Jian Yue cooked noodles.' },
    { kind: 'paragraph', text: 'Xu Kai looked into the bowl.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'What did they do to you?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'They are noodles.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Legally?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Eat.', accent: 'secondary' },
    { kind: 'paragraph', text: 'He ate one bite.' },
    { kind: 'paragraph', text: 'Jian Yue watched him with more concentration than she had given the White Bridge operation.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Interesting.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'What does that mean?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'It means National Tier strength cannot defeat salt.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'There is not too much salt.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'There is enough salt to preserve the table.', accent: 'primary' },
    { kind: 'paragraph', text: 'She reached for his bowl.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Then do not eat it.', accent: 'secondary' },
    { kind: 'paragraph', text: 'Xu Kai moved the bowl away.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I did not say I would stop.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Why would you keep eating something you dislike?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You made it.', accent: 'primary' },
    { kind: 'paragraph', text: 'Jian Yue froze.' },
    { kind: 'paragraph', text: 'Xu Kai took another bite.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Still terrible.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Idiot.', accent: 'secondary' },
    { kind: 'paragraph', text: 'She turned away before he could see how red her ears had become.' },
    { kind: 'break', label: 'Later' },
    { kind: 'paragraph', text: 'A sealed military message arrived just before midnight.' },
    { kind: 'paragraph', text: 'Jian Yue opened it.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'No.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'That is becoming my favorite answer from you.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Pillar Three is returning from the eastern frontier.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Good for Pillar Three.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'He wants to meet you.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Less good for Pillar Three.', accent: 'primary' },
    { kind: 'paragraph', text: 'She handed him the message.' },
    { kind: 'paragraph', text: 'The final line had been written personally.' },
    { kind: 'paragraph', text: 'Bring me the civilian who made the Five dance.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You are not going alone.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Oi.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'What?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'That sounded like concern.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'It is supervision.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Naturally.', accent: 'primary' },
    { kind: 'paragraph', text: 'From the other side of the wall, Lu Chen sneezed.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'He does not live there.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'That is more concerning.', accent: 'primary' },
  ],
};

const newChapters = [chapter8, chapter9, chapter10, chapter11, chapter12, chapter13, chapter14];

export const seasons: Season[] = baseSeasons.map((season) => {
  if (season.number !== 1) {
    return season;
  }

  return {
    ...season,
    subtitle: 'A dangerous civilian acquires a National-Tier supervisor and accidentally becomes a national policy problem.',
    description: 'Xu Kai solves crises through observation, manipulation, economics, social engineering, and shameless conversation while Jian Yue, National Tier #2, insists that following him everywhere is merely responsible supervision.',
    chapters: [...season.chapters, ...newChapters],
  };
});
