import type { Chapter, Season } from '../domain/types';
import { seasons as baseSeasons } from './story-v12';

const chapter73: Chapter = {
  id: 's01-c73',
  season: 1,
  number: 73,
  title: 'The Map We Did Not Have',
  summary: 'Xu Kai cannot find the second doctrine archive, so he does the next best thing: convinces Jiang Tai that he already has.',
  readingMinutes: 10,
  tags: ['black-rain', 'deception', 'jiang-tai', 'qin-fei', 'strategy'],
  segments: [
    { kind: 'paragraph', text: 'The first problem was that half a map was not a map.' },
    { kind: 'paragraph', text: 'The second problem was that Qin Fei had folded his half badly for seven years.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You murdered geography.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Qin Fei', text: 'I was busy pretending to be dead.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'The river line could be any of twelve tributaries in the Grey March.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Ning Sui', text: 'And Gu removed place names from doctrine maps.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'So we cannot locate the archive.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Correct.', accent: 'primary' },
    { kind: 'paragraph', text: 'He looked delighted.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Why are you smiling?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Because Jiang Tai does not know that.', accent: 'primary' },
    { kind: 'paragraph', text: 'Lu Chen closed his eyes.' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'What are you going to do?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Be irresponsible with confidence.', accent: 'primary' },
    { kind: 'break', label: 'By noon' },
    { kind: 'paragraph', text: 'Yunqiao acquired three rumors.' },
    { kind: 'paragraph', text: 'The first said Xu Kai had found a buried archive beneath Red Reed Monastery.' },
    { kind: 'paragraph', text: 'The second said the archive was under the abandoned northern flood station.' },
    { kind: 'paragraph', text: 'The third said there was no archive at all and Xu Kai had already burned it.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Why three?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Because one lie creates suspicion. Three lies create work.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'For whom?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Everyone.', accent: 'primary' },
    { kind: 'paragraph', text: 'Each rumor carried a different tiny detail.' },
    { kind: 'paragraph', text: 'Red Reed included a reference to blue roof tiles.' },
    { kind: 'paragraph', text: 'The flood station included a broken stone lion.' },
    { kind: 'paragraph', text: 'The burned-archive story mentioned a copper furnace.' },
    { kind: 'dialogue', speaker: 'Ning Sui', text: 'Markers.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Whichever detail returns tells us which rumor reached Jiang Tai.', accent: 'primary' },
    { kind: 'paragraph', text: 'It took four hours.' },
    { kind: 'paragraph', text: 'A fishmonger near the west gate complained that strangers had been asking about blue roof tiles.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Red Reed.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Our fisherman has selected a monastery.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Qin Fei', text: 'There is nothing at Red Reed.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Excellent. Less chance of damaging something useful.', accent: 'primary' },
    { kind: 'paragraph', text: 'Lu Chen unfolded a regional map.' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'If Jiang moves people there, we can identify his network.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Do not arrest them.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Why?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Because Jiang Tai is looking for us to behave like the state.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'And you want him to think we do not know.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I want him comfortable.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Qin Fei', text: 'You were always unpleasant when you sounded kind.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Thank you.', accent: 'primary' },
    { kind: 'paragraph', text: 'That night a folded menu arrived at their inn.' },
    { kind: 'paragraph', text: 'No one had ordered food.' },
    { kind: 'paragraph', text: 'On the back, in precise block characters, was a single sentence.' },
    { kind: 'paragraph', text: 'RED REED HAS TERRIBLE TILE WORK.' },
    { kind: 'dialogue', speaker: 'Ning Sui', text: 'Jiang.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'He knows the rumor is bait.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Then the plan failed.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'No.', accent: 'primary' },
    { kind: 'paragraph', text: 'He turned the menu over again.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'He answered.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Meaning?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Meaning he wants to play.', accent: 'primary' },
  ],
};

const chapter74: Chapter = {
  id: 's01-c74',
  season: 1,
  number: 74,
  title: 'Reserve Eight Orders Dinner',
  summary: 'Jiang Tai invites Xu Kai to dinner in a crowded restaurant, where killing anyone would be rude and telling the truth would be worse.',
  readingMinutes: 11,
  tags: ['jiang-tai', 'dinner', 'black-rain', 'psychological', 'jian-yue'],
  segments: [
    { kind: 'paragraph', text: 'Jiang Tai chose the busiest restaurant in Yunqiao.' },
    { kind: 'paragraph', text: 'Xu Kai approved immediately.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'No.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You have not heard the plan.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'The plan includes you meeting a former assassin who has killed his own colleagues.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Over dinner.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Still no.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'There will be dumplings.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'I hate your negotiating style.', accent: 'secondary' },
    { kind: 'paragraph', text: 'They went together.' },
    { kind: 'paragraph', text: 'Jiang Tai was already seated upstairs by an open window.' },
    { kind: 'paragraph', text: 'He looked ordinary.' },
    { kind: 'paragraph', text: 'This was immediately suspicious.' },
    { kind: 'dialogue', speaker: 'Jiang Tai', text: 'Kai.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Eight.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jiang Tai', text: 'You still call people by designations when you dislike them.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You still murder coworkers when networking fails.', accent: 'primary' },
    { kind: 'paragraph', text: 'Jian Yue sat beside Xu Kai.' },
    { kind: 'paragraph', text: 'Jiang Tai looked at her sword, then at Xu Kai.' },
    { kind: 'dialogue', speaker: 'Jiang Tai', text: 'So the Sword Saint is your shadow now.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Say that again.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Oi. We just sat down.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'He is irritating.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I know. I feel strangely competitive.', accent: 'primary' },
    { kind: 'paragraph', text: 'Jiang Tai poured tea.' },
    { kind: 'dialogue', speaker: 'Jiang Tai', text: 'You found Qin Fei.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Laundry found Qin Fei.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jiang Tai', text: 'Of course it did.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You sound disappointed.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jiang Tai', text: 'I spent three years searching for him.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Did you ask a washerwoman?', accent: 'primary' },
    { kind: 'paragraph', text: 'Jiang Tai actually laughed.' },
    { kind: 'dialogue', speaker: 'Jiang Tai', text: 'This is why Gu feared you.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Feared his mind?', accent: 'secondary' },
    { kind: 'paragraph', text: 'The question was innocent enough.' },
    { kind: 'paragraph', text: 'Xu Kai heard the trap inside it.' },
    { kind: 'dialogue', speaker: 'Jiang Tai', text: 'Among other things.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Jian Yue took a dumpling.' },
    { kind: 'paragraph', text: 'She did not react.' },
    { kind: 'paragraph', text: 'She was getting better at lying.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Why the doctrine archive?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jiang Tai', text: 'Because Gu made one mistake.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Only one?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jiang Tai', text: 'He built Black Rain with a conscience.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'An assassination network.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Jiang Tai', text: 'A contingency network. Targets required three independent confirmations. Civilian proximity cancelled action. Local commanders could delay. Couriers could reject corrupted codes.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Safeguards.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jiang Tai', text: 'Weaknesses.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Xu Kai stopped smiling.' },
    { kind: 'dialogue', speaker: 'Jiang Tai', text: 'You proved it. You exploited every hesitation Gu allowed.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'People refusing to murder strangers without certainty is not a defect.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jiang Tai', text: 'It is if the state actually falls.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'The state did not fall.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Jiang Tai', text: 'Not that time.', accent: 'neutral' },
    { kind: 'paragraph', text: 'He pushed a folded paper across the table.' },
    { kind: 'dialogue', speaker: 'Jiang Tai', text: 'Foreign agents have mapped three of our provincial command systems. Two governors can be bought. One Pillar can be isolated with a herb anyone can purchase in pieces.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Jian Yue\'s expression went cold.' },
    { kind: 'dialogue', speaker: 'Jiang Tai', text: 'Your Common Scale friends already demonstrated that last point.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'So this is fear.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jiang Tai', text: 'Preparedness.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Fear with stationery.', accent: 'primary' },
    { kind: 'paragraph', text: 'Jiang Tai leaned back.' },
    { kind: 'dialogue', speaker: 'Jiang Tai', text: 'Give me Qin Fei\'s half of the map.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'No.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jiang Tai', text: 'Then I find it without you.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You have been trying for three years.', accent: 'primary' },
    { kind: 'paragraph', text: 'The first real anger appeared in Jiang Tai\'s eyes.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'There you are.', accent: 'primary' },
    { kind: 'paragraph', text: 'Jiang Tai stood.' },
    { kind: 'dialogue', speaker: 'Jiang Tai', text: 'You think mercy saved the country that night.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'No.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jiang Tai', text: 'Then what did?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'People deciding they were allowed to stop.', accent: 'primary' },
    { kind: 'paragraph', text: 'Jiang Tai left without paying.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'I dislike him.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'He also skipped the bill.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Now I hate him.', accent: 'secondary' },
  ],
};

const chapter75: Chapter = {
  id: 's01-c75',
  season: 1,
  number: 75,
  title: 'The Archive Hidden in a Flood',
  summary: 'The half-map points not to a bunker but to a flood-control system. Gu hid his most dangerous archive inside the most boring public works project he could find.',
  readingMinutes: 10,
  tags: ['archive', 'flood-control', 'black-rain', 'wit', 'gu-zhaolin'],
  segments: [
    { kind: 'paragraph', text: 'The map did not show a secret base.' },
    { kind: 'paragraph', text: 'It showed drainage.' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'You are smiling again.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Gu hid a doctrine archive inside flood-control records.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Why is that funny?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Because nobody willingly audits drainage.', accent: 'primary' },
    { kind: 'paragraph', text: 'Qin Fei\'s half-map contained elevation marks rather than roads.' },
    { kind: 'paragraph', text: 'When Lu Chen overlaid them against pre-fire Yunqiao flood plans, only one structure matched.' },
    { kind: 'paragraph', text: 'Old Gate Twelve.' },
    { kind: 'paragraph', text: 'The gate had been buried when the river was redirected six years ago.' },
    { kind: 'dialogue', speaker: 'Ning Sui', text: 'If Jiang has the other half, he knows the same thing.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Not necessarily.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Why?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Because the river moved.', accent: 'primary' },
    { kind: 'paragraph', text: 'He pointed to three later flood projects.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'The old gate is now under a pottery district, two warehouses, and a public latrine.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'That feels disrespectful.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'History rarely controls zoning.', accent: 'primary' },
    { kind: 'break', label: 'Pottery district' },
    { kind: 'paragraph', text: 'They found the first access shaft under a kiln.' },
    { kind: 'paragraph', text: 'It was empty.' },
    { kind: 'paragraph', text: 'The second shaft had collapsed.' },
    { kind: 'paragraph', text: 'The third opened beneath the public latrine.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I refuse.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'National emergency.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'National dignity.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Get in.', accent: 'neutral' },
    { kind: 'paragraph', text: 'The tunnel beneath was dry, narrow, and offensively real.' },
    { kind: 'paragraph', text: 'At the far end they found a bronze flood gauge fixed to the wall.' },
    { kind: 'paragraph', text: 'The numbers were wrong.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'How wrong?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'River heights do not go seventeen, eighteen, twenty-two, four, nine.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Ning Sui', text: 'Cipher sequence.', accent: 'neutral' },
    { kind: 'paragraph', text: 'She translated the old field code.' },
    { kind: 'paragraph', text: 'TURN. WAIT. RETURN. LISTEN. OPEN.' },
    { kind: 'paragraph', text: 'Lu Chen rotated the gauge wheel, waited, reversed it, then stopped.' },
    { kind: 'paragraph', text: 'A section of wall released with a dull click.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I hate competent bureaucracy.', accent: 'primary' },
    { kind: 'paragraph', text: 'Behind the wall was not an armory.' },
    { kind: 'paragraph', text: 'It was a reading room.' },
    { kind: 'paragraph', text: 'Shelves held sealed ledgers, doctrine manuals, personnel assessments, code matrices, and after-action reports.' },
    { kind: 'paragraph', text: 'On the central desk sat a wooden box.' },
    { kind: 'paragraph', text: 'The lid had already been opened.' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Jiang was here.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Or someone before him.', accent: 'primary' },
    { kind: 'paragraph', text: 'Inside the box should have been the doctrine master index.' },
    { kind: 'paragraph', text: 'Instead there was a note.' },
    { kind: 'paragraph', text: 'Kai—if you are reading this, I was wrong twice. Once when I built it. Once when I thought destroying it would be enough.' },
    { kind: 'paragraph', text: 'The note was signed GU ZHAOLIN.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'He survived.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Long enough to write this.', accent: 'primary' },
    { kind: 'paragraph', text: 'There was one more line.' },
    { kind: 'paragraph', text: 'THE MASTER INDEX IS NOT HERE. I GAVE IT TO THE ONE PERSON I BELIEVED WOULD NEVER USE IT.' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Who?', accent: 'neutral' },
    { kind: 'paragraph', text: 'Xu Kai read the sentence again.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Me.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You have it?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'No.', accent: 'primary' },
    { kind: 'paragraph', text: 'He looked genuinely confused.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Which is inconvenient.', accent: 'primary' },
  ],
};

const chapter76: Chapter = {
  id: 's01-c76',
  season: 1,
  number: 76,
  title: 'The Thing Gu Gave Him Without Saying So',
  summary: 'Xu Kai has no memory of receiving the master index. Jian Yue realizes Gu may have hidden it inside something Xu Kai would never throw away.',
  readingMinutes: 9,
  tags: ['master-index', 'black-rain', 'memory', 'jian-yue', 'xu-kai'],
  segments: [
    { kind: 'paragraph', text: 'Xu Kai emptied his travel bag onto the inn bed.' },
    { kind: 'paragraph', text: 'Two shirts.' },
    { kind: 'paragraph', text: 'One notebook.' },
    { kind: 'paragraph', text: 'Yan Shuo\'s eastern command token.' },
    { kind: 'paragraph', text: 'Three restaurant receipts.' },
    { kind: 'paragraph', text: 'A spoon.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Why do you have a spoon?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'The inn charged extra for porridge utensils.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You stole it.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Recovered value.', accent: 'primary' },
    { kind: 'paragraph', text: 'There was no master index.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Case closed.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Seven years ago.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I owned less then.', accent: 'primary' },
    { kind: 'paragraph', text: 'They reconstructed the ninth bell.' },
    { kind: 'paragraph', text: 'Gu Zhaolin had been wounded.' },
    { kind: 'paragraph', text: 'Qin Fei had vanished.' },
    { kind: 'paragraph', text: 'Ning Sui had been running cancellation codes across the city.' },
    { kind: 'paragraph', text: 'Xu Kai had entered the command house alone.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'What did Gu give you?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'A headache.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Physical object.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'His cancellation seals. A key ring. One coat because mine was ruined.', accent: 'primary' },
    { kind: 'paragraph', text: 'Jian Yue looked up.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'The coat.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Burned two winters ago.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'How?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Cooking.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You cook?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Not successfully.', accent: 'primary' },
    { kind: 'paragraph', text: 'The key ring was gone.' },
    { kind: 'paragraph', text: 'The seals had been surrendered to the temporary investigation commission and later destroyed.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'What did you keep?', accent: 'secondary' },
    { kind: 'paragraph', text: 'Xu Kai went quiet.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'A brass rain gauge token.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Where?', accent: 'secondary' },
    { kind: 'paragraph', text: 'He looked toward the capital as though distance itself had become rude.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'My house.', accent: 'primary' },
    { kind: 'paragraph', text: 'Lu Chen received the message that evening.' },
    { kind: 'paragraph', text: 'His reply arrived through military relay before midnight.' },
    { kind: 'paragraph', text: 'YOUR HOUSE WAS SEARCHED THIS AFTERNOON.' },
    { kind: 'paragraph', text: 'NOTHING ELSE TAKEN.' },
    { kind: 'paragraph', text: 'BRASS TOKEN MISSING.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Jiang has it.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Maybe.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You hate certainty again.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'It keeps trying to kill us.', accent: 'primary' },
    { kind: 'paragraph', text: 'Ning Sui arrived with a cipher lens.' },
    { kind: 'dialogue', speaker: 'Ning Sui', text: 'The token was hollow.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You knew?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Ning Sui', text: 'I suspected. Gu loved objects with unnecessary compartments.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'What fits inside?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Ning Sui', text: 'Microfilm would be convenient if we had invented it.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Helpful.', accent: 'primary' },
    { kind: 'paragraph', text: 'She held up a thin roll of treated silk.' },
    { kind: 'dialogue', speaker: 'Ning Sui', text: 'Cipher silk. Thousands of characters if written under magnification.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Xu Kai stared at the empty space where the token should have been.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Gu gave me the master index because he knew I would forget it existed.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'That is insulting.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'It worked.', accent: 'primary' },
    { kind: 'paragraph', text: 'A messenger knocked on the inn door.' },
    { kind: 'paragraph', text: 'He carried a package from the capital.' },
    { kind: 'paragraph', text: 'Inside was the missing brass token.' },
    { kind: 'paragraph', text: 'Still sealed.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Then what did the thief take?', accent: 'secondary' },
    { kind: 'paragraph', text: 'Xu Kai smiled slowly.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'A fake.', accent: 'primary' },
  ],
};

const chapter77: Chapter = {
  id: 's01-c77',
  season: 1,
  number: 77,
  title: 'The Thief Who Stole the Wrong Secret',
  summary: 'Xu Kai had replaced Gu\'s token years ago because he disliked carrying official-looking objects. Jiang Tai now has a convincing fake and no idea he is being watched.',
  readingMinutes: 10,
  tags: ['brass-token', 'trap', 'jiang-tai', 'strategy', 'black-rain'],
  segments: [
    { kind: 'paragraph', text: 'Lu Chen had found the real token in an old rice jar.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Why?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I needed a paperweight.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You used a national assassination master index as a paperweight.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Technically the container.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Ning Sui', text: 'Gu would rise from the grave to complain.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'He can queue behind everyone else.', accent: 'primary' },
    { kind: 'paragraph', text: 'The fake token had been made five years earlier by a market smith after Xu Kai misplaced the original for three days.' },
    { kind: 'paragraph', text: 'It contained no cipher silk.' },
    { kind: 'paragraph', text: 'It did contain a folded tea-shop receipt.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Jiang broke into your house and stole a receipt.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Justice is beautiful.', accent: 'primary' },
    { kind: 'paragraph', text: 'The real token opened under Ning Sui\'s lens.' },
    { kind: 'paragraph', text: 'Inside was a strip of treated silk so thin it floated when she breathed.' },
    { kind: 'paragraph', text: 'It did not contain a list of targets.' },
    { kind: 'paragraph', text: 'It contained a list of people authorized to cancel targets.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'The master index is a list of brakes.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Ning Sui', text: 'Gu expected command compromise. Every province had hidden veto authorities.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'He really did build a conscience into it.', accent: 'primary' },
    { kind: 'paragraph', text: 'Twenty-seven names remained legible.' },
    { kind: 'paragraph', text: 'Eleven were dead.' },
    { kind: 'paragraph', text: 'Seven could not be located.' },
    { kind: 'paragraph', text: 'Nine were alive.' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'If Jiang wants a version without safeguards, these nine people are threats to him.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Which means he does not need the real index to start killing them.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'He only needs to think the fake gave him names.', accent: 'secondary' },
    { kind: 'paragraph', text: 'Silence.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Oh.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'What?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'The receipt.', accent: 'primary' },
    { kind: 'paragraph', text: 'He remembered the old tea-shop receipt inside the fake token.' },
    { kind: 'paragraph', text: 'Nine items had been ordered.' },
    { kind: 'paragraph', text: 'Each line began with a different customer name because the shopkeeper had split a group bill.' },
    { kind: 'dialogue', speaker: 'Ning Sui', text: 'Nine names.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Jiang may believe they are veto authorities.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I have accidentally weaponized lunch.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Again?', accent: 'secondary' },
    { kind: 'paragraph', text: 'The receipt was seven years old.' },
    { kind: 'paragraph', text: 'The first listed name was Madam He, proprietor of the tea shop.' },
    { kind: 'paragraph', text: 'She was still alive.' },
    { kind: 'paragraph', text: 'And still in Yunqiao.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'We need to move.', accent: 'primary' },
    { kind: 'paragraph', text: 'They arrived at Madam He\'s shop twelve minutes later.' },
    { kind: 'paragraph', text: 'The front door was open.' },
    { kind: 'paragraph', text: 'Three tables were overturned.' },
    { kind: 'paragraph', text: 'Madam He stood behind the counter holding a soup ladle.' },
    { kind: 'paragraph', text: 'A man lay unconscious at her feet.' },
    { kind: 'dialogue', speaker: 'Madam He', text: 'Kai?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You seem well.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Madam He', text: 'This idiot asked if I was a Black Rain veto authority.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'And you hit him?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Madam He', text: 'He touched my tea jars.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Reasonable.', accent: 'primary' },
    { kind: 'paragraph', text: 'The unconscious man carried a list.' },
    { kind: 'paragraph', text: 'All nine names from the receipt.' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Jiang believes it.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Xu Kai read the other eight names.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'He is going to spend the night attacking people who once shared a lunch bill.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'We have to protect them.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Yes.', accent: 'primary' },
    { kind: 'paragraph', text: 'Then he smiled.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'And while he does that, we find out who receives his reports.', accent: 'primary' },
  ],
};

const chapter78: Chapter = {
  id: 's01-c78',
  season: 1,
  number: 78,
  title: 'Nine Civilians Accidentally Become National Assets',
  summary: 'A tea-shop receipt becomes a national protection list. The Five arrive, Jiang Tai\'s network exposes itself, and Jian Yue gets much better at lying for Xu Kai.',
  readingMinutes: 11,
  tags: ['five-pillars', 'civilians', 'black-rain', 'comedy', 'secret'],
  segments: [
    { kind: 'paragraph', text: 'By sunset, nine completely ordinary people had acquired National-Tier protection.' },
    { kind: 'paragraph', text: 'None understood why.' },
    { kind: 'paragraph', text: 'The butcher was delighted.' },
    { kind: 'paragraph', text: 'The retired schoolmaster was offended.' },
    { kind: 'paragraph', text: 'Madam He charged Han Zhen for tea.' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'Why am I paying?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Madam He', text: 'Because you drank it.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Bai Ren', text: 'I like her.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Madam He', text: 'You still owe for the second pot.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Bai Ren', text: 'I fear her.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Han Zhen, Yan Shuo, and Bai Ren had arrived after Lu Chen requested discreet reinforcement.' },
    { kind: 'paragraph', text: 'They had interpreted discreet differently.' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'Why are we guarding a cobbler?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'He once ordered noodles with us.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'I am going to hit you.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Get in line.', accent: 'secondary' },
    { kind: 'paragraph', text: 'Jiang Tai\'s people approached six of the nine false targets.' },
    { kind: 'paragraph', text: 'Two fled when they saw military patrols.' },
    { kind: 'paragraph', text: 'Three were captured by Lu Chen\'s agents.' },
    { kind: 'paragraph', text: 'One made the mistake of entering Madam He\'s kitchen.' },
    { kind: 'paragraph', text: 'The kitchen resolved the matter independently.' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Every captured operative carries the same reporting token.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Where does it lead?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'A relay office outside South Gate.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'We raid it.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'No.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'Again.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'We send reports through it.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Bai Ren', text: 'False reports.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Mostly true.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'Why mostly?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Truth travels better.', accent: 'primary' },
    { kind: 'paragraph', text: 'The first report stated that the Five had converged on Yunqiao.' },
    { kind: 'paragraph', text: 'True.' },
    { kind: 'paragraph', text: 'The second said Xu Kai had opened Gu\'s archive.' },
    { kind: 'paragraph', text: 'True.' },
    { kind: 'paragraph', text: 'The third said the master index contained nine living veto authorities.' },
    { kind: 'paragraph', text: 'False, but Jiang already believed it.' },
    { kind: 'paragraph', text: 'The fourth said Jian Yue had been assigned to guard the index personally.' },
    { kind: 'paragraph', text: 'Technically false.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Why me?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Because he knows you protect important things.', accent: 'primary' },
    { kind: 'paragraph', text: 'She looked at him.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Careful.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Bai Ren', text: 'That sounded—', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Finish that sentence and die old man.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Bai Ren', text: 'I treasure silence.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Jiang took the bait before midnight.' },
    { kind: 'paragraph', text: 'A coded message instructed his remaining operatives to withdraw from civilian targets and prepare for “Index Recovery.”' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'Location?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Old Gate Twelve.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'He thinks Jian Yue will move the index through the flood tunnels.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'Will she?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Apparently.', accent: 'secondary' },
    { kind: 'paragraph', text: 'Han Zhen looked at Xu Kai.' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'You remain here.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Naturally.', accent: 'primary' },
    { kind: 'paragraph', text: 'Jian Yue looked at him.' },
    { kind: 'paragraph', text: 'He looked back.' },
    { kind: 'paragraph', text: 'Neither believed the sentence.' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'You are both doing it again.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Doing what?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Lying badly in coordination.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Jian Yue drew herself up.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'He is a civilian. Obviously he stays here.', accent: 'secondary' },
    { kind: 'paragraph', text: 'The lie was better this time.' },
    { kind: 'paragraph', text: 'Lu Chen looked almost disappointed.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Training works.', accent: 'primary' },
  ],
};

const chapter79: Chapter = {
  id: 's01-c79',
  season: 1,
  number: 79,
  title: 'Black Rain Falls a Second Time',
  summary: 'Jiang Tai moves for the master index at Old Gate Twelve. The Five expect a raid. Xu Kai realizes the raid is only there to keep them busy.',
  readingMinutes: 12,
  tags: ['climax', 'jiang-tai', 'black-rain', 'five-pillars', 'xu-kai'],
  segments: [
    { kind: 'paragraph', text: 'Old Gate Twelve filled with people who were pretending not to be National Tiers.' },
    { kind: 'paragraph', text: 'They were not convincing.' },
    { kind: 'paragraph', text: 'Han Zhen wore a laborer\'s coat like a declaration of war.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You look extremely normal.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'You were told to remain at the inn.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I got lost.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'For two districts.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Yunqiao zoning is hostile.', accent: 'primary' },
    { kind: 'paragraph', text: 'Jian Yue did not tell him to leave.' },
    { kind: 'paragraph', text: 'Han Zhen noticed.' },
    { kind: 'paragraph', text: 'Han Zhen said nothing.' },
    { kind: 'break', label: 'First bell' },
    { kind: 'paragraph', text: 'Jiang Tai\'s operatives entered the flood tunnels in three teams.' },
    { kind: 'paragraph', text: 'Yan Shuo intercepted the eastern team.' },
    { kind: 'paragraph', text: 'Bai Ren blocked the river exit.' },
    { kind: 'paragraph', text: 'Lu Chen sealed the pottery district.' },
    { kind: 'paragraph', text: 'Jian Yue carried the brass token in plain sight.' },
    { kind: 'paragraph', text: 'It was another fake.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You have too many of these.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I panic-manufactured six after losing the first.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Of course you did.', accent: 'secondary' },
    { kind: 'break', label: 'Second bell' },
    { kind: 'paragraph', text: 'The first fighting began underground.' },
    { kind: 'paragraph', text: 'Jiang\'s people were skilled enough to delay soldiers but not strong enough to defeat Pillars.' },
    { kind: 'paragraph', text: 'That bothered Xu Kai.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Too weak.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'What?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Jiang knows who is here. He would not send these people to win.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Diversion.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Xu Kai turned toward the city above.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'What changed because all Five came here?', accent: 'primary' },
    { kind: 'paragraph', text: 'Lu Chen swore softly.' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'The capital.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'No. We left deputies and royal guard.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Not the capital as a place. The assumption.', accent: 'primary' },
    { kind: 'paragraph', text: 'Ning Sui appeared at the tunnel mouth, pale.' },
    { kind: 'dialogue', speaker: 'Ning Sui', text: 'A Black Rain confirmation phrase just moved through old courier channels.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Target?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Ning Sui', text: 'Not a person.', accent: 'neutral' },
    { kind: 'paragraph', text: 'She held out the decoded strip.' },
    { kind: 'paragraph', text: 'TARGET: THE FIVE-PILLAR RESPONSE NETWORK.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'He does not want to assassinate officials.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'He wants to prove the country still collapses when the Five move together.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Common Scale gave him the idea.', accent: 'primary' },
    { kind: 'paragraph', text: 'Signal fires rose on the western ridge.' },
    { kind: 'paragraph', text: 'Then southern.' },
    { kind: 'paragraph', text: 'Then northern.' },
    { kind: 'paragraph', text: 'Three false provincial emergencies, all at once.' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'He is splitting us.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'He wants you to split yourselves.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'Then we stay together.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'And abandon three provinces to panic?', accent: 'primary' },
    { kind: 'paragraph', text: 'Han Zhen looked furious because both options were bad.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Stop being the answer.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'Explain quickly.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Make the provinces solve their own alarms. Use the Common Scale reforms we just passed. Provincial response councils. Local command verification. Civilian emergency boards.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'They are barely operational.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Then tonight they become operational.', accent: 'primary' },
    { kind: 'paragraph', text: 'Han Zhen understood first.' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'If we move, Jiang proves dependence. If we stay and local systems succeed, he proves the reforms work.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Very inconvenient for him.', accent: 'primary' },
    { kind: 'paragraph', text: 'Orders flew.' },
    { kind: 'paragraph', text: 'The Five stayed in Yunqiao.' },
    { kind: 'paragraph', text: 'For the first time in generations, three provinces received emergency alarms and no National Tier arrived.' },
    { kind: 'paragraph', text: 'They responded anyway.' },
    { kind: 'break', label: 'Fourth bell' },
    { kind: 'paragraph', text: 'The western alarm was exposed as a false grain-depot fire.' },
    { kind: 'paragraph', text: 'The south arrested two forged-order couriers.' },
    { kind: 'paragraph', text: 'The north evacuated a bridge, inspected it, and reopened it without asking a Pillar for permission.' },
    { kind: 'dialogue', speaker: 'Bai Ren', text: 'I feel unemployed.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Congratulations.', accent: 'primary' },
    { kind: 'paragraph', text: 'A slow clap came from the dark end of the flood chamber.' },
    { kind: 'paragraph', text: 'Jiang Tai stepped into the lamplight alone.' },
    { kind: 'dialogue', speaker: 'Jiang Tai', text: 'You improved the country just to ruin my demonstration.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Spite is productive when managed responsibly.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jiang Tai', text: 'Then give me the index.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'No.', accent: 'primary' },
    { kind: 'paragraph', text: 'Jiang Tai looked at Jian Yue.' },
    { kind: 'dialogue', speaker: 'Jiang Tai', text: 'He told you what he is.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Every other Pillar turned toward her.' },
    { kind: 'paragraph', text: 'Jian Yue did not blink.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'An idiot.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Oi.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Quiet.', accent: 'secondary' },
    { kind: 'paragraph', text: 'Jiang Tai smiled.' },
    { kind: 'dialogue', speaker: 'Jiang Tai', text: 'Good. Keep the secret a little longer.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Then he moved.' },
  ],
};

const chapter80: Chapter = {
  id: 's01-c80',
  season: 1,
  number: 80,
  title: 'Rain Ends Twice',
  summary: 'Jiang Tai tries to force Xu Kai to reveal himself before the Five. Jian Yue refuses to let him choose the terms, and Black Rain finally ends for good.',
  readingMinutes: 12,
  tags: ['black-rain', 'finale', 'jiang-tai', 'jian-yue', 'five-pillars'],
  segments: [
    { kind: 'paragraph', text: 'Jiang Tai did not attack Xu Kai.' },
    { kind: 'paragraph', text: 'He attacked Han Zhen.' },
    { kind: 'paragraph', text: 'This was smarter.' },
    { kind: 'paragraph', text: 'It was also a mistake.' },
    { kind: 'paragraph', text: 'Han Zhen met the first strike with enough force to crack three floor stones.' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'National Tier.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Bai Ren', text: 'High end.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Jiang Tai disengaged before the other Pillars closed.' },
    { kind: 'paragraph', text: 'Black powder burst from his sleeve.' },
    { kind: 'paragraph', text: 'Not poison.' },
    { kind: 'paragraph', text: 'Lamp soot.' },
    { kind: 'paragraph', text: 'The chamber went dark.' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Positions!', accent: 'neutral' },
    { kind: 'paragraph', text: 'Footsteps scattered through three tunnels.' },
    { kind: 'paragraph', text: 'Jiang had prepared echoes.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Nobody chase.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'He is escaping.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'He wants you separated again.', accent: 'primary' },
    { kind: 'paragraph', text: 'Jian Yue felt a hand catch her sleeve.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Oi. Left wall.', accent: 'primary' },
    { kind: 'paragraph', text: 'She understood.' },
    { kind: 'paragraph', text: 'Her sword flashed once.' },
    { kind: 'paragraph', text: 'A hidden panel split open.' },
    { kind: 'paragraph', text: 'Behind it, Jiang Tai was halfway through a narrow service passage.' },
    { kind: 'dialogue', speaker: 'Jiang Tai', text: 'You always see the door.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You always overdesign rooms.', accent: 'primary' },
    { kind: 'paragraph', text: 'Jiang threw three needles.' },
    { kind: 'paragraph', text: 'Jian Yue deflected all three.' },
    { kind: 'paragraph', text: 'She entered the passage after him.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Do not—', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Trust me.', accent: 'secondary' },
    { kind: 'paragraph', text: 'He stopped.' },
    { kind: 'paragraph', text: 'That was new.' },
    { kind: 'break', label: 'Above the flood chamber' },
    { kind: 'paragraph', text: 'Jian Yue drove Jiang Tai onto the pottery roofs.' },
    { kind: 'paragraph', text: 'Rain had begun again over Yunqiao.' },
    { kind: 'paragraph', text: 'People below kept walking without umbrellas.' },
    { kind: 'paragraph', text: 'Jiang Tai laughed when he saw the rain.' },
    { kind: 'dialogue', speaker: 'Jiang Tai', text: 'Appropriate.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'No.', accent: 'secondary' },
    { kind: 'paragraph', text: 'She attacked.' },
    { kind: 'paragraph', text: 'Jiang Tai was fast enough to make ordinary masters invisible.' },
    { kind: 'paragraph', text: 'Jian Yue was Jian Yue.' },
    { kind: 'paragraph', text: 'Their first exchange removed half a roof ridge.' },
    { kind: 'paragraph', text: 'The second shattered Jiang\'s short blade.' },
    { kind: 'paragraph', text: 'The third put blood on his sleeve.' },
    { kind: 'dialogue', speaker: 'Jiang Tai', text: 'You know he could end this faster.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Probably.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Jiang Tai', text: 'Does that not bother you?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'He asked me to trust him for months while I thought he was weak.', accent: 'secondary' },
    { kind: 'paragraph', text: 'Her sword turned.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'He can trust me for five minutes while I am not.', accent: 'secondary' },
    { kind: 'paragraph', text: 'She broke Jiang Tai\'s stance.' },
    { kind: 'paragraph', text: 'Below, Xu Kai heard every word.' },
    { kind: 'paragraph', text: 'He smiled once.' },
    { kind: 'break', label: 'The last safeguard' },
    { kind: 'paragraph', text: 'Lu Chen found a second cipher strip on Jiang\'s abandoned coat.' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'There is another activation.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Target?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Nine provincial governors.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'Can the index stop it?', accent: 'neutral' },
    { kind: 'paragraph', text: 'Xu Kai opened the real brass token.' },
    { kind: 'paragraph', text: 'Ning Sui read the cipher silk.' },
    { kind: 'dialogue', speaker: 'Ning Sui', text: 'Yes. But each cancellation requires a living veto authority.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Bai Ren', text: 'How many can we reach?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Ning Sui', text: 'Nine are alive.', accent: 'neutral' },
    { kind: 'paragraph', text: 'The absurdity landed at once.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'The actual nine.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Not the lunch receipt.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Disappointing. Madam He was excellent.', accent: 'primary' },
    { kind: 'paragraph', text: 'They used every relay in Yunqiao.' },
    { kind: 'paragraph', text: 'Military mirrors.' },
    { kind: 'paragraph', text: 'Merchant couriers.' },
    { kind: 'paragraph', text: 'Temple bells.' },
    { kind: 'paragraph', text: 'One extremely confused pigeon service.' },
    { kind: 'paragraph', text: 'Eight veto authorities answered.' },
    { kind: 'paragraph', text: 'The ninth did not.' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'Location?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Ning Sui', text: 'Yunqiao.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Everyone looked at Qin Fei.' },
    { kind: 'dialogue', speaker: 'Qin Fei', text: 'What?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Ning Sui', text: 'You are veto nine.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Qin Fei', text: 'Gu never told me.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'He was apparently committed to surprising people after death.', accent: 'primary' },
    { kind: 'paragraph', text: 'Qin Fei pressed his burned palm to the old confirmation plate.' },
    { kind: 'paragraph', text: 'The final cancellation moved through Black Rain.' },
    { kind: 'paragraph', text: 'Across nine provinces, dormant cells received the same message.' },
    { kind: 'paragraph', text: 'STAND DOWN. AUTHORITY VERIFIED. DOCTRINE TERMINATED.' },
    { kind: 'break', label: 'Roof' },
    { kind: 'paragraph', text: 'Jiang Tai felt the cancellation bell from the city tower.' },
    { kind: 'paragraph', text: 'His face changed.' },
    { kind: 'dialogue', speaker: 'Jiang Tai', text: 'Again.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Yes.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Jiang Tai', text: 'He ruined it again.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'No.', accent: 'secondary' },
    { kind: 'paragraph', text: 'She lowered her sword slightly.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'People stopped it.', accent: 'secondary' },
    { kind: 'paragraph', text: 'Jiang Tai attacked anyway.' },
    { kind: 'paragraph', text: 'Jian Yue disarmed him in four exchanges.' },
    { kind: 'paragraph', text: 'On the fifth, she put him through a roof.' },
    { kind: 'paragraph', text: 'Xu Kai looked up as Jiang Tai landed in a pottery storeroom.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Very direct.', accent: 'primary' },
    { kind: 'paragraph', text: 'Jian Yue dropped through the hole after him.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'I enjoy my methods.', accent: 'secondary' },
    { kind: 'paragraph', text: 'Yan Shuo laughed loud enough to be heard in the street.' },
    { kind: 'break', label: 'Three days later' },
    { kind: 'paragraph', text: 'Black Rain was dismantled properly this time.' },
    { kind: 'paragraph', text: 'Not burned.' },
    { kind: 'paragraph', text: 'Not hidden.' },
    { kind: 'paragraph', text: 'Documented.' },
    { kind: 'paragraph', text: 'Every surviving cell was identified. Every cancellation authority was placed under civilian oversight. The doctrine manuals went into a sealed state archive with three independent custodians.' },
    { kind: 'paragraph', text: 'Qin Fei accepted amnesty under protest.' },
    { kind: 'paragraph', text: 'Ning Sui refused a government job before anyone offered one.' },
    { kind: 'paragraph', text: 'Madam He invoiced the Ministry for a broken tea jar.' },
    { kind: 'paragraph', text: 'The Ministry paid.' },
    { kind: 'break', label: 'The sixth chair' },
    { kind: 'paragraph', text: 'Back in the Hall of Five, Han Zhen placed Gu\'s personnel assessment file in front of Xu Kai.' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'This was in the archive.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Xu Kai opened it.' },
    { kind: 'paragraph', text: 'Most of the page had been blacked out decades earlier.' },
    { kind: 'paragraph', text: 'One sentence remained.' },
    { kind: 'paragraph', text: 'SUBJECT KAI: PRINCIPAL DANGER IS NOT CAPABILITY. PRINCIPAL DANGER IS THAT HE MAKES PEOPLE QUESTION THE ORDER THEY WERE GIVEN.' },
    { kind: 'paragraph', text: 'Bai Ren whistled.' },
    { kind: 'dialogue', speaker: 'Bai Ren', text: 'Accurate.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'What was blacked out?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Probably compliments.', accent: 'primary' },
    { kind: 'paragraph', text: 'Jian Yue knew better.' },
    { kind: 'paragraph', text: 'At the bottom of the page, under the censor ink, one word was still faintly visible.' },
    { kind: 'paragraph', text: 'CAPABILITY: UNMEASURABLE.' },
    { kind: 'paragraph', text: 'Jian Yue quietly folded that corner under before Lu Chen leaned closer.' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'What was there?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Nothing.', accent: 'secondary' },
    { kind: 'paragraph', text: 'The lie was smooth.' },
    { kind: 'paragraph', text: 'Xu Kai looked at her.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Training works.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Oi.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'What?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Buy me dinner.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Why?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'I just saved your secret and your country.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You put a man through a roof.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'That was for me.', accent: 'secondary' },
    { kind: 'paragraph', text: 'He smiled.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Fine.', accent: 'primary' },
    { kind: 'paragraph', text: 'A palace clerk entered carrying a gold-edged diplomatic scroll.' },
    { kind: 'dialogue', speaker: 'Palace Clerk', text: 'Imperial Examiner Xu. Liangbei requests you by name for emergency treaty negotiations.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Xu Kai looked at Jian Yue.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Dinner may be delayed.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'No.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Palace Clerk', text: 'It is a matter of state.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'So is dinner.', accent: 'secondary' },
  ],
};

const newChapters = [chapter73, chapter74, chapter75, chapter76, chapter77, chapter78, chapter79, chapter80];

export const seasons: Season[] = baseSeasons.map((season) => {
  if (season.number !== 1) {
    return season;
  }

  return {
    ...season,
    subtitle: 'A dangerous civilian acquires a National-Tier supervisor and accidentally becomes a national policy problem.',
    description: 'Xu Kai solves crises through observation, manipulation, economics, social engineering, and shameless conversation while Jian Yue, National Tier #2, now protects both the man and the impossible secret she learned about him.',
    chapters: [...season.chapters, ...newChapters],
  };
});
