import type { Chapter, Season } from '../domain/types';
import { seasons as baseSeasons } from './story-v7';

const chapter35: Chapter = {
  id: 's01-c35',
  season: 1,
  number: 35,
  title: 'The Vice Minister Would Like His Evidence Back',
  summary: 'Gao Wen responds to the reopened Heshan case by politely ordering every piece of evidence surrendered to the very ministry implicated by it.',
  readingMinutes: 10,
  tags: ['gao-wen', 'heshan', 'lu-chen', 'jian-yue', 'politics'],
  segments: [
    { kind: 'paragraph', text: 'Vice Minister Gao Wen\'s order arrived on cream paper, under three official seals, with the careful courtesy of a knife wrapped in silk.' },
    { kind: 'paragraph', text: 'Lu Chen read it twice.' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'He wants everything.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Greedy.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Can he legally demand it?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Some of it.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'That sounded bureaucratically tragic.', accent: 'primary' },
    { kind: 'paragraph', text: 'They were still in Heshan. Auntie Lan had placed the procurement receipt beneath an overturned rice bowl because, in her words, important men were less likely to steal things if they first had to move kitchenware.' },
    { kind: 'dialogue', speaker: 'Auntie Lan', text: 'Is this Gao man the one who stole our grain?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Maybe.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Auntie Lan', text: 'You got less annoying with age.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'That is the cruelest thing you have said to me.', accent: 'primary' },
    { kind: 'paragraph', text: 'Lu Chen placed Gao Wen\'s order beside the receipt.' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'The Revenue Ministry claims exclusive jurisdiction over historical procurement fraud involving its predecessor offices.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'And Gao Wen is Vice Minister of Revenue.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'He has achieved the rare privilege of investigating himself professionally.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'The Ministry will argue that he was only a provincial deputy at the time and cannot be presumed conflicted.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Then we should congratulate him on his promotion before distrusting him.', accent: 'primary' },
    { kind: 'paragraph', text: 'Jian Yue took the order.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'What happens if we refuse?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'He petitions the Imperial Finance Council. The Council orders compliance. If we still refuse, it becomes an inter-ministry dispute.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Excellent. Nothing protects truth like twelve senior officials arguing over filing authority.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Can I refuse for you?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'On what grounds?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'I dislike him already.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Not currently recognized in statute.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'A legislative failure.', accent: 'primary' },
    { kind: 'break', label: 'An hour later' },
    { kind: 'paragraph', text: 'Xu Kai asked Mei Rong to copy every surviving Heshan paper three times.' },
    { kind: 'dialogue', speaker: 'Mei Rong', text: 'You intend to surrender the originals?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Eventually.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Define eventually.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'After we discover why he wants them quickly.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Because they implicate him.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Too simple.', accent: 'primary' },
    { kind: 'paragraph', text: 'He tapped Gao Wen\'s order.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'If he only wanted the evidence destroyed, he would not create an official record showing he demanded custody of it.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'So he believes possession helps him.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Or he is afraid of something in these papers that we have not understood yet.', accent: 'primary' },
    { kind: 'paragraph', text: 'Mei Rong looked at the procurement receipt.' },
    { kind: 'dialogue', speaker: 'Mei Rong', text: 'The missing grain?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Everyone keeps looking at what vanished.', accent: 'primary' },
    { kind: 'paragraph', text: 'He turned the receipt over.' },
    { kind: 'paragraph', text: 'His younger handwriting crowded the back: bowl counts, delivery days, duplicated invoice numbers, lamp oil, cloth bundles.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I want to know what arrived.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'That sounds backwards.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'So did the frontier.', accent: 'primary' },
    { kind: 'paragraph', text: 'Auntie Lan disappeared into the old kitchen.' },
    { kind: 'paragraph', text: 'She returned with a wooden box full of cracked household tallies.' },
    { kind: 'dialogue', speaker: 'Auntie Lan', text: 'If you are counting things, count these.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Xu Kai opened the box.' },
    { kind: 'paragraph', text: 'The first tally was for winter blankets.' },
    { kind: 'paragraph', text: 'The second was for medicine.' },
    { kind: 'paragraph', text: 'The third was for ink.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Why did a relief house receive twenty-four jars of archival ink?', accent: 'primary' },
    { kind: 'paragraph', text: 'No one answered.' },
    { kind: 'dialogue', speaker: 'Mei Rong', text: 'Archival ink does not wash away easily.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'It is used for permanent government ledgers.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'And we received enough to rewrite a small ministry.', accent: 'primary' },
    { kind: 'paragraph', text: 'Jian Yue folded her arms.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'So Gao Wen may not want the evidence because it proves theft.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'He may want it because it proves someone was manufacturing records.', accent: 'primary' },
    { kind: 'paragraph', text: 'Lu Chen looked toward the capital road.' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Then we should go back before he has time to clean his ministry.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'No.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'No?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'If he is cleaning, I want him to finish.', accent: 'primary' },
    { kind: 'paragraph', text: 'Jian Yue stared at him.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'People reveal what they fear by what they remove first.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You are going to let him destroy evidence.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Copies exist.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'He does not know that.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Exactly.', accent: 'primary' },
    { kind: 'paragraph', text: 'Jian Yue looked increasingly unhappy.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'I hate plans where the first step is allowing the enemy to do something.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'That is because swords have poor patience.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Swords also solve arguments quickly.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'And people wonder why I prefer paperwork.', accent: 'primary' },
  ],
};

const chapter36: Chapter = {
  id: 's01-c36',
  season: 1,
  number: 36,
  title: 'A Very Honest Man with Four Account Books',
  summary: 'Xu Kai finally meets Gao Wen, who is courteous, composed, and apparently eager to cooperate. This is immediately suspicious.',
  readingMinutes: 11,
  tags: ['gao-wen', 'capital', 'politics', 'xu-kai', 'jian-yue'],
  segments: [
    { kind: 'paragraph', text: 'Gao Wen received them personally.' },
    { kind: 'paragraph', text: 'That was the first thing Xu Kai disliked.' },
    { kind: 'paragraph', text: 'The second was the tea.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Too good.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Gao Wen', text: 'I beg your pardon?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'The tea. Public servants should not have tea this good.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Gao Wen', text: 'A gift from the southern tax commissioner.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'That did not improve the answer.', accent: 'primary' },
    { kind: 'paragraph', text: 'Jian Yue sat beside Xu Kai rather than across from him.' },
    { kind: 'paragraph', text: 'Gao Wen noticed.' },
    { kind: 'paragraph', text: 'He noticed everything politely.' },
    { kind: 'dialogue', speaker: 'Gao Wen', text: 'Lady Jian. Lord Lu. Mister Xu. I appreciate that you came directly to me.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'You ordered us to.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Gao Wen', text: 'And you came. Cooperation is becoming fashionable.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Do not encourage it.', accent: 'primary' },
    { kind: 'paragraph', text: 'Gao Wen smiled.' },
    { kind: 'paragraph', text: 'He was in his early fifties, silver beginning at his temples, with the relaxed posture of a man who had spent twenty years learning that important rooms eventually became his.' },
    { kind: 'dialogue', speaker: 'Gao Wen', text: 'You were at Heshan Relief House.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You were at the Provincial Relief Office.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Gao Wen', text: 'Then we share an unfortunate piece of history.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Mine had worse food.', accent: 'primary' },
    { kind: 'paragraph', text: 'Gao Wen opened four account books.' },
    { kind: 'dialogue', speaker: 'Gao Wen', text: 'These are the surviving provincial relief ledgers from that year.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'You already gathered them.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Gao Wen', text: 'The moment I learned old allegations had resurfaced.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Efficient.', accent: 'secondary' },
    { kind: 'paragraph', text: 'It was not praise.' },
    { kind: 'dialogue', speaker: 'Gao Wen', text: 'I prefer that to defensive.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Xu Kai opened the first ledger.' },
    { kind: 'paragraph', text: 'Every page was orderly.' },
    { kind: 'paragraph', text: 'Every total balanced.' },
    { kind: 'paragraph', text: 'Every transfer had two signatures.' },
    { kind: 'paragraph', text: 'It was beautiful.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'This is disgusting.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Gao Wen', text: 'Most auditors react differently.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Most auditors enjoy being lied to neatly.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'What is wrong with it?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Nothing.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Which means?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Real relief accounts are ugly. Storms happen. Roads close. Medicine spoils. Someone writes seven instead of nine. A mule dies and ruins a month.', accent: 'primary' },
    { kind: 'paragraph', text: 'He turned another page.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'This ledger has survived disaster without a single clerical mistake.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Gao Wen', text: 'Competence is not evidence of fraud.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'No. But perfection is often evidence of rewriting.', accent: 'primary' },
    { kind: 'paragraph', text: 'Gao Wen\'s smile remained.' },
    { kind: 'dialogue', speaker: 'Gao Wen', text: 'Then examine them.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You want me to?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Gao Wen', text: 'I want the truth.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'That sounded expensive.', accent: 'primary' },
    { kind: 'paragraph', text: 'Gao Wen leaned back.' },
    { kind: 'dialogue', speaker: 'Gao Wen', text: 'Mister Xu, you assume I am afraid because my seal appears on one receipt.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'No.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Gao Wen', text: 'No?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I assume you are afraid because you sent an order across two provinces to retrieve a receipt you had not officially seen.', accent: 'primary' },
    { kind: 'paragraph', text: 'The room became still.' },
    { kind: 'paragraph', text: 'Gao Wen\'s smile changed by less than a breath.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'There it is.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Gao Wen', text: 'There what is?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'A human being.', accent: 'primary' },
    { kind: 'paragraph', text: 'Jian Yue looked down to hide the beginning of a smile.' },
    { kind: 'dialogue', speaker: 'Gao Wen', text: 'You are exactly as irritating as reported.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'The reports are incomplete.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Oi.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'That was support.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I felt something warm and unfamiliar.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'It will pass.', accent: 'secondary' },
    { kind: 'paragraph', text: 'Gao Wen closed the first ledger.' },
    { kind: 'dialogue', speaker: 'Gao Wen', text: 'Keep copies. Keep observers. Keep Lady Jian beside you if that makes everyone comfortable. But leave the original Heshan evidence here tonight.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Why tonight?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Gao Wen', text: 'Because the Imperial Finance Council meets tomorrow morning.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'And you want to tell them you control the file.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Gao Wen', text: 'I want to tell them the Revenue Ministry is functioning.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Those sentences are cousins.', accent: 'primary' },
    { kind: 'paragraph', text: 'Lu Chen agreed to surrender one sealed evidence packet under joint custody.' },
    { kind: 'paragraph', text: 'Xu Kai did not object.' },
    { kind: 'paragraph', text: 'That was the third thing Gao Wen should have disliked.' },
  ],
};

const chapter37: Chapter = {
  id: 's01-c37',
  season: 1,
  number: 37,
  title: 'The Ledger That Improved Overnight',
  summary: 'Xu Kai gives Gao Wen exactly what he asked for. By morning, one ministry ledger has become slightly more perfect—and therefore much more useful.',
  readingMinutes: 10,
  tags: ['audit', 'gao-wen', 'trap', 'lu-chen', 'wit'],
  segments: [
    { kind: 'paragraph', text: 'At sunrise, Xu Kai asked for the ledgers again.' },
    { kind: 'paragraph', text: 'Gao Wen sent them within twelve minutes.' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'That was fast.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Efficiency continues to stalk us.', accent: 'primary' },
    { kind: 'paragraph', text: 'They examined the books in a Ministry archive room under the supervision of two Revenue clerks, one Imperial Finance Council auditor, Lu Chen, Jian Yue, and a pot of tea nobody trusted.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'What are we looking for?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Improvement.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'In an old ledger?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'People cannot resist fixing things once they know where you are looking.', accent: 'primary' },
    { kind: 'paragraph', text: 'He compared yesterday\'s charcoal rubbings of the binding stitches against the current books.' },
    { kind: 'paragraph', text: 'One thread had been replaced.' },
    { kind: 'paragraph', text: 'Lu Chen noticed next.' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Book three was opened and resewn.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Revenue Clerk', text: 'Old bindings fail.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'During the night?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Revenue Clerk', text: 'It happens.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'History is very active in this building.', accent: 'primary' },
    { kind: 'paragraph', text: 'Page 184 recorded ink deliveries to six provincial relief sites.' },
    { kind: 'paragraph', text: 'Heshan now received six jars.' },
    { kind: 'paragraph', text: 'The household tally found by Auntie Lan said twenty-four.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Someone changed the quantity.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Someone changed it from strange to ordinary.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Which means they knew we noticed the ink.', accent: 'neutral' },
    { kind: 'paragraph', text: 'The two Revenue clerks looked at each other.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Thank you.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Revenue Clerk', text: 'For what?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'That.', accent: 'primary' },
    { kind: 'paragraph', text: 'Neither clerk spoke.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'One of you knew the page had changed. The other did not.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Revenue Clerk', text: 'You cannot know that from a glance.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'No. I know it because he looked at you before looking at the page.', accent: 'primary' },
    { kind: 'paragraph', text: 'The younger clerk went pale.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Should I close the door?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Oi. That sounded threatening.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'It was geometry.', accent: 'secondary' },
    { kind: 'paragraph', text: 'Lu Chen closed the door.' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'I also understand geometry.', accent: 'neutral' },
    { kind: 'paragraph', text: 'The younger clerk lasted four minutes.' },
    { kind: 'dialogue', speaker: 'Young Clerk', text: 'Assistant Director Meng ordered the replacement page.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'On whose authority?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Young Clerk', text: 'He said the original had water damage.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Did the original have water damage?', accent: 'primary' },
    { kind: 'paragraph', text: 'The clerk looked miserable.' },
    { kind: 'dialogue', speaker: 'Young Clerk', text: 'It had twenty-four jars.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Lu Chen wrote the confession himself.' },
    { kind: 'break', label: 'Assistant Director Meng' },
    { kind: 'paragraph', text: 'Meng was found at breakfast.' },
    { kind: 'paragraph', text: 'He denied altering evidence.' },
    { kind: 'paragraph', text: 'Then denied having breakfast.' },
    { kind: 'paragraph', text: 'The second denial was more difficult because he was holding a steamed bun.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'We are off to a poor start.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Meng', text: 'Vice Minister Gao knows nothing about this.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I did not ask about Vice Minister Gao.', accent: 'primary' },
    { kind: 'paragraph', text: 'Meng stopped.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Now we are improving.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Meng', text: 'I only corrected a transcription error.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'On a seven-year-old original ledger during an active investigation.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Meng', text: 'The number was obviously wrong.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Why?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Meng', text: 'No relief house needed twenty-four jars of archival ink.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Xu Kai smiled.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Exactly.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Meng', text: 'Exactly what?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You just told us the strange number mattered.', accent: 'primary' },
    { kind: 'paragraph', text: 'Meng looked toward Jian Yue as though National Tier #2 might somehow be the less dangerous conversation.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Do not look at me. I am enjoying this.', accent: 'secondary' },
    { kind: 'paragraph', text: 'Meng confessed to changing the page.' },
    { kind: 'paragraph', text: 'He did not confess who told him the number was dangerous.' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'We can detain him.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'No.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Again?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Let him go back to work.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Why?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Because whoever frightened him will want to know how much he said.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'So we follow him.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'No.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'I am beginning to dislike that word.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'We follow the person who follows him.', accent: 'primary' },
    { kind: 'paragraph', text: 'Lu Chen looked almost pleased.' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'That is my department.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Finally, government specialization works.', accent: 'primary' },
  ],
};

const chapter38: Chapter = {
  id: 's01-c38',
  season: 1,
  number: 38,
  title: 'The Five Pillars Have a Personnel Problem',
  summary: 'The Five meet to decide what Xu Kai actually is to the state. Nobody agrees, especially Jian Yue.',
  readingMinutes: 10,
  tags: ['five-pillars', 'hall-of-five', 'romance', 'politics', 'xu-kai'],
  segments: [
    { kind: 'paragraph', text: 'The Hall of Five had been designed for five people.' },
    { kind: 'paragraph', text: 'Xu Kai continued to treat this as a suggestion.' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'You are in my chair again.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'The sixth chair remains empty.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'Because there are five Pillars.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Then why own six chairs?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Bai Ren', text: 'He has a point.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'Do not help him.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Yan Shuo had returned from the frontier for two days. Lu Chen brought the Revenue Ministry file. Jian Yue brought herself and the clear intention to disagree with anything inconvenient.' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'This meeting is not about Gao Wen.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Promising start.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'It is about you.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Worse start.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'You now hold an eastern command pass, have participated in cross-border negotiations, possess access to active investigations, and have no official office.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'A model citizen.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'Give him an office.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'No.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'He does not need one.', accent: 'secondary' },
    { kind: 'paragraph', text: 'Everyone looked at Jian Yue.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'What?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Bai Ren', text: 'Nothing.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You are smiling.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Bai Ren', text: 'Old age.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Han Zhen ignored them.' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'Without an office, he answers to no formal chain of command.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'He answers to me.', accent: 'secondary' },
    { kind: 'paragraph', text: 'Silence.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Do I?', accent: 'primary' },
    { kind: 'paragraph', text: 'Jian Yue realized what she had said.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'For supervision.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'Of course.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Do not start.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I was going to ask about benefits.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You get to remain alive.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Competitive package.', accent: 'primary' },
    { kind: 'paragraph', text: 'Lu Chen placed three proposals on the table.' },
    { kind: 'paragraph', text: 'The first made Xu Kai a civilian adviser to the Grand Marshal.' },
    { kind: 'paragraph', text: 'The second attached him to the Ministry of State Security.' },
    { kind: 'paragraph', text: 'The third created a temporary Imperial Examiner role reporting to the Five collectively.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'All terrible.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'You were not asked to vote.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Democracy dies quietly.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'The third one.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Agreed.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Bai Ren', text: 'Give him no staff.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You are my favorite today.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'He needs staff.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Favorite status revoked.', accent: 'primary' },
    { kind: 'paragraph', text: 'Jian Yue had not spoken.' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'Jian Yue?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'I dislike all three.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Reason?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'An official position makes him a formal target.', accent: 'secondary' },
    { kind: 'paragraph', text: 'Xu Kai looked at her.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'He is already targeted enough.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Oi.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'What?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'That sounded like concern in front of witnesses.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'I can correct that.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Bai Ren', text: 'Please do not. I am enjoying the historical record.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Han Zhen rubbed his forehead.' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'Temporary examiner. No public announcement until Gao Wen is resolved.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Do I get paid?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'Yes.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I withdraw several principled objections.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Cheap.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Affordable.', accent: 'primary' },
    { kind: 'paragraph', text: 'The vote passed four to one.' },
    { kind: 'paragraph', text: 'Jian Yue was the one.' },
    { kind: 'paragraph', text: 'She spent the rest of the meeting insisting this was because the appointment was strategically premature.' },
    { kind: 'paragraph', text: 'Nobody believed her.' },
  ],
};

const chapter39: Chapter = {
  id: 's01-c39',
  season: 1,
  number: 39,
  title: 'The Accountant Who Died Twice',
  summary: 'Lu Chen follows the man behind the altered ledger and finds a dead accountant with two death certificates and one very active pension.',
  readingMinutes: 11,
  tags: ['investigation', 'accountant', 'gao-wen', 'lu-chen', 'mystery'],
  segments: [
    { kind: 'paragraph', text: 'Assistant Director Meng was followed by three different people after work.' },
    { kind: 'paragraph', text: 'One was Lu Chen\'s agent.' },
    { kind: 'paragraph', text: 'The second was a Revenue Ministry clerk.' },
    { kind: 'paragraph', text: 'The third sold candied hawthorn and was genuinely just going home.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Respect the hawthorn man.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'I do.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Meng met nobody.' },
    { kind: 'paragraph', text: 'Instead he left a paper token beneath a bridge stone.' },
    { kind: 'paragraph', text: 'Two hours later, an old woman collected it.' },
    { kind: 'paragraph', text: 'The old woman delivered laundry to a boarding house.' },
    { kind: 'paragraph', text: 'The boarding house rented one room to a man named Qiao Min.' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Qiao Min died nine years ago.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Inconvenient tenant.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Maybe someone uses his name.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Someone does more than that. Qiao Min receives a state pension.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Death has improved financially.', accent: 'primary' },
    { kind: 'paragraph', text: 'They entered the boarding house after midnight.' },
    { kind: 'paragraph', text: 'Jian Yue went first because Xu Kai was, according to Jian Yue, physically unsuited to entering suspicious rooms.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I can open a door.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You can stand behind me while I open a door.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'My talents are being suppressed.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Quiet.', accent: 'neutral' },
    { kind: 'paragraph', text: 'The room was empty.' },
    { kind: 'paragraph', text: 'It contained three shirts, two pairs of shoes, a stove, a mattress, and enough accounting paper to frighten a small province.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'He lives beautifully.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You own one table.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'A hostile table.', accent: 'primary' },
    { kind: 'paragraph', text: 'Lu Chen opened a locked chest.' },
    { kind: 'paragraph', text: 'Inside were pension receipts, identity papers, old provincial seals, and two death certificates for Qiao Min.' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'One says he died of fever nine years ago.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'The other?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Warehouse collapse. Seven years ago.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Very committed.', accent: 'primary' },
    { kind: 'paragraph', text: 'A loose board beneath the mattress hid a third document.' },
    { kind: 'paragraph', text: 'It was not a death certificate.' },
    { kind: 'paragraph', text: 'It was a payroll list.' },
    { kind: 'paragraph', text: 'Qiao Min had been chief reconciliation accountant for the Provincial Relief Office during Heshan.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'There.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'He reconciled local delivery records against central payments.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Meaning if two invoices existed for one sack of grain, he was supposed to notice.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'And instead he died twice.', accent: 'secondary' },
    { kind: 'paragraph', text: 'The door opened behind them.' },
    { kind: 'paragraph', text: 'Jian Yue\'s sword left its sheath.' },
    { kind: 'dialogue', speaker: 'Old Man', text: 'Please do not kill me in my own rented room.', accent: 'neutral' },
    { kind: 'paragraph', text: 'The old man was thin, grey, and holding a bag of turnips.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Qiao Min?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Old Man', text: 'Depends who is asking.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'A civilian with poor boundaries.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Ministry of State Security.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'National Tier #2.', accent: 'secondary' },
    { kind: 'paragraph', text: 'The old man looked at Xu Kai.' },
    { kind: 'dialogue', speaker: 'Qiao Min', text: 'I prefer the civilian.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Excellent judgment.', accent: 'primary' },
    { kind: 'break', label: 'Turnips and treason' },
    { kind: 'paragraph', text: 'Qiao Min had not died.' },
    { kind: 'paragraph', text: 'He had been paid to disappear.' },
    { kind: 'dialogue', speaker: 'Qiao Min', text: 'The books were wrong before they reached me.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Who altered them?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Qiao Min', text: 'Nobody altered them. They were created wrong.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Xu Kai leaned forward.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Explain.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Qiao Min', text: 'Two accounting systems. Provincial offices recorded real deliveries. The central relief ledger recorded larger ones. The difference became claimable expense.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Someone billed the state for supplies that never existed.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Qiao Min', text: 'For years.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Gao Wen?', accent: 'neutral' },
    { kind: 'paragraph', text: 'Qiao Min looked toward the window.' },
    { kind: 'dialogue', speaker: 'Qiao Min', text: 'Gao found it.', accent: 'neutral' },
    { kind: 'paragraph', text: 'No one spoke.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Found it?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Qiao Min', text: 'He did not build the scheme. He discovered it as a deputy. Then he decided exposing it would destroy half the provincial government.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'So he buried it.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Qiao Min', text: 'He took control of it.', accent: 'neutral' },
    { kind: 'paragraph', text: 'That was worse.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'How many people paid him to keep their old thefts quiet?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Qiao Min', text: 'Enough to make him Vice Minister.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Jian Yue\'s expression went cold.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Now can I dislike him officially?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Yes.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Historic legislative progress.', accent: 'primary' },
    { kind: 'paragraph', text: 'Qiao Min put the turnips on the table.' },
    { kind: 'dialogue', speaker: 'Qiao Min', text: 'If Gao knows I am alive, I am dead for a third time.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Then let us preserve tradition and keep you deceased.', accent: 'primary' },
  ],
};

const newChapters = [chapter35, chapter36, chapter37, chapter38, chapter39];

export const seasons: Season[] = baseSeasons.map((season) => {
  if (season.number !== 1) {
    return season;
  }

  return {
    ...season,
    chapters: [...season.chapters, ...newChapters],
  };
});
