import type { Chapter, Season } from '../domain/types';
import { seasons as baseSeasons } from './story-v6';

const chapter30: Chapter = {
  id: 's01-c30',
  season: 1,
  number: 30,
  title: 'The Road Xu Kai Did Not Want',
  summary: 'Xu Kai returns to Heshan with Jian Yue, Lu Chen, and an entirely unnecessary Liangbei observer. The closer they get, the less he jokes.',
  readingMinutes: 10,
  tags: ['heshan', 'road-trip', 'identity', 'romance', 'lin-shuying'],
  segments: [
    { kind: 'paragraph', text: 'Xu Kai objected to the Heshan journey at seven separate stages.' },
    { kind: 'paragraph', text: 'He objected when Lu Chen filed the travel order.' },
    { kind: 'paragraph', text: 'He objected when Jian Yue packed provisions.' },
    { kind: 'paragraph', text: 'He objected when Lin Shuying arrived with diplomatic papers authorizing herself as a Liangbei observer.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Why are you here?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lin Shuying', text: 'The forged dossier implicated Liangbei.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Lu Chen could have sent you a report.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Lin Shuying', text: 'I was told that already.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Several times, I imagine.', accent: 'primary' },
    { kind: 'paragraph', text: 'Jian Yue adjusted the strap on her travel bag with unnecessary force.' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'If we leave now, we can reach River Post by evening.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'If we do not leave now, we can remain somewhere with restaurants.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Move.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Oppression has become very organized.', accent: 'primary' },
    { kind: 'break', label: 'Second day' },
    { kind: 'paragraph', text: 'The western road narrowed as the land climbed.' },
    { kind: 'paragraph', text: 'Terraced farms gave way to broken hills and villages built around old flood lines.' },
    { kind: 'paragraph', text: 'Xu Kai stopped complaining about the road.' },
    { kind: 'paragraph', text: 'Jian Yue noticed first.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You are quiet.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I am conserving excellence.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'That was weak.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Long road.', accent: 'primary' },
    { kind: 'paragraph', text: 'She let him have the excuse.' },
    { kind: 'paragraph', text: 'At River Post, the innkeeper recognized Jian Yue and immediately tried to give them the entire upper floor.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Four rooms are enough.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Innkeeper', text: 'Of course, Lady Jian. One for you, one for Lord Lu, one for Lady Lin, and one for your husband.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Silence.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Efficient.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'He is not my husband.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Lin Shuying', text: 'The denial grows faster every time.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You are a foreign guest. Behave like one.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Lin Shuying', text: 'Diplomatically?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Quietly.', accent: 'secondary' },
    { kind: 'paragraph', text: 'Lu Chen accepted his room key and left before becoming evidence.' },
    { kind: 'break', label: 'Night' },
    { kind: 'paragraph', text: 'Xu Kai sat alone behind the inn with a bowl of untouched noodles.' },
    { kind: 'paragraph', text: 'Jian Yue found him there.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Too much salt?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Not enough personality.', accent: 'primary' },
    { kind: 'paragraph', text: 'She sat beside him.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'We can turn back.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Lu Chen would develop a facial expression.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'I am serious.', accent: 'secondary' },
    { kind: 'paragraph', text: 'He looked toward the dark hills.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'So am I.', accent: 'primary' },
    { kind: 'paragraph', text: 'She waited.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'If someone went through this much trouble to point us there, turning back just means they choose the next move.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'That is not why you are going.', accent: 'secondary' },
    { kind: 'paragraph', text: 'Xu Kai smiled without much humor.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You are becoming inconveniently observant.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Supervision requires training.', accent: 'secondary' },
    { kind: 'paragraph', text: 'He looked at her for a long moment.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I want to know why someone remembers Heshan better than the state does.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Then we find out.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'We?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Do not make me explain this again.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Oi.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'What?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Nothing.', accent: 'primary' },
    { kind: 'paragraph', text: 'She stayed until he finally ate the noodles.' },
  ],
};

const chapter31: Chapter = {
  id: 's01-c31',
  season: 1,
  number: 31,
  title: 'The House That Burned Twice',
  summary: 'The Heshan Relief House is mostly ruins. Someone searched those ruins days before Xu Kai arrived, and apparently decided one fire was not enough.',
  readingMinutes: 11,
  tags: ['heshan', 'relief-house', 'investigation', 'mystery', 'xu-kai'],
  segments: [
    { kind: 'paragraph', text: 'Heshan Relief House had once been three buildings around a stone courtyard.' },
    { kind: 'paragraph', text: 'Seven years later, it was one wall, half a kitchen, and a pear tree growing through what had been the registry room.' },
    { kind: 'paragraph', text: 'Xu Kai stopped at the gate.' },
    { kind: 'dialogue', speaker: 'Lin Shuying', text: 'This was it?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'It had more roof.', accent: 'primary' },
    { kind: 'paragraph', text: 'Lu Chen crouched beside the road.' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Recent cart tracks.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'How recent?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'After the last rain. Three days, perhaps four.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Our anonymous friend has terrible manners.', accent: 'primary' },
    { kind: 'paragraph', text: 'They entered the courtyard.' },
    { kind: 'paragraph', text: 'The registry room had burned twice.' },
    { kind: 'paragraph', text: 'The first fire had blackened the stone seven years ago.' },
    { kind: 'paragraph', text: 'The second had been small, recent, and concentrated beneath a collapsed shelf.' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Someone burned something here this week.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'After searching first.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'How do you know?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Because the stones were moved before the ash fell.', accent: 'primary' },
    { kind: 'paragraph', text: 'He pointed at pale rectangles beneath several blocks.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Someone lifted them, found what they wanted or did not, then tried to erase the search.', accent: 'primary' },
    { kind: 'paragraph', text: 'Lin Shuying walked toward the kitchen ruin.' },
    { kind: 'dialogue', speaker: 'Lin Shuying', text: 'What would survive two fires and seven years?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Stone. Metal. Bad decisions.', accent: 'primary' },
    { kind: 'paragraph', text: 'Jian Yue watched him move through the courtyard.' },
    { kind: 'paragraph', text: 'He knew where the well had been before he saw it.' },
    { kind: 'paragraph', text: 'He stepped around a foundation pit without looking down.' },
    { kind: 'paragraph', text: 'At the kitchen threshold, he paused.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You remember everything.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'No.', accent: 'primary' },
    { kind: 'paragraph', text: 'He looked at the pear tree.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Enough.', accent: 'primary' },
    { kind: 'break', label: 'The village below' },
    { kind: 'paragraph', text: 'Only twelve families still lived near the old relief road.' },
    { kind: 'paragraph', text: 'Most remembered the fire.' },
    { kind: 'paragraph', text: 'None remembered nine people leaving together.' },
    { kind: 'dialogue', speaker: 'Old Farmer', text: 'People came and went every week after the flood years. Nobody counted properly.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Did you know Registrar Sun Jiao?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Old Farmer', text: 'City man. Came after the fire with forms and a cough.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Still smoked reed tobacco?', accent: 'primary' },
    { kind: 'paragraph', text: 'The farmer looked at him.' },
    { kind: 'dialogue', speaker: 'Old Farmer', text: 'You knew him.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'He smelled like a wet chimney.', accent: 'primary' },
    { kind: 'paragraph', text: 'The farmer laughed.' },
    { kind: 'dialogue', speaker: 'Old Farmer', text: 'Then you knew him.', accent: 'neutral' },
    { kind: 'paragraph', text: 'A woman sweeping the shrine steps had been listening.' },
    { kind: 'paragraph', text: 'She was very old, very small, and held the broom like a weapon against untidiness.' },
    { kind: 'dialogue', speaker: 'Old Woman', text: 'Turn around.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'That sounds ominous.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Old Woman', text: 'Turn around, boy.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Xu Kai turned.' },
    { kind: 'paragraph', text: 'The old woman stared at his face.' },
    { kind: 'paragraph', text: 'Then she hit him on the arm with the broom.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Ow.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Do not touch him.', accent: 'secondary' },
    { kind: 'paragraph', text: 'Jian Yue had moved before thinking.' },
    { kind: 'paragraph', text: 'The old woman looked at National Tier #2 with complete indifference.' },
    { kind: 'dialogue', speaker: 'Old Woman', text: 'He deserved it seven years ago.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Xu Kai stared.' },
    { kind: 'dialogue', speaker: 'Old Woman', text: 'You still tilt your head when you are pretending not to know something.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Auntie Lan?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Auntie Lan', text: 'Finally.', accent: 'neutral' },
    { kind: 'paragraph', text: 'She hit him again.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Oi. Protect your civilian.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'I am reconsidering.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Auntie Lan', text: 'Good girl.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Jian Yue, feared across three provinces, did not know how to respond to being called a good girl by a woman with a broom.' },
  ],
};

const chapter32: Chapter = {
  id: 's01-c32',
  season: 1,
  number: 32,
  title: 'The Boy Who Counted Bowls',
  summary: 'Auntie Lan remembers Xu Kai before the state did. Unfortunately for him, she remembers everything embarrassing first.',
  readingMinutes: 11,
  tags: ['heshan', 'backstory', 'auntie-lan', 'jian-yue', 'wit'],
  segments: [
    { kind: 'paragraph', text: 'Auntie Lan fed them because interrogation, according to her, was irresponsible on an empty stomach.' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'You worked at the Relief House?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Auntie Lan', text: 'Cooked there twelve years. Which is longer than this one ever washed a bowl willingly.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I had other talents.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Auntie Lan', text: 'Talking.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'That has not changed.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Auntie Lan', text: 'You are the sword girl?', accent: 'neutral' },
    { kind: 'paragraph', text: 'Jian Yue paused.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'National Tier #2.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Auntie Lan', text: 'Good. Make him wash bowls.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'This investigation has become abusive.', accent: 'primary' },
    { kind: 'paragraph', text: 'Lin Shuying was openly enjoying herself.' },
    { kind: 'dialogue', speaker: 'Lin Shuying', text: 'What was he like?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Why do you need to know?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Lin Shuying', text: 'Historical research.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'I also need to know.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You are allowed.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Lin Shuying', text: 'Fascinating distinction.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I am sitting here.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Auntie Lan', text: 'He was skinny.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Strong opening.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Auntie Lan', text: 'Nosy. Always counting things. Bowls, sacks, candles, people.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Why?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Auntie Lan', text: 'Because if the numbers were wrong, he could not sleep.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Xu Kai looked offended by the accuracy.' },
    { kind: 'dialogue', speaker: 'Auntie Lan', text: 'One winter, rice kept disappearing. Steward blamed the displaced families.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'He was an unpleasant man.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Auntie Lan', text: 'You counted breakfast bowls for three days.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Lin Shuying', text: 'Of course he did.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Auntie Lan', text: 'Then he asked why we were feeding one hundred twelve people but ordering lamp oil for one hundred thirty rooms.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'The storeroom workers were stealing rice and hiding it in unused rooms.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Auntie Lan', text: 'See? Sword girl is smart.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Jian Yue looked absurdly pleased for half a second.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I solve one national crisis and receive less praise than that.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Wash more bowls.', accent: 'secondary' },
    { kind: 'paragraph', text: 'Lu Chen opened his notebook.' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Was he called Xu Kai then?', accent: 'neutral' },
    { kind: 'paragraph', text: 'Auntie Lan stopped smiling.' },
    { kind: 'dialogue', speaker: 'Auntie Lan', text: 'He called himself Kai.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Family name?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Auntie Lan', text: 'None that he gave us.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Jian Yue looked at Xu Kai.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'That is true.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'So Xu was added seven years ago.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Yes.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lin Shuying', text: 'Why Xu?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'It was short.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Auntie Lan', text: 'Liar.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Everyone turned.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Auntie.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Auntie Lan', text: 'You picked Xu because Doctor Xu treated children for free after the flood.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Xu Kai looked down at his soup.' },
    { kind: 'dialogue', speaker: 'Auntie Lan', text: 'You said if the state demanded a family name, you would borrow one from someone worth remembering.', accent: 'neutral' },
    { kind: 'paragraph', text: 'The room became very quiet.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I was younger and more dramatic.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You are still dramatic.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Cruel.', accent: 'primary' },
    { kind: 'break', label: 'The fire' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'What happened the night the Relief House burned?', accent: 'neutral' },
    { kind: 'paragraph', text: 'Auntie Lan set down her chopsticks.' },
    { kind: 'dialogue', speaker: 'Auntie Lan', text: 'Officially? Kitchen accident.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'It was not.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Auntie Lan', text: 'No.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'How do you know?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Auntie Lan', text: 'Because the kitchen was the last building to catch.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Where did it start?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Auntie Lan', text: 'Registry room.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Xu Kai closed his eyes briefly.' },
    { kind: 'dialogue', speaker: 'Auntie Lan', text: 'And because three days before the fire, this boy told me someone was stealing relief grain.', accent: 'neutral' },
  ],
};

const chapter33: Chapter = {
  id: 's01-c33',
  season: 1,
  number: 33,
  title: 'Small Greed, Old Ash',
  summary: 'The Heshan fire was never about Xu Kai. It was about grain, missing relief money, and an official who discovered that burning paper was easier than answering questions.',
  readingMinutes: 11,
  tags: ['heshan', 'corruption', 'backstory', 'lu-chen', 'investigation'],
  segments: [
    { kind: 'paragraph', text: 'Auntie Lan remembered the missing grain because hungry people remember arithmetic.' },
    { kind: 'dialogue', speaker: 'Auntie Lan', text: 'Three wagons every month came short.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'How short?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Auntie Lan', text: 'Enough that we watered porridge by the end of winter.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'The invoices said full delivery.', accent: 'primary' },
    { kind: 'paragraph', text: 'Lu Chen looked at him.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I remember.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'You investigated it?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Investigated sounds official. I annoyed people until numbers stopped lying.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'How old were you?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Old enough to be irritating.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Auntie Lan', text: 'He was born that age.', accent: 'neutral' },
    { kind: 'paragraph', text: 'The missing grain led to missing cloth.' },
    { kind: 'paragraph', text: 'Missing cloth led to medicine invoices for remedies that never arrived.' },
    { kind: 'paragraph', text: 'The Relief House was not losing supplies randomly.' },
    { kind: 'paragraph', text: 'Someone had built a business out of disaster relief.' },
    { kind: 'dialogue', speaker: 'Lin Shuying', text: 'Who controlled procurement?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Auntie Lan', text: 'Provincial Relief Office.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Who headed it?', accent: 'neutral' },
    { kind: 'paragraph', text: 'Auntie Lan looked at Xu Kai.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Gao Wen.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Vice Minister Gao Wen?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'He has improved his title.', accent: 'primary' },
    { kind: 'paragraph', text: 'Lu Chen did not write for several seconds.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'He sits on the Imperial Finance Council.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Lin Shuying', text: 'That is inconvenient.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Corruption often promotes well.', accent: 'primary' },
    { kind: 'paragraph', text: 'Seven years ago, Xu Kai had found duplicate grain receipts carrying three warehouse marks that never appeared on delivery carts.' },
    { kind: 'paragraph', text: 'He had shown them to the Relief House steward.' },
    { kind: 'paragraph', text: 'The steward had told him not to ask adult questions.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I took that poorly.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Auntie Lan', text: 'You copied every receipt.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Of course he did.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I feel judged by people who benefit from my habits.', accent: 'primary' },
    { kind: 'paragraph', text: 'Three nights later, the registry room burned.' },
    { kind: 'paragraph', text: 'The copied receipts were inside.' },
    { kind: 'paragraph', text: 'So were displacement rolls, donation ledgers, and several years of procurement records.' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Deaths?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Auntie Lan', text: 'Four.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Xu Kai looked at the table.' },
    { kind: 'dialogue', speaker: 'Auntie Lan', text: 'Could have been forty if Kai had not smelled lamp oil near the registry stairs.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You warned people.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I shouted that the roof was on fire.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Auntie Lan', text: 'The roof was not on fire yet.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Specificity wastes evacuation time.', accent: 'primary' },
    { kind: 'paragraph', text: 'Jian Yue stared at him.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'What?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Nothing.', accent: 'secondary' },
    { kind: 'paragraph', text: 'It was not nothing, but she let him keep it.' },
    { kind: 'break', label: 'Back at the ruins' },
    { kind: 'paragraph', text: 'They returned to the registry room before sunset.' },
    { kind: 'paragraph', text: 'Xu Kai stood where the old shelves had been.' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'If the receipts burned, why point us here now?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Because someone thinks something survived.', accent: 'primary' },
    { kind: 'paragraph', text: 'He looked at the pear tree growing through the floor.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Or because they know it did.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You hid something.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I was irritating, not suicidal.', accent: 'primary' },
    { kind: 'paragraph', text: 'He walked to the old well.' },
    { kind: 'paragraph', text: 'Halfway down its stone lining was a narrow gap filled with mortar.' },
    { kind: 'paragraph', text: 'Fresh mortar.' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Someone opened this recently.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Yes.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lin Shuying', text: 'What was inside?', accent: 'neutral' },
    { kind: 'paragraph', text: 'A voice answered from behind them.' },
    { kind: 'dialogue', speaker: 'Unknown Woman', text: 'Not what he thinks.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Jian Yue turned.' },
    { kind: 'paragraph', text: 'A woman in a travelling archivist\'s coat stood beneath the broken gate.' },
    { kind: 'dialogue', speaker: 'Unknown Woman', text: 'Hello, Kai.', accent: 'neutral' },
  ],
};

const chapter34: Chapter = {
  id: 's01-c34',
  season: 1,
  number: 34,
  title: 'The First Page Was a Receipt',
  summary: 'The person behind the Heshan trail finally steps forward. She is not trying to prove Xu Kai is a spy. She is trying to make the country look at what it buried with the Relief House.',
  readingMinutes: 12,
  tags: ['heshan', 'reveal', 'mei-rong', 'gao-wen', 'politics'],
  segments: [
    { kind: 'paragraph', text: 'The archivist called herself Mei Rong.' },
    { kind: 'paragraph', text: 'Lu Chen already knew the name.' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Imperial Archive restoration division.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Mei Rong', text: 'Third desk, eastern stacks.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You donated the Heshan census book.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Mei Rong', text: 'Yes.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Lin Shuying', text: 'And forged a Liangbei personnel record.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Mei Rong', text: 'Yes.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Jian Yue took one step forward.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You tried to frame him as a foreign agent.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Mei Rong', text: 'I made the frame weak enough to break.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'That is your defense?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Mei Rong', text: 'It broke.', accent: 'neutral' },
    { kind: 'paragraph', text: 'The air around Jian Yue acquired the quality of an approaching storm.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Oi.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'What?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Questions first.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'I have a question involving a wall.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Administrative questions first.', accent: 'primary' },
    { kind: 'paragraph', text: 'She folded her arms.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Fine.', accent: 'secondary' },
    { kind: 'paragraph', text: 'Mei Rong looked at Xu Kai.' },
    { kind: 'dialogue', speaker: 'Mei Rong', text: 'You do not remember me.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I remember a girl who copied donation ledgers for the Relief House.', accent: 'primary' },
    { kind: 'paragraph', text: 'Her expression changed.' },
    { kind: 'dialogue', speaker: 'Mei Rong', text: 'You remember too much.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'A recurring complaint.', accent: 'primary' },
    { kind: 'paragraph', text: 'Mei Rong had been seventeen when the Relief House burned.' },
    { kind: 'paragraph', text: 'Afterward Sun Jiao gave her a legal identity too.' },
    { kind: 'paragraph', text: 'One of the eight names in his audit ledger belonged to her.' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'So the nine identities were not one organization.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Mei Rong', text: 'We were people whose papers burned, flooded, or never existed. Sun Jiao made the bureaucracy admit we were alive.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'For a fee.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Mei Rong', text: 'For the filing fees. He kept almost none of it.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Xu Kai looked mildly betrayed by a dead corrupt registrar becoming morally complicated.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'That is inconvenient to my memory of him.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Mei Rong', text: 'He still smoked too much.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Balance restored.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Why construct this trail now?', accent: 'neutral' },
    { kind: 'paragraph', text: 'Mei Rong opened her satchel.' },
    { kind: 'paragraph', text: 'Inside was a scorched metal document tube.' },
    { kind: 'dialogue', speaker: 'Mei Rong', text: 'Because I found this six months ago in a private archive sale.', accent: 'neutral' },
    { kind: 'paragraph', text: 'She handed it to Xu Kai.' },
    { kind: 'paragraph', text: 'He opened it carefully.' },
    { kind: 'paragraph', text: 'Inside were three charred strips of paper and one nearly intact receipt.' },
    { kind: 'dialogue', speaker: 'Lin Shuying', text: 'The first page.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Mei Rong', text: 'Not a census page. A procurement receipt.', accent: 'neutral' },
    { kind: 'paragraph', text: 'The receipt documented six hundred sacks of winter grain purchased for Heshan Relief House.' },
    { kind: 'paragraph', text: 'Only four hundred had ever arrived.' },
    { kind: 'paragraph', text: 'The receiving seal belonged to Gao Wen.' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'This is evidence of theft, not arson.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Mei Rong', text: 'Read the reverse.', accent: 'neutral' },
    { kind: 'paragraph', text: 'On the back, in faded ink, someone had listed three duplicated invoices and a date.' },
    { kind: 'paragraph', text: 'The date was two days before the fire.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'My handwriting.', accent: 'primary' },
    { kind: 'paragraph', text: 'Jian Yue looked at him.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I copied the numbers wherever I could.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Mei Rong', text: 'You gave this to the registry steward. He hid it in the well before the fire reached the room.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'How did it leave Heshan?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Mei Rong', text: 'Someone removed it afterward. I do not know who.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Why not bring it directly to the Ministry?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Mei Rong', text: 'Because Gao Wen is Vice Minister of Revenue, sits on the Finance Council, and has spent seven years deciding which records survive audits.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Silence settled over the ruins.' },
    { kind: 'dialogue', speaker: 'Mei Rong', text: 'A clerk accusing him disappears into procedure. A damaged receipt becomes inconclusive. But the civilian who embarrassed ministers, stopped a war, and somehow collected the attention of the Five Pillars?', accent: 'neutral' },
    { kind: 'paragraph', text: 'She looked at Xu Kai.' },
    { kind: 'dialogue', speaker: 'Mei Rong', text: 'You are difficult to ignore.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You framed me as a foreign spy because I am annoying.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Mei Rong', text: 'When you say it that way, it sounds ungrateful.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'It sounds insane.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I object to her methods.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Finally.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'But strategically...', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'No.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Lin Shuying', text: 'I would also like to hear this.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'No.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Unfortunately, I understand what she did.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'I hate all of you.', accent: 'secondary' },
    { kind: 'break', label: 'The name' },
    { kind: 'paragraph', text: 'Lu Chen sealed the receipt in an evidence sleeve.' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'One question remains.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Only one? Excellent progress.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Xu Kai is not your birth name.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Jian Yue looked at him.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'No.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lin Shuying', text: 'What was it?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I do not know.', accent: 'primary' },
    { kind: 'paragraph', text: 'No joke followed.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I was already without papers when I reached Heshan. Kai was the name I used. Xu was the name I chose later.', accent: 'primary' },
    { kind: 'paragraph', text: 'Jian Yue was quiet for a moment.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Then Xu Kai is your name.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'That simple?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You chose it. You answer to it. You annoy me with it. Sounds established.', accent: 'secondary' },
    { kind: 'paragraph', text: 'Xu Kai looked at her.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Oi.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Do not ruin the moment.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Too late.', accent: 'primary' },
    { kind: 'break', label: 'The capital answers' },
    { kind: 'paragraph', text: 'A Ministry courier reached Heshan before sunset.' },
    { kind: 'paragraph', text: 'He carried an order signed by the Imperial Finance Council.' },
    { kind: 'paragraph', text: 'All evidence relating to Heshan procurement was to be surrendered immediately to Vice Minister Gao Wen for internal review.' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'He knows.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Good.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Good?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'We were wondering who would move first.', accent: 'primary' },
    { kind: 'paragraph', text: 'His smile returned.' },
    { kind: 'paragraph', text: 'Jian Yue recognized that smile now.' },
    { kind: 'paragraph', text: 'It was the smile Xu Kai wore when someone had just made the mistake of becoming predictable.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Now we know.', accent: 'primary' },
  ],
};

const newChapters = [chapter30, chapter31, chapter32, chapter33, chapter34];

export const seasons: Season[] = baseSeasons.map((season) => {
  if (season.number !== 1) {
    return season;
  }

  return {
    ...season,
    subtitle: 'A dangerous civilian acquires a National-Tier supervisor and accidentally becomes a national policy problem.',
    description: 'Xu Kai solves crises through observation, manipulation, economics, social engineering, and shameless conversation while Jian Yue, National Tier #2, insists that following him everywhere is merely responsible supervision.',
    chapters: [...season.chapters, ...newChapters],
  };
});
