import type { Chapter, Season } from '../domain/types';
import { seasons as baseSeasons } from './story-v4';

const chapter20: Chapter = {
  id: 's01-c20',
  season: 1,
  number: 20,
  title: 'The War Everyone Had Already Ordered',
  summary: 'Both borders mobilize after the Willow Pass attack. Xu Kai notices that some commanders reacted too quickly to news they supposedly had not received yet.',
  readingMinutes: 11,
  tags: ['frontier', 'war', 'yan-shuo', 'strategy', 'mystery'],
  segments: [
    { kind: 'paragraph', text: 'By midnight, Fort Shanyin had received seven military orders, four contradictory reports, and one request from the capital asking everyone to remain calm.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'The request is my favorite.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'Why?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Because it arrived after three mobilization orders.', accent: 'primary' },
    { kind: 'paragraph', text: 'Yan Shuo stood over the command table in partial armor.' },
    { kind: 'paragraph', text: 'Three red markers showed eastern regiments moving toward Willow Pass.' },
    { kind: 'paragraph', text: 'Across the border, Liangbei signal fires burned on two ridges.' },
    { kind: 'dialogue', speaker: 'General Pei', text: 'They are mobilizing faster than we are.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'General Rong', text: 'Then we should stop discussing it and move.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Wonderful. Let us race into a war and give a prize to whoever understands least.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'General Rong', text: 'Civilian, men were attacked.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Which is why I am interested in the people who knew before they were.', accent: 'primary' },
    { kind: 'paragraph', text: 'The room went quiet.' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'Explain.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Show me the first mobilization order.', accent: 'primary' },
    { kind: 'paragraph', text: 'A clerk handed it over.' },
    { kind: 'paragraph', text: 'The order had been issued by East Garrison Command at the third evening bell.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'When did the wounded scouts reach us?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'General Ma', text: 'Fourth bell and two quarters.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'How long from Willow Pass to East Garrison by fast horse?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'General Pei', text: 'An hour. Less if the road is clear.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Then East Garrison mobilized before anyone there could have learned about the attack.', accent: 'primary' },
    { kind: 'paragraph', text: 'Yan Shuo took the order from him.' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'Could be a copied time mark.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Could be.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You do not think so.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I think mistakes are usually untidy. This is convenient.', accent: 'primary' },
    { kind: 'paragraph', text: 'He asked for every order issued that evening.' },
    { kind: 'paragraph', text: 'Two had been written early.' },
    { kind: 'paragraph', text: 'One requested extra arrows before the attack.' },
    { kind: 'paragraph', text: 'Another instructed a river post to prepare casualty wagons.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'They expected fighting.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'Or planned it.', accent: 'neutral' },
    { kind: 'paragraph', text: 'General Rong pushed away from the table.' },
    { kind: 'dialogue', speaker: 'General Rong', text: 'Then arrest East Garrison Command.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'For being too punctual?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'General Rong', text: 'For treason.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You have skipped several useful nouns between those sentences.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'He is right.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Everyone looked at Yan Shuo.' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'Do not make me repeat it.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I am writing down the date.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Do not provoke him while he is learning.', accent: 'secondary' },
    { kind: 'paragraph', text: 'A courier arrived from East Garrison before dawn.' },
    { kind: 'paragraph', text: 'The commander there denied issuing the mobilization order.' },
    { kind: 'paragraph', text: 'His seal had been copied.' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'So someone forged military orders.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'And knew which officers would obey before verifying.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'The same pattern as White Bridge.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Not the same people necessarily. Same kind of thinking.', accent: 'primary' },
    { kind: 'paragraph', text: 'Yan Shuo pointed to the border.' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'Liangbei is still mobilizing.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Then they may have received their own helpful paperwork.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'General Pei', text: 'You want to contact them?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I want to ask whether their bureaucracy is also trying to kill them.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'We do not have a diplomatic channel open at Willow Pass.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You have merchants.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'The border markets are closed.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Then smugglers.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'You are recommending illegal communication between states.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I prefer flexible diplomacy.', accent: 'primary' },
    { kind: 'paragraph', text: 'Yan Shuo looked at Jian Yue.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Do not look at me. I am supervising him, not explaining him.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'A distinction without labor.', accent: 'primary' },
    { kind: 'break', label: 'Morning' },
    { kind: 'paragraph', text: 'A black-market tea merchant crossed the border carrying a message sewn into the lining of a tea basket.' },
    { kind: 'paragraph', text: 'Xu Kai paid him double.' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'With whose money?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'The government is investigating national survival. I assumed there was a budget.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'There was not.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'There is now.', accent: 'primary' },
    { kind: 'paragraph', text: 'The reply came before noon.' },
    { kind: 'paragraph', text: 'Liangbei had also suffered an attack.' },
    { kind: 'paragraph', text: 'Their patrol had been struck by men wearing Wuyuan colors.' },
    { kind: 'paragraph', text: 'Their first mobilization order had also been issued before the survivors returned.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Someone is pushing both sides.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'Toward each other.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Finally. A war with symmetry.', accent: 'primary' },
    { kind: 'paragraph', text: 'The message contained one additional line.' },
    { kind: 'paragraph', text: 'Liangbei proposed a secret meeting before sunset.' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'Trap.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Possibly.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You want to go.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'There may be dinner.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Absolutely not alone.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'There is the supervision.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'I am also coming.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'This is becoming less secret by the minute.', accent: 'primary' },
  ],
};

const chapter21: Chapter = {
  id: 's01-c21',
  season: 1,
  number: 21,
  title: 'Oi Has a Name',
  summary: 'Before the secret border meeting, Jian Yue wants the safe plan. Xu Kai wants the useful one. For once, he uses her actual name.',
  readingMinutes: 9,
  tags: ['romance', 'jian-yue', 'xu-kai', 'trust', 'frontier'],
  segments: [
    { kind: 'paragraph', text: 'The meeting place was an abandoned customs house built directly over a dry streambed between the two borders.' },
    { kind: 'paragraph', text: 'Yan Shuo disliked it immediately.' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'Three approaches. Too many windows. High ground on both sides.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You make architecture sound judgmental.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'Architecture gets people killed.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'He is right.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'This trip has damaged both of you.', accent: 'primary' },
    { kind: 'paragraph', text: 'Jian Yue ignored him and inspected the rear door.' },
    { kind: 'paragraph', text: 'She had been quiet since reading the Liangbei reply.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Oi.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'No.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You do not know what I was going to say.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You are going to suggest something unsafe with a cheerful expression.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'That is unfairly specific.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'I have experience.', accent: 'secondary' },
    { kind: 'paragraph', text: 'He held up the reply.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Their envoy asked for three representatives. They expect Yan Shuo, a diplomat, and an intelligence officer.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'They are getting two National Tiers and you.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'A terrible bargain.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You are not sitting nearest the door.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Why?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Because the first person through that door reaches you first.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Concern.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Geometry.', accent: 'secondary' },
    { kind: 'paragraph', text: 'Yan Shuo walked outside before the conversation could worsen.' },
    { kind: 'paragraph', text: 'Jian Yue lowered her voice.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'This is different from the capital.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'The food is worse.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Xu Kai.', accent: 'secondary' },
    { kind: 'paragraph', text: 'He stopped joking.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'If this is a trap, there may be National-Tier equivalents on the other side. If fighting starts, I cannot guarantee I can protect you and support Yan Shuo at the same time.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Then do not protect me.', accent: 'primary' },
    { kind: 'paragraph', text: 'Her expression hardened.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'No.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Oi—', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'No.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You have made that word tyrannical.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Good.', accent: 'secondary' },
    { kind: 'paragraph', text: 'He watched her for a moment.' },
    { kind: 'paragraph', text: 'Then his tone changed.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Jian Yue.', accent: 'primary' },
    { kind: 'paragraph', text: 'She went completely still.' },
    { kind: 'paragraph', text: 'It was absurd that hearing her own name from him felt more dangerous than the border.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'What?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'If something happens, protect the room. Protect the negotiation. Do not abandon the reason we came because someone points a blade at me.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You are part of the reason we came.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Unfortunately.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'I am serious.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'So am I.', accent: 'primary' },
    { kind: 'paragraph', text: 'That made her angrier than a joke would have.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You ask people to trust your plans while telling them not to care what happens to you.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Those are separate issues.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Not to me.', accent: 'secondary' },
    { kind: 'paragraph', text: 'Silence.' },
    { kind: 'paragraph', text: 'Xu Kai looked briefly surprised.' },
    { kind: 'paragraph', text: 'Jian Yue realized what she had said.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Because you are a state security concern.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'There it is.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Do not.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I said nothing.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Your face did.', accent: 'secondary' },
    { kind: 'paragraph', text: 'He smiled, but softer this time.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Fine. Compromise.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'What compromise?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You protect the negotiation first.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'And?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'And I will make an effort not to be stabbed.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'That is a terrible compromise.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You accepted it slowly enough that it became binding.', accent: 'primary' },
    { kind: 'paragraph', text: 'She stepped closer and straightened his collar with unnecessary force.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'If you die, I will kill you.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Logistically difficult.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'I am National Tier.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Fair.', accent: 'primary' },
    { kind: 'paragraph', text: 'She released his collar.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Oi.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'What?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You look nervous.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'I was happier when you used my name.', accent: 'secondary' },
    { kind: 'paragraph', text: 'Xu Kai laughed.' },
    { kind: 'paragraph', text: 'Her ears turned red.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Forget I said that.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Impossible.', accent: 'primary' },
  ],
};

const chapter22: Chapter = {
  id: 's01-c22',
  season: 1,
  number: 22,
  title: 'Dinner with the Enemy',
  summary: 'Wuyuan and Liangbei meet in an abandoned customs house. The food is poor, the accusations are excellent, and Xu Kai discovers both countries have been lied to in almost identical handwriting.',
  readingMinutes: 12,
  tags: ['diplomacy', 'liangbei', 'banter', 'jian-yue', 'yan-shuo'],
  segments: [
    { kind: 'paragraph', text: 'Liangbei arrived with exactly three representatives.' },
    { kind: 'paragraph', text: 'General Mu Qiao commanded their western border.' },
    { kind: 'paragraph', text: 'Lady Lin Shuying represented the Liangbei court.' },
    { kind: 'paragraph', text: 'The third man introduced himself only as Mister Fan and looked like the sort of person Lu Chen would dislike professionally.' },
    { kind: 'dialogue', speaker: 'Lin Shuying', text: 'Which of you is Xu Kai?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'That depends why you are asking.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lin Shuying', text: 'I was told the dangerous one was a civilian.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Slander travels quickly.', accent: 'primary' },
    { kind: 'paragraph', text: 'Lin Shuying smiled.' },
    { kind: 'paragraph', text: 'Jian Yue did not.' },
    { kind: 'dialogue', speaker: 'Lin Shuying', text: 'And Lady Jian Yue. I have wanted to meet you for years.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Why?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Lin Shuying', text: 'You are exactly as warm as the reports.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'The reports were optimistic.', accent: 'primary' },
    { kind: 'paragraph', text: 'Jian Yue stepped on his foot.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Ow.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lin Shuying', text: 'Oh.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'There is no oh.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Lin Shuying', text: 'I did not say what the oh meant.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You were going to.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'Can we prevent a war before starting another one at this table?', accent: 'neutral' },
    { kind: 'break', label: 'First course' },
    { kind: 'paragraph', text: 'The customs-house cook served a stew that united both nations in suspicion.' },
    { kind: 'dialogue', speaker: 'Mu Qiao', text: 'Your soldiers attacked ours at Heshan Ridge.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'Your soldiers attacked ours at Willow Pass.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Mu Qiao', text: 'We lost four men.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'We lost two.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Excellent. We have established that corpses are poor diplomats.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Mu Qiao', text: 'Is he always like this?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Worse when rested.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Lin Shuying', text: 'I find it refreshing.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Jian Yue drank water.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Oi, are you thirsty?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Very.', accent: 'secondary' },
    { kind: 'paragraph', text: 'Yan Shuo decided not to ask.' },
    { kind: 'paragraph', text: 'Both sides laid their evidence on the table.' },
    { kind: 'paragraph', text: 'Wuyuan had a Liangbei-colored sash taken from Willow Pass.' },
    { kind: 'paragraph', text: 'Liangbei had a Wuyuan military cloak taken from Heshan Ridge.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Beautiful.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Mu Qiao', text: 'Beautiful?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Perfectly incriminating objects left by attackers who otherwise avoided identification.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Mister Fan', text: 'You believe both were planted.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You do too.', accent: 'primary' },
    { kind: 'paragraph', text: 'Mister Fan smiled faintly.' },
    { kind: 'dialogue', speaker: 'Mister Fan', text: 'Why?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Because you have spent the entire meal watching our papers, not our weapons.', accent: 'primary' },
    { kind: 'paragraph', text: 'Lu Chen would have enjoyed the silence that followed.' },
    { kind: 'dialogue', speaker: 'Mister Fan', text: 'Our first mobilization order was forged.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'So was ours.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Lin Shuying', text: 'Our grain inspectors found false military sacks in two border markets.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'South-valley millet?', accent: 'primary' },
    { kind: 'paragraph', text: 'Lin Shuying stopped smiling.' },
    { kind: 'dialogue', speaker: 'Lin Shuying', text: 'How did you know?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'A goat.', accent: 'primary' },
    { kind: 'paragraph', text: 'Six people stared at him.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Unfortunately, that is true.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Mu Qiao', text: 'A goat exposed an international provocation?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'It was a competent goat.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Finally, respect.', accent: 'primary' },
    { kind: 'paragraph', text: 'Lin Shuying produced copies of three Liangbei orders.' },
    { kind: 'paragraph', text: 'Xu Kai placed the Wuyuan forgeries beside them.' },
    { kind: 'paragraph', text: 'The scripts differed.' },
    { kind: 'paragraph', text: 'The bureaucratic habits did not.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Same spacing before unit counts.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Mister Fan', text: 'Same way of abbreviating reserve companies.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Same mistake with road-distance notation.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Mister Fan', text: 'One planner.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Or one training source.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lin Shuying', text: 'Someone familiar with both military systems.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'That narrows the list poorly.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Then narrow by motive.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Mu Qiao', text: 'Who benefits from war?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Almost everyone who does not have to fight it.', accent: 'primary' },
    { kind: 'paragraph', text: 'The room went quiet again.' },
    { kind: 'break', label: 'Second course' },
    { kind: 'paragraph', text: 'Lin Shuying leaned toward Xu Kai while Yan Shuo and Mu Qiao compared patrol maps.' },
    { kind: 'dialogue', speaker: 'Lin Shuying', text: 'Are you attached to Wuyuan service?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Against my better judgment.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lin Shuying', text: 'Liangbei pays advisers well.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'No.', accent: 'secondary' },
    { kind: 'paragraph', text: 'Lin Shuying looked at her.' },
    { kind: 'dialogue', speaker: 'Lin Shuying', text: 'I asked him.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'I answered.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Efficient government.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lin Shuying', text: 'Is she your superior?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'She thinks so.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'I am your supervisor.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Lin Shuying', text: 'Ah.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Again, there is no ah.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Lin Shuying', text: 'This border meeting is educational.', accent: 'neutral' },
    { kind: 'paragraph', text: 'A signal arrow rose outside.' },
    { kind: 'paragraph', text: 'Red.' },
    { kind: 'paragraph', text: 'Then a second from the opposite ridge.' },
    { kind: 'paragraph', text: 'Red again.' },
    { kind: 'paragraph', text: 'Yan Shuo and Mu Qiao stood at the same time.' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'Attack signal.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Mu Qiao', text: 'Ours too.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Outside, horns began to sound from both armies.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'There is our dinner entertainment.', accent: 'primary' },
  ],
};

const chapter23: Chapter = {
  id: 's01-c23',
  season: 1,
  number: 23,
  title: 'The War That Lasted Nine Minutes',
  summary: 'Saboteurs trigger attack signals on both sides while the negotiators are isolated. Xu Kai cannot stop two armies with strength, so he attacks the only thing faster than soldiers: certainty.',
  readingMinutes: 12,
  tags: ['war', 'strategy', 'climax', 'jian-yue', 'yan-shuo', 'diplomacy'],
  segments: [
    { kind: 'paragraph', text: 'The first problem was distance.' },
    { kind: 'paragraph', text: 'The Wuyuan army was two ridges west.' },
    { kind: 'paragraph', text: 'The Liangbei army was two ridges east.' },
    { kind: 'paragraph', text: 'The customs house sat between them with six negotiators and no authority anyone could hear over war horns.' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'I am going back.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Mu Qiao', text: 'So am I.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'No.', accent: 'primary' },
    { kind: 'paragraph', text: 'Both generals looked at him.' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'This is not the time.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Exactly. If both of you ride out now, your armies see their commanders racing toward them during attack signals.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lin Shuying', text: 'They will assume the negotiation failed.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'And your arrival becomes confirmation.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Mu Qiao', text: 'Then what do you propose?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Confuse everyone.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'Of course you do.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Xu Kai pointed at the customs signal mast.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Does either army recognize neutral customs flags?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Mister Fan', text: 'Trade halt. Medical emergency. Fire.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Raise all three.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'At once?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'If you cannot give soldiers a clear truth, give them an unclear reason to hesitate.', accent: 'primary' },
    { kind: 'paragraph', text: 'Mister Fan ran for the mast.' },
    { kind: 'paragraph', text: 'Jian Yue moved toward the rear door.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Oi.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Someone fired those arrows.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I know.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'They are close.', accent: 'secondary' },
    { kind: 'paragraph', text: 'He looked at her.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'The room first.', accent: 'primary' },
    { kind: 'paragraph', text: 'She remembered the conversation outside.' },
    { kind: 'paragraph', text: 'Her jaw tightened.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Fine.', accent: 'secondary' },
    { kind: 'paragraph', text: 'She stayed.' },
    { kind: 'break', label: 'Minute two' },
    { kind: 'paragraph', text: 'Three incompatible customs flags climbed the mast.' },
    { kind: 'paragraph', text: 'The nearest Wuyuan horn pattern faltered.' },
    { kind: 'paragraph', text: 'The Liangbei drums hesitated half a beat later.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Good. Now both armies know something is wrong.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Mu Qiao', text: 'They already knew something was wrong.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Now they know their officers may not know what.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lin Shuying', text: 'You weaponize doubt.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Certainty started this.', accent: 'primary' },
    { kind: 'paragraph', text: 'Yan Shuo wrote a six-word order.' },
    { kind: 'paragraph', text: 'HOLD POSITION. VERIFY ALL SIGNAL SOURCES.' },
    { kind: 'paragraph', text: 'Mu Qiao wrote the same in Liangbei script.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Do not send them by horse.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'Why?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Because a lone rider can be stopped.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Mister Fan', text: 'Signal mirrors.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Better.', accent: 'primary' },
    { kind: 'break', label: 'Minute four' },
    { kind: 'paragraph', text: 'Mirrors flashed from the customs roof.' },
    { kind: 'paragraph', text: 'The Wuyuan ridge answered.' },
    { kind: 'paragraph', text: 'The Liangbei ridge did not.' },
    { kind: 'dialogue', speaker: 'Mu Qiao', text: 'Our western signal team is compromised.', accent: 'neutral' },
    { kind: 'paragraph', text: 'A window shattered.' },
    { kind: 'paragraph', text: 'A crossbow bolt buried itself in the table where Lin Shuying had been sitting.' },
    { kind: 'paragraph', text: 'Jian Yue drew her sword.' },
    { kind: 'paragraph', text: 'Mu Qiao moved in front of Lin Shuying.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'That seems rude.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Stay down.', accent: 'secondary' },
    { kind: 'paragraph', text: 'Xu Kai got down.' },
    { kind: 'paragraph', text: 'Not gracefully.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I object to the floor.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Object quietly.', accent: 'secondary' },
    { kind: 'paragraph', text: 'Three saboteurs appeared on the western roofline.' },
    { kind: 'paragraph', text: 'Jian Yue left through the window.' },
    { kind: 'paragraph', text: 'There was no useful way for an ordinary person to follow what happened next.' },
    { kind: 'paragraph', text: 'There was a crimson flash, one broken roof tile, and then two saboteurs were on the ground.' },
    { kind: 'paragraph', text: 'The third fled toward the ridge.' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'I will take him.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Yan Shuo disappeared through the door with considerably less concern for hinges than the architect had intended.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'And people criticize my relationship with furniture.', accent: 'primary' },
    { kind: 'break', label: 'Minute six' },
    { kind: 'paragraph', text: 'Liangbei drums began an advance pattern.' },
    { kind: 'dialogue', speaker: 'Mu Qiao', text: 'My left regiment did not receive the hold order.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Can you send any signal their enemy would also understand?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Mu Qiao', text: 'What?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Something so wrong both sides stop to stare.', accent: 'primary' },
    { kind: 'paragraph', text: 'Mu Qiao thought for one second.' },
    { kind: 'dialogue', speaker: 'Mu Qiao', text: 'Funeral drums.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Lin Shuying', text: 'In battle?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Mu Qiao', text: 'Never.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Perfect.', accent: 'primary' },
    { kind: 'paragraph', text: 'Mister Fan signaled the customs team.' },
    { kind: 'paragraph', text: 'Deep funeral drums rolled across the valley.' },
    { kind: 'paragraph', text: 'The advancing Liangbei formation slowed.' },
    { kind: 'paragraph', text: 'Wuyuan archers lowered bows by instinct, confused by a mourning signal in the middle of an attack order.' },
    { kind: 'dialogue', speaker: 'Lin Shuying', text: 'This is insane.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Thank you.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lin Shuying', text: 'That was not praise.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Too late.', accent: 'primary' },
    { kind: 'break', label: 'Minute eight' },
    { kind: 'paragraph', text: 'The Wuyuan ridge finally mirrored Yan Shuo\'s hold order across the entire line.' },
    { kind: 'paragraph', text: 'Liangbei repeated it thirty heartbeats later.' },
    { kind: 'paragraph', text: 'The war stopped before most soldiers understood it had nearly begun.' },
    { kind: 'paragraph', text: 'Yan Shuo returned dragging the third saboteur by the collar.' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'Caught him.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Very direct.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'I enjoy my methods.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Jian Yue reentered through the broken window.' },
    { kind: 'paragraph', text: 'She had a shallow cut across one sleeve.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You are hurt.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Cloth is hurt.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'The cloth looks expensive.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You stayed down?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I was extremely brave near the floor.', accent: 'primary' },
    { kind: 'paragraph', text: 'She looked him over once anyway.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Supervision?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Inventory.', accent: 'secondary' },
    { kind: 'break', label: 'Minute nine' },
    { kind: 'paragraph', text: 'The final attack horns stopped.' },
    { kind: 'paragraph', text: 'Across two ridges, thousands of soldiers remained alive because for nine minutes nobody had been completely sure what was happening.' },
    { kind: 'dialogue', speaker: 'Mu Qiao', text: 'You stopped a battle by making both armies confused.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Confusion is underrated when the alternative is confidence.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'I hate that this worked.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You will get used to it.', accent: 'secondary' },
    { kind: 'paragraph', text: 'Yan Shuo looked at her.' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'That sounded affectionate.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Do you want to go back outside?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'No witnesses.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Lin Shuying laughed loud enough for both countries.' },
  ],
};

const chapter24: Chapter = {
  id: 's01-c24',
  season: 1,
  number: 24,
  title: 'The Civilian Who Came Home',
  summary: 'The frontier settles, Yan Shuo changes his opinion by a humiliating amount, and Xu Kai returns to the capital expecting peace. Lu Chen has found something instead.',
  readingMinutes: 11,
  tags: ['aftermath', 'capital', 'romance', 'lu-chen', 'mystery'],
  segments: [
    { kind: 'paragraph', text: 'The saboteur talked after discovering that both countries wanted answers and neither intended to let the other conduct the interrogation alone.' },
    { kind: 'paragraph', text: 'He belonged to a private network of military contractors, smugglers, minor officials, and displaced nobles who had spent two years profiting from tension along the frontier.' },
    { kind: 'paragraph', text: 'War would have multiplied their contracts, erased several investigations, and made stolen supply records almost impossible to audit.' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'So thousands nearly died for procurement fraud.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'People prefer grand motives. Small greed is usually better funded.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lin Shuying', text: 'Liangbei will conduct its own arrests.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'Wuyuan will do the same.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Try not to arrest each other.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Mu Qiao', text: 'No promises.', accent: 'neutral' },
    { kind: 'paragraph', text: 'The border markets reopened three days later.' },
    { kind: 'paragraph', text: 'Merchants crossed before diplomats did.' },
    { kind: 'paragraph', text: 'This surprised no merchant.' },
    { kind: 'break', label: 'Departure' },
    { kind: 'paragraph', text: 'Yan Shuo walked Xu Kai and Jian Yue to the western road.' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'I was wrong about you.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'This trip has been full of personal growth.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'Do not make me regret saying it.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Too late.', accent: 'primary' },
    { kind: 'paragraph', text: 'Yan Shuo held out a small bronze token.' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'Eastern command pass. It opens military gates and requisitions transport.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Dangerous thing to give a civilian.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'I know.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Then why?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'Because if the east catches fire again, I would rather you arrive before the paperwork.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Xu Kai looked at the token.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'That may be the nicest insult I have received.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'Good.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Yan Shuo turned to Jian Yue.' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'Keep supervising him.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Obviously.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'My autonomy continues to suffer.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'I understand why she does it now.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Jian Yue narrowed her eyes.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Explain that sentence carefully.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'State security.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Xu Kai laughed all the way to the first hill.' },
    { kind: 'break', label: 'The road home' },
    { kind: 'paragraph', text: 'The return trip took six days.' },
    { kind: 'paragraph', text: 'Jian Yue discovered that Xu Kai slept badly in moving carriages, disliked cold tea, and considered every roadside inn a personal challenge.' },
    { kind: 'paragraph', text: 'Xu Kai discovered that Jian Yue carried emergency medicine, spare coins, two whetstones, dried fruit, and exactly one sweet bun she insisted she had not packed for him.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Then who is it for?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Emergency.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I am experiencing an emergency.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'What emergency?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Lack of sweet bun.', accent: 'primary' },
    { kind: 'paragraph', text: 'She gave it to him.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Remarkable medical response.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Eat quietly.', accent: 'secondary' },
    { kind: 'paragraph', text: 'He ate quietly for almost thirty seconds.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Oi.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Thirty seconds. A new record.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Are you going to miss traveling with me?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'We live next door.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'That was not an answer.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'It was an escape route.', accent: 'secondary' },
    { kind: 'paragraph', text: 'He smiled out the carriage window.' },
    { kind: 'break', label: 'Capital' },
    { kind: 'paragraph', text: 'Lu Chen was waiting inside Xu Kai\'s house when they returned.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I am beginning to question the purpose of doors.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Your lock is inadequate.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'I told him that.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'This is victim blaming.', accent: 'primary' },
    { kind: 'paragraph', text: 'Lu Chen had placed a thin folder on the new table.' },
    { kind: 'paragraph', text: 'The table still looked judgmental.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'What happened?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Nothing.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You broke into my house for nothing?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'I investigated you.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Jian Yue looked at him sharply.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Why?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Because he has been involved in two national security crises in one month and now carries an eastern command pass.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Three crises if you count my furniture.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'I do not.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Coward.', accent: 'primary' },
    { kind: 'paragraph', text: 'Lu Chen opened the folder.' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Your records begin seven years ago.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Xu Kai stopped smiling.' },
    { kind: 'paragraph', text: 'Only for a moment.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Records have to begin somewhere.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Tax record. Residence permit. Apprenticeship registration. All within the same six-week period.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'And before that?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Nothing.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Jian Yue looked at Xu Kai.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I was very poor at paperwork as a child.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'You had no childhood according to the state.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Efficient.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Xu Kai.', accent: 'secondary' },
    { kind: 'paragraph', text: 'He glanced at her.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Is there something I need to know?', accent: 'secondary' },
    { kind: 'paragraph', text: 'The question was careful.' },
    { kind: 'paragraph', text: 'Not suspicious.' },
    { kind: 'paragraph', text: 'That made it harder.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Yes.', accent: 'primary' },
    { kind: 'paragraph', text: 'Lu Chen straightened.' },
    { kind: 'paragraph', text: 'Jian Yue waited.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Your noodles were worse than the frontier stew.', accent: 'primary' },
    { kind: 'paragraph', text: 'Jian Yue stared at him.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'I hate you.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'That sounded relieved.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'It was a threat.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'We are not finished.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I just returned from preventing a war. Can my mysterious bureaucratic childhood wait until breakfast?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'No.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Yes.', accent: 'secondary' },
    { kind: 'paragraph', text: 'Lu Chen looked at her.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'He has not slept properly in six days.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Concern.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Medical fact.', accent: 'secondary' },
    { kind: 'paragraph', text: 'Lu Chen closed the folder.' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Breakfast.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Excellent. Bring dumplings when you invade my privacy tomorrow.', accent: 'primary' },
    { kind: 'paragraph', text: 'Lu Chen left through the door like a normal person, perhaps to make a point.' },
    { kind: 'paragraph', text: 'Jian Yue remained.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You do not have to tell me tonight.', accent: 'secondary' },
    { kind: 'paragraph', text: 'Xu Kai looked at her.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'But do not lie to me when you do.', accent: 'secondary' },
    { kind: 'paragraph', text: 'For once, Xu Kai did not have a joke ready.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'All right.', accent: 'primary' },
    { kind: 'paragraph', text: 'She nodded once and walked to the neighboring door.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Oi.', accent: 'primary' },
    { kind: 'paragraph', text: 'She turned.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'What?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Welcome home.', accent: 'primary' },
    { kind: 'paragraph', text: 'Her expression softened before she could stop it.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Idiot.', accent: 'secondary' },
    { kind: 'paragraph', text: 'She went inside.' },
    { kind: 'paragraph', text: 'Xu Kai stood alone beside the folder Lu Chen had left behind.' },
    { kind: 'paragraph', text: 'On its cover were two words.' },
    { kind: 'paragraph', text: 'IDENTITY: UNVERIFIED.' },
  ],
};

const newChapters = [chapter20, chapter21, chapter22, chapter23, chapter24];

export const seasons: Season[] = baseSeasons.map((season) => {
  if (season.number !== 1) {
    return season;
  }

  return {
    ...season,
    subtitle: 'A dangerous civilian acquires a National-Tier supervisor and accidentally becomes a national policy problem.',
    description: 'Xu Kai solves crises through observation, manipulation, economics, social engineering, and shameless conversation while Jian Yue, National Tier #2, insists that following him everywhere is merely responsible supervision.',
    chapters: [...season.chapters, ...newChapters],
  };
});
