import type { Season } from '../domain/types';

// Starter manuscript only. Replace these chapters with Project G canon.
export const seasons: Season[] = [
  {
    id: 'season-01',
    number: 1,
    title: 'Season One',
    subtitle: 'The opening movement',
    description: 'Starter content used to demonstrate the reader, season archive and dialogue styling.',
    chapters: [
      {
        id: 's01-c01',
        season: 1,
        number: 1,
        title: 'The First Page',
        summary: 'A compact sample chapter showing the default reading experience.',
        readingMinutes: 3,
        tags: ['starter', 'opening'],
        segments: [
          { kind: 'paragraph', text: 'The city was quiet enough that every late train sounded like a promise being reconsidered.' },
          { kind: 'paragraph', text: 'At the end of the platform, someone had left a paper envelope on the only dry bench.' },
          { kind: 'dialogue', speaker: 'Ari', text: 'That is either the beginning of a very good story or a very bad decision.', accent: 'primary' },
          { kind: 'dialogue', speaker: 'Mina', text: 'Those are usually the same thing for the first five minutes.', accent: 'secondary' },
          { kind: 'break', label: 'Later' },
          { kind: 'paragraph', text: 'Inside the envelope was a single line, written carefully enough to look rehearsed: If you found this, you are already late.' },
        ],
      },
      {
        id: 's01-c02',
        season: 1,
        number: 2,
        title: 'A Door Left Open',
        summary: 'The sample cast follows the clue beyond the station.',
        readingMinutes: 4,
        tags: ['starter', 'mystery'],
        segments: [
          { kind: 'paragraph', text: 'The address led them to a narrow shop wedged between two buildings that had forgotten what century they belonged to.' },
          { kind: 'dialogue', speaker: 'Mina', text: 'We can still choose not to go inside.', accent: 'secondary' },
          { kind: 'dialogue', speaker: 'Ari', text: 'You said that after opening the door.', accent: 'primary' },
          { kind: 'paragraph', text: 'A bell rang above them. Nobody stood behind the counter, but two cups of tea were already steaming.' },
        ],
      },
      {
        id: 's01-c03',
        season: 1,
        number: 3,
        title: 'The Name on the Wall',
        summary: 'A final starter chapter closes the first sample season.',
        readingMinutes: 4,
        tags: ['starter', 'reveal'],
        segments: [
          { kind: 'paragraph', text: 'Every wall was covered in photographs, except for one clean rectangle above the counter.' },
          { kind: 'dialogue', speaker: 'Ari', text: 'Something used to hang there.', accent: 'primary' },
          { kind: 'dialogue', speaker: 'Mina', text: 'Something someone expected us to notice.', accent: 'secondary' },
          { kind: 'paragraph', text: 'Behind the counter, a drawer clicked open by itself. Inside was a brass key and a card carrying a name neither of them recognized.' },
        ],
      },
    ],
  },
  {
    id: 'season-02',
    number: 2,
    title: 'Season Two',
    subtitle: 'After the invitation',
    description: 'A second starter group demonstrates how the archive scales to multiple seasons.',
    chapters: [
      {
        id: 's02-c01',
        season: 2,
        number: 1,
        title: 'Three Floors Down',
        summary: 'The key opens a place that should not fit beneath the city.',
        readingMinutes: 3,
        tags: ['starter', 'discovery'],
        segments: [
          { kind: 'paragraph', text: 'The elevator had no button below B1, yet the brass key turned a hidden dial and sent them three floors deeper.' },
          { kind: 'dialogue', speaker: 'Mina', text: 'I officially prefer ordinary bad decisions.', accent: 'secondary' },
          { kind: 'dialogue', speaker: 'Ari', text: 'Noted for next time.', accent: 'primary' },
        ],
      },
      {
        id: 's02-c02',
        season: 2,
        number: 2,
        title: 'The Quiet Archive',
        summary: 'A room full of unfinished stories waits below street level.',
        readingMinutes: 4,
        tags: ['starter', 'archive'],
        segments: [
          { kind: 'paragraph', text: 'Shelves disappeared into the dark, each book labeled with a date that had not happened yet.' },
          { kind: 'paragraph', text: 'Ari reached for the nearest spine. Mina caught his wrist before he could pull it free.' },
          { kind: 'dialogue', speaker: 'Mina', text: 'For once, let us read the warning first.', accent: 'secondary' },
        ],
      },
      {
        id: 's02-c03',
        season: 2,
        number: 3,
        title: 'Before Tomorrow',
        summary: 'The starter manuscript ends with a clean handoff point for real canon.',
        readingMinutes: 3,
        tags: ['starter', 'handoff'],
        segments: [
          { kind: 'paragraph', text: 'On the desk lay an empty volume with today’s date on its spine.' },
          { kind: 'dialogue', speaker: 'Ari', text: 'This one is blank.', accent: 'primary' },
          { kind: 'dialogue', speaker: 'Mina', text: 'Then maybe this is where our version starts.', accent: 'secondary' },
          { kind: 'break' },
          { kind: 'paragraph', text: 'Replace this starter manuscript with Project G canon while keeping the reader architecture unchanged.' },
        ],
      },
    ],
  },
];
