import type { Chapter, Season } from '../domain/types';
import { seasons as baseSeasons } from './story-v9';

const chapter45: Chapter = {
  id: 's01-c45',
  season: 1,
  number: 45,
  title: 'The Boy Who Was Already Dead',
  summary: 'The anonymous warning about Shen Kai leads Xu Kai and Jian Yue to an old mortuary clerk, who proves the name belonged to someone else long before Xu Kai ever used it.',
  readingMinutes: 10,
  tags: ['identity', 'shen-kai', 'jian-yue', 'lu-chen', 'mystery'],
  segments: [
    { kind: 'paragraph', text: 'The note saying SHEN KAI DIED TWELVE YEARS AGO had been written on burial-office paper.' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Only three offices still use this stock.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Good. I was worried death had become a private industry.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'With you involved, give it time.', accent: 'secondary' },
    { kind: 'paragraph', text: 'By noon they were standing outside a shuttered mortuary archive in the western district.' },
    { kind: 'paragraph', text: 'The former clerk waiting inside was eighty, nearly blind, and unimpressed by National Tier #2.' },
    { kind: 'dialogue', speaker: 'Old Clerk He', text: 'You took long enough.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'People usually open with hello.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Old Clerk He', text: 'People usually stay dead when I write them down.', accent: 'neutral' },
    { kind: 'paragraph', text: 'He produced a burial roll sealed twelve years earlier.' },
    { kind: 'paragraph', text: 'Shen Kai, age eleven, had died during the North River fever season.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Then Gao Wen\'s census record was wrong.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Old Clerk He', text: 'Not wrong. Reused.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Explain.', accent: 'neutral' },
    { kind: 'paragraph', text: 'The old clerk tapped a second page.' },
    { kind: 'paragraph', text: 'After floods, fires, epidemics, and displacement, local offices sometimes rebuilt population rolls from partial names.' },
    { kind: 'dialogue', speaker: 'Old Clerk He', text: 'A dead child with no surviving family. A living boy with no record. Same age range. Same given name. A lazy clerk sees a solution.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Administrative resurrection.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'So you are not Shen Kai.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I am devastated. I had just begun planning the inheritance.', accent: 'primary' },
    { kind: 'paragraph', text: 'Jian Yue did not laugh.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Who sent the note?', accent: 'secondary' },
    { kind: 'paragraph', text: 'Old Clerk He folded his hands.' },
    { kind: 'dialogue', speaker: 'Old Clerk He', text: 'A man named Qin Ruo asked me to make sure Examiner Xu did not accept a convenient answer.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Qin Ruo of An Province?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Old Clerk He', text: 'Former disaster magistrate. Current nuisance.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I already like him.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'No.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I have not done anything.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Preventive supervision.', accent: 'secondary' },
    { kind: 'paragraph', text: 'Lu Chen knew the name.' },
    { kind: 'paragraph', text: 'Qin Ruo had spent fifteen years arguing that provinces relied too heavily on the Five Pillars and had allowed emergency institutions to rot behind them.' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'He is in the capital this week.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Of course he is.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Why of course?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Because people who send anonymous notes are unbearable unless they can watch the result.', accent: 'primary' },
    { kind: 'paragraph', text: 'Old Clerk He smiled.' },
    { kind: 'dialogue', speaker: 'Old Clerk He', text: 'He said you would say something like that.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Xu Kai stopped smiling.' },
  ],
};

const chapter46: Chapter = {
  id: 's01-c46',
  season: 1,
  number: 46,
  title: 'The Country Has Too Many Heroes',
  summary: 'Xu Kai meets Qin Ruo, a provincial reformer who thinks the Five Pillars have become the nation\'s favorite excuse not to build competent institutions.',
  readingMinutes: 11,
  tags: ['qin-ruo', 'politics', 'five-pillars', 'reform', 'xu-kai'],
  segments: [
    { kind: 'paragraph', text: 'Qin Ruo was speaking to three hundred provincial officials when Xu Kai arrived late with Jian Yue.' },
    { kind: 'paragraph', text: 'The title of the forum was NATIONAL RESILIENCE WITHOUT NATIONAL-TIER INTERVENTION.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Subtle.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Sit down.', accent: 'secondary' },
    { kind: 'paragraph', text: 'Qin Ruo looked ordinary enough to be dangerous.' },
    { kind: 'paragraph', text: 'No ceremonial robe. No martial weapon. No theatrical voice.' },
    { kind: 'dialogue', speaker: 'Qin Ruo', text: 'A bridge collapses. We ask which Pillar can arrive. A flood breaks a levee. We ask which Pillar is closest. Bandits take a county seat. We ask whether Lady Jian is available.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Several officials glanced toward Jian Yue.' },
    { kind: 'dialogue', speaker: 'Qin Ruo', text: 'That is not national strength. That is five very capable people standing in front of administrative weakness.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'He is not entirely wrong.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'I heard you.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I was sitting beside you.', accent: 'primary' },
    { kind: 'paragraph', text: 'After the forum, Qin Ruo approached them himself.' },
    { kind: 'dialogue', speaker: 'Qin Ruo', text: 'Examiner Xu.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Anonymous-note enthusiast.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Qin Ruo', text: 'I dislike convenient identities.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'We have that in common.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Why were you looking into his identity?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Qin Ruo', text: 'Because the man who embarrassed Qingshi, White Bridge, the eastern quartermasters, and the Revenue Ministry is more useful to my argument than any speech.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I charge for endorsements.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Qin Ruo', text: 'You are proof that a civilian can solve crises before a National Tier arrives.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'He solves them because people like me keep him alive long enough to be irritating.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'That sounded possessive.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'It was factual.', accent: 'secondary' },
    { kind: 'paragraph', text: 'Qin Ruo watched them carefully.' },
    { kind: 'dialogue', speaker: 'Qin Ruo', text: 'And that is precisely the dependency I mean.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Jian Yue\'s expression cooled.' },
    { kind: 'dialogue', speaker: 'Qin Ruo', text: 'Do not misunderstand me. The Five are necessary. But necessary things become dangerous when everyone else forgets how to function.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You want redundancy.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Qin Ruo', text: 'I want a country that does not collapse if one of five people sleeps late.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Reasonable.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Stop agreeing with suspicious men.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I agree with you constantly.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'That was worse.', accent: 'secondary' },
    { kind: 'paragraph', text: 'Qin Ruo invited Xu Kai to visit a provincial emergency drill the following morning.' },
    { kind: 'dialogue', speaker: 'Qin Ruo', text: 'No Pillars. No army. Clerks, physicians, engineers, messengers, local guards.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'There will be breakfast?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Qin Ruo', text: 'Yes.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I support reform.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'I am coming.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Qin Ruo', text: 'That rather defeats the point.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'I am not participating.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'She is decorative.', accent: 'primary' },
    { kind: 'paragraph', text: 'The table cracked under Jian Yue\'s palm.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Aggressively decorative.', accent: 'primary' },
  ],
};

const chapter47: Chapter = {
  id: 's01-c47',
  season: 1,
  number: 47,
  title: 'The Fire That Knew Her Name',
  summary: 'A provincial emergency drill becomes a real disaster. Jian Yue saves dozens of civilians, exactly as someone expected her to.',
  readingMinutes: 11,
  tags: ['jian-yue', 'trap', 'common-scale', 'rescue', 'martial'],
  segments: [
    { kind: 'paragraph', text: 'The drill was supposed to simulate a warehouse fire.' },
    { kind: 'paragraph', text: 'At the third bell, Warehouse Four actually exploded.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'That seems outside the syllabus.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Qin Ruo', text: 'It is.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Workers poured from the yard.' },
    { kind: 'paragraph', text: 'A timber gallery collapsed across the eastern exit with thirty people still inside.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Stay here.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Oi—', accent: 'primary' },
    { kind: 'paragraph', text: 'She was already gone.' },
    { kind: 'paragraph', text: 'Jian Yue crossed the yard in a crimson blur.' },
    { kind: 'paragraph', text: 'One sword stroke split the burning gallery supports before they crushed the trapped workers.' },
    { kind: 'paragraph', text: 'A second cleared a path through falling timber.' },
    { kind: 'dialogue', speaker: 'Qin Ruo', text: 'Evacuation teams, east lane. Physicians to the yard. Nobody follow her into the smoke.', accent: 'neutral' },
    { kind: 'paragraph', text: 'For twenty seconds the drill functioned exactly as advertised.' },
    { kind: 'paragraph', text: 'Then Xu Kai smelled something bitter beneath the burning pine.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'What do your warehouses store?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Qin Ruo', text: 'Grain, lamp oil, cloth.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Not medicine?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Qin Ruo', text: 'No.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Xu Kai looked toward the smoke.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Then why does the fire smell like black reed?', accent: 'primary' },
    { kind: 'paragraph', text: 'Qin Ruo went pale.' },
    { kind: 'dialogue', speaker: 'Qin Ruo', text: 'Black reed is a meridian suppressant.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'For ordinary people?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Qin Ruo', text: 'Almost harmless. The stronger the circulating internal energy, the worse it binds.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Inside the warehouse, something heavy crashed.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Jian Yue.', accent: 'primary' },
    { kind: 'paragraph', text: 'He ran toward the smoke.' },
    { kind: 'paragraph', text: 'Three local guards caught him before he reached the door.' },
    { kind: 'dialogue', speaker: 'Guard Captain', text: 'Examiner, you cannot go in.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'That is normally her line.', accent: 'primary' },
    { kind: 'paragraph', text: 'A section of wall burst outward.' },
    { kind: 'paragraph', text: 'Jian Yue emerged carrying two unconscious workers.' },
    { kind: 'paragraph', text: 'She made it seven steps.' },
    { kind: 'paragraph', text: 'Then one knee hit the ground.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Oi.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Do not... start.', accent: 'secondary' },
    { kind: 'paragraph', text: 'She tried to stand.' },
    { kind: 'paragraph', text: 'Her internal energy surged.' },
    { kind: 'paragraph', text: 'The black-reed compound tightened through her meridians like wire.' },
    { kind: 'paragraph', text: 'Jian Yue gasped.' },
    { kind: 'paragraph', text: 'The yard floor beneath her cracked anyway.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Stop circulating.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'There are still people inside.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'The teams have them.', accent: 'primary' },
    { kind: 'paragraph', text: 'For once, she listened.' },
    { kind: 'paragraph', text: 'That was when the ground opened.' },
    { kind: 'paragraph', text: 'A prepared section of the yard collapsed into an old freight tunnel.' },
    { kind: 'paragraph', text: 'Jian Yue disappeared with it.' },
    { kind: 'paragraph', text: 'Xu Kai reached the edge half a heartbeat too late.' },
    { kind: 'paragraph', text: 'Below, men in grey masks dragged Jian Yue through a side passage while smoke filled the shaft.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Qin Ruo.', accent: 'primary' },
    { kind: 'paragraph', text: 'There was no joke in his voice.' },
    { kind: 'dialogue', speaker: 'Qin Ruo', text: 'This is not mine.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Then help me prove it.', accent: 'primary' },
  ],
};

const chapter48: Chapter = {
  id: 's01-c48',
  season: 1,
  number: 48,
  title: 'National Tier Number Two Is Missing',
  summary: 'The capital reacts to Jian Yue\'s abduction exactly as the kidnappers predicted. Xu Kai refuses to let the Five make the next move for them.',
  readingMinutes: 10,
  tags: ['abduction', 'five-pillars', 'xu-kai', 'strategy', 'jian-yue'],
  segments: [
    { kind: 'paragraph', text: 'Jian Yue had been missing for forty-three minutes when Han Zhen ordered three military districts sealed.' },
    { kind: 'paragraph', text: 'At forty-six minutes, Yan Shuo requested cavalry.' },
    { kind: 'paragraph', text: 'At forty-eight, Lu Chen had every city gate under intelligence control.' },
    { kind: 'paragraph', text: 'At fifty-one, Xu Kai told them all to stop.' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'No.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Excellent discussion.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'They took a Pillar from the capital district.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Because they knew exactly what you would do afterward.', accent: 'primary' },
    { kind: 'paragraph', text: 'Qin Ruo placed a sealed pamphlet on the table.' },
    { kind: 'paragraph', text: 'It bore the mark of a reform circle called the Common Scale.' },
    { kind: 'dialogue', speaker: 'Qin Ruo', text: 'They began as provincial administrators, physicians, engineers, and retired officers. They share my arguments. They do not answer to me.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Their pamphlet says the nation must learn to survive seventy-two hours without a Pillar.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'They have chosen poorly.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'They chose perfectly.', accent: 'primary' },
    { kind: 'paragraph', text: 'Everyone looked at him.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Jian Yue is the most visible responder among the Five. Take her, and every weakness Qin Ruo described appears at once. Army seals roads. Intelligence closes gates. Provincial officials wait for instructions. Everyone looks upward.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Qin Ruo', text: 'A demonstration.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Yes. Except somebody added black reed and a kidnapping tunnel.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Radical wing.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Likely.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'We search everything.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'No armies.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'You are telling me not to use soldiers to recover Jian Yue?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I am telling you they built this for soldiers.', accent: 'primary' },
    { kind: 'paragraph', text: 'He pointed to the city map.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Every sealed road tells them where you are looking. Every cavalry movement tells them which corridor is safe. Every gate closure turns their hidden route into the only moving route.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Bai Ren', text: 'Then what moves?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Everything ordinary.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Bai Ren', text: 'Meaning?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Bread carts. Night-soil wagons. Laundry. Medicine. People nobody puts on a military map.', accent: 'primary' },
    { kind: 'paragraph', text: 'Han Zhen studied him.' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'You have a plan.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'No.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'That is not reassuring.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I have people who made a plan. That is much better.', accent: 'primary' },
    { kind: 'paragraph', text: 'He took Jian Yue\'s red hair ribbon from the evidence tray.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I want every black-reed merchant in the capital before sunset.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'There are dozens.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Then make the plant expensive.', accent: 'primary' },
  ],
};

const chapter49: Chapter = {
  id: 's01-c49',
  season: 1,
  number: 49,
  title: 'The Most Expensive Root in the Capital',
  summary: 'Xu Kai turns the herbal market upside down to find who is keeping Jian Yue suppressed, while the Five discover that rescuing someone can begin with price manipulation.',
  readingMinutes: 10,
  tags: ['market', 'black-reed', 'wit', 'rescue', 'lu-chen'],
  segments: [
    { kind: 'paragraph', text: 'By sunset black reed cost more than silver.' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'You bought the entire legal supply.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Borrowed.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'With state money.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'The state has been borrowing my peace for weeks.', accent: 'primary' },
    { kind: 'paragraph', text: 'Every apothecary had been instructed to sell future black-reed purchases only in blue paper tied with red thread.' },
    { kind: 'paragraph', text: 'Every illegal seller had been told the government was paying triple for names.' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'You created a market panic.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'A targeted market enthusiasm.', accent: 'primary' },
    { kind: 'paragraph', text: 'Within three hours, five buyers appeared.' },
    { kind: 'paragraph', text: 'Four were martial schools hoarding antidotes.' },
    { kind: 'paragraph', text: 'The fifth bought only fresh root, not dried powder.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'There.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Why?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Dried black reed is enough to contaminate smoke. Fresh root is for maintaining suppression after exposure.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'You knew that?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I asked a physician.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'That is disappointingly normal.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I contain multitudes.', accent: 'primary' },
    { kind: 'paragraph', text: 'The buyer was a baker named Su Han.' },
    { kind: 'paragraph', text: 'Lu Chen wanted him arrested.' },
    { kind: 'paragraph', text: 'Xu Kai bought twelve buns instead.' },
    { kind: 'dialogue', speaker: 'Su Han', text: 'I do not know anything.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Good. Then these buns can remain a commercial transaction.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Su Han', text: 'Why twelve?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I am anxious.', accent: 'primary' },
    { kind: 'paragraph', text: 'That answer made Lu Chen look at him.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Do not make it emotional.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'I said nothing.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You have an accusatory face.', accent: 'primary' },
    { kind: 'paragraph', text: 'Su Han eventually admitted that a charitable clinic had ordered fresh black reed twice that day.' },
    { kind: 'dialogue', speaker: 'Su Han', text: 'They said it was for a patient with runaway internal energy.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Accurate enough.', accent: 'primary' },
    { kind: 'paragraph', text: 'The clinic address was real.' },
    { kind: 'paragraph', text: 'The clinic itself had closed eight months earlier.' },
    { kind: 'paragraph', text: 'But its bread deliveries had not.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'People lie. Habits invoice honestly.', accent: 'primary' },
    { kind: 'paragraph', text: 'The bread route ran through three districts and ended at a monastery warehouse near the old aqueduct.' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'We found them.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'We found where they want medicine delivered.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Difference?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Always.', accent: 'primary' },
    { kind: 'paragraph', text: 'He looked at Jian Yue\'s ribbon again.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Send no one there tonight.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'You are going to make me dislike you again.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Comforting. I prefer familiar relationships.', accent: 'primary' },
  ],
};

const chapter50: Chapter = {
  id: 's01-c50',
  season: 1,
  number: 50,
  title: 'Jian Yue, Temporarily Inconvenienced',
  summary: 'Jian Yue wakes in Common Scale custody with her meridians suppressed and discovers that being kidnapped has not improved her patience.',
  readingMinutes: 9,
  tags: ['jian-yue', 'captive', 'qin-ruo', 'common-scale', 'romance'],
  segments: [
    { kind: 'paragraph', text: 'Jian Yue woke chained to a stone bench and immediately decided the bench was offensive.' },
    { kind: 'paragraph', text: 'Her wrists were bound with layered meridian-lock wire.' },
    { kind: 'paragraph', text: 'A bowl of black-reed tonic sat untouched beside her.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Whoever decorated this room should be executed.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Qin Ruo', text: 'That seems severe.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Qin Ruo stepped into the lantern light.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Qin Ruo', text: 'Not willingly.', accent: 'neutral' },
    { kind: 'paragraph', text: 'He had been brought there separately after the warehouse collapse.' },
    { kind: 'dialogue', speaker: 'Qin Ruo', text: 'The Common Scale cell responsible for this broke from my coalition six months ago.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Convenient.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Qin Ruo', text: 'Extremely. I dislike convenient answers too.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Their captor entered without a mask.' },
    { kind: 'paragraph', text: 'Wei Cang had once commanded a mountain gate army and had retired after losing half a province during a flood evacuation.' },
    { kind: 'dialogue', speaker: 'Wei Cang', text: 'Lady Jian.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Former Commander Wei.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Wei Cang', text: 'You remember me.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'I remember everyone who blames me for arriving after roads already washed away.', accent: 'secondary' },
    { kind: 'paragraph', text: 'Wei Cang did not flinch.' },
    { kind: 'dialogue', speaker: 'Wei Cang', text: 'Forty thousand people waited for a Pillar. Provincial officials delayed evacuation because they believed one of you would solve the river.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'And you think kidnapping me teaches them competence?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Wei Cang', text: 'Seventy-two hours without you will.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You poisoned civilians to reach me.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Wei Cang', text: 'The dose was harmless to them.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'That sentence is why your argument already failed.', accent: 'secondary' },
    { kind: 'paragraph', text: 'Wei Cang left.' },
    { kind: 'paragraph', text: 'Qin Ruo sat against the opposite wall.' },
    { kind: 'dialogue', speaker: 'Qin Ruo', text: 'He is not wrong about the dependency.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Neither is Xu Kai. He is still irritating.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Qin Ruo', text: 'You are worried about him.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'He was standing near an explosion.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Qin Ruo', text: 'You are chained underground and worried about the civilian.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'He requires supervision.', accent: 'secondary' },
    { kind: 'paragraph', text: 'Qin Ruo smiled despite himself.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Do not.', accent: 'secondary' },
    { kind: 'paragraph', text: 'Somewhere far above them, a bell rang twice.' },
    { kind: 'dialogue', speaker: 'Qin Ruo', text: 'That is not one of theirs.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Jian Yue looked toward the ceiling.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Idiot.', accent: 'secondary' },
    { kind: 'paragraph', text: 'She sounded relieved.' },
  ],
};

const chapter51: Chapter = {
  id: 's01-c51',
  season: 1,
  number: 51,
  title: 'The Civilian They Left Behind',
  summary: 'Xu Kai begins dismantling the Common Scale network through permits, banks, bread, and fake inspection orders while the kidnappers wait for soldiers who never come.',
  readingMinutes: 11,
  tags: ['rescue', 'wit', 'common-scale', 'bureaucracy', 'xu-kai'],
  segments: [
    { kind: 'paragraph', text: 'The Common Scale had prepared for cavalry.' },
    { kind: 'paragraph', text: 'They had prepared for Lu Chen\'s agents.' },
    { kind: 'paragraph', text: 'They had prepared for Han Zhen tearing open every fortified compound within twenty li.' },
    { kind: 'paragraph', text: 'They had not prepared for the Municipal Bread Office.' },
    { kind: 'dialogue', speaker: 'Baker', text: 'They cancelled my delivery permit.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Common Scale Courier', text: 'Why?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Baker', text: 'Emergency flour inspection.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Across the district, three laundries received fire-code notices.' },
    { kind: 'paragraph', text: 'Two stable yards were audited for manure disposal.' },
    { kind: 'paragraph', text: 'A private clinic suddenly discovered its banking license had expired that morning.' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'You are weaponizing clerks.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'The nation has invested heavily in them.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Half these violations are invented.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Temporary misunderstandings.', accent: 'primary' },
    { kind: 'paragraph', text: 'Every interruption forced the Common Scale to replace an ordinary service.' },
    { kind: 'paragraph', text: 'Every replacement created movement.' },
    { kind: 'paragraph', text: 'Movement created witnesses.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'They built a hidden network out of normal life. So stop normal life.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Without closing roads.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Exactly.', accent: 'primary' },
    { kind: 'paragraph', text: 'By midnight, six previously invisible safe houses had started sending runners.' },
    { kind: 'paragraph', text: 'Xu Kai ignored five.' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Why the sixth?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Because they sent someone for fresh water.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'All safe houses need water.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Not at midnight unless they have more people than expected.', accent: 'primary' },
    { kind: 'paragraph', text: 'The water runner led them to an abandoned dye warehouse.' },
    { kind: 'paragraph', text: 'Inside were fourteen Common Scale volunteers, three frightened clerks, and no Jian Yue.' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'Wrong place.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Useful wrong place.', accent: 'primary' },
    { kind: 'paragraph', text: 'One of the volunteers carried a ration chit stamped with the number 27.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'How many holding sites use numbered ration seals?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Volunteer', text: 'I do not know.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Good. Which number scares you?', accent: 'primary' },
    { kind: 'paragraph', text: 'The volunteer looked at the chit before he could stop himself.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Twenty-seven it is.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'That was barely an interrogation.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'He did most of it.', accent: 'primary' },
    { kind: 'paragraph', text: 'Site Twenty-Seven did not exist on any official city map.' },
  ],
};

const chapter52: Chapter = {
  id: 's01-c52',
  season: 1,
  number: 52,
  title: 'Three Rescues That Were Not Real',
  summary: 'Xu Kai leaks three false rescue plans and waits to see which one frightens the kidnappers enough to move Jian Yue.',
  readingMinutes: 10,
  tags: ['misdirection', 'rescue', 'five-pillars', 'xu-kai', 'strategy'],
  segments: [
    { kind: 'paragraph', text: 'Xu Kai announced three rescue operations before breakfast.' },
    { kind: 'paragraph', text: 'The first targeted the old aqueduct.' },
    { kind: 'paragraph', text: 'The second targeted a monastery storehouse.' },
    { kind: 'paragraph', text: 'The third targeted a quarry outside the southern wall.' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'Which one is real?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'None.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'You called me here for three operations that do not exist.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I needed them to exist in this room.', accent: 'primary' },
    { kind: 'paragraph', text: 'Each false plan was told to a different cluster of officials.' },
    { kind: 'paragraph', text: 'Only one detail changed each time: the supposed target.' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Canary trap.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Birds are unreliable. Bureaucrats gossip more consistently.', accent: 'primary' },
    { kind: 'paragraph', text: 'At noon the quarry route suddenly saw three wagons leave under vegetable tarps.' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'Then the quarry is real.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'No. It means someone who heard the quarry story warned them.', accent: 'primary' },
    { kind: 'paragraph', text: 'The wagons went north, not deeper south.' },
    { kind: 'dialogue', speaker: 'Bai Ren', text: 'They are moving something important.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Or something they want us to think is important.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'You distrust your own trap.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'That is why it works.', accent: 'primary' },
    { kind: 'paragraph', text: 'He did not follow the wagons.' },
    { kind: 'paragraph', text: 'He followed the empty carts sent to replace them.' },
    { kind: 'paragraph', text: 'Those carts entered the old canal district and vanished behind a paper mill.' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Site Twenty-Seven.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Probably.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'You say probably too often.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Certainty kidnapped Jian Yue.', accent: 'primary' },
    { kind: 'paragraph', text: 'The room went quiet.' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'How long?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Give me six hours.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'You have four.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Five.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'Four.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You negotiate like a siege engine.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'Four.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Fine.', accent: 'primary' },
    { kind: 'paragraph', text: 'For the first time since Jian Yue disappeared, Xu Kai looked tired.' },
    { kind: 'dialogue', speaker: 'Bai Ren', text: 'You will find her.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'That was not a question.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Bai Ren', text: 'No.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Xu Kai tied Jian Yue\'s red ribbon around his wrist.' },
  ],
};

const chapter53: Chapter = {
  id: 's01-c53',
  season: 1,
  number: 53,
  title: 'A Pillar Is Not a Country',
  summary: 'Han Zhen and Xu Kai clash over whether to storm Site Twenty-Seven, forcing the strongest Pillar to trust the civilian method he dislikes most.',
  readingMinutes: 9,
  tags: ['han-zhen', 'rescue', 'trust', 'strategy', 'five-pillars'],
  segments: [
    { kind: 'paragraph', text: 'Site Twenty-Seven sat beneath the paper mill.' },
    { kind: 'paragraph', text: 'Lu Chen found four entrances.' },
    { kind: 'paragraph', text: 'Han Zhen found seven ways to destroy all of them.' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'I can enter from above.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'And bury half the tunnels.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'I can control the force.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'They know that.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'You presume too much.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'They kidnapped Jian Yue by designing a trap around exactly how National Tiers respond. Presumption is the only thing they have done well.', accent: 'primary' },
    { kind: 'paragraph', text: 'Han Zhen stepped closer.' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'She is one of mine.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'She is not a sword in your armory.', accent: 'primary' },
    { kind: 'paragraph', text: 'Yan Shuo stopped breathing for a moment.' },
    { kind: 'paragraph', text: 'Han Zhen\'s expression hardened.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'And she is not proof of a government theory either. She is Jian Yue.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'I know who she is.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Then act like you are rescuing a person instead of recovering a national asset.', accent: 'primary' },
    { kind: 'paragraph', text: 'For several seconds nobody spoke.' },
    { kind: 'dialogue', speaker: 'Bai Ren', text: 'He is right.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'I know.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'This week continues to surprise me.', accent: 'primary' },
    { kind: 'paragraph', text: 'Han Zhen placed a bronze command token on the table.' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'Four hours. No assault unless you fail.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Generous.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'If you get yourself captured, I am not negotiating for you.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'That feels targeted.', accent: 'primary' },
    { kind: 'paragraph', text: 'Han Zhen left.' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'You are planning to get captured.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'What an insulting thing to infer from my character.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'You are planning to get captured.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I dislike this team.', accent: 'primary' },
  ],
};

const chapter54: Chapter = {
  id: 's01-c54',
  season: 1,
  number: 54,
  title: 'Xu Kai Gets Kidnapped on Purpose',
  summary: 'With four hours left, Xu Kai offers the Common Scale exactly what they want most: the civilian proof of their philosophy, delivered voluntarily.',
  readingMinutes: 11,
  tags: ['kidnapping', 'xu-kai', 'jian-yue', 'common-scale', 'wit'],
  segments: [
    { kind: 'paragraph', text: 'Xu Kai sent the message through the bread route.' },
    { kind: 'paragraph', text: 'ONE CIVILIAN FOR ONE PILLAR. YOU WANTED A DEMONSTRATION. TAKE THE BETTER WITNESS.' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'This is not a plan.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'It has punctuation.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'Han Zhen said not to get captured.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'He said he would not negotiate for me. Different policy.', accent: 'primary' },
    { kind: 'paragraph', text: 'The reply arrived twenty minutes later.' },
    { kind: 'paragraph', text: 'COME ALONE.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Rude.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'You are wearing three tracking threads.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I feel accessorized.', accent: 'primary' },
    { kind: 'paragraph', text: 'The Common Scale searched him twice.' },
    { kind: 'paragraph', text: 'They found two tracking threads.' },
    { kind: 'paragraph', text: 'Xu Kai complained loudly about the indignity.' },
    { kind: 'paragraph', text: 'They missed the third because it was woven into the cheap red ribbon around his wrist.' },
    { kind: 'dialogue', speaker: 'Common Scale Guard', text: 'What is that?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'A reminder not to trust women with swords.', accent: 'primary' },
    { kind: 'paragraph', text: 'They took him through the paper mill, down two freight lifts, through a drainage gallery, and into a chamber beneath the old canal.' },
    { kind: 'paragraph', text: 'Xu Kai counted turns aloud until they threatened to gag him.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'That would damage the educational value.', accent: 'primary' },
    { kind: 'paragraph', text: 'Wei Cang met him at the final gate.' },
    { kind: 'dialogue', speaker: 'Wei Cang', text: 'You came.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You took my supervisor.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Wei Cang', text: 'She is not yours.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Neither is the government. I complain about that too.', accent: 'primary' },
    { kind: 'paragraph', text: 'Wei Cang led him into the holding chamber.' },
    { kind: 'paragraph', text: 'Jian Yue looked up.' },
    { kind: 'paragraph', text: 'For one astonishing second, National Tier #2 looked genuinely shocked.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'What are you doing here?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Supervision.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'I am going to kill you.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You look busy.', accent: 'primary' },
    { kind: 'paragraph', text: 'Her eyes dropped to the ribbon around his wrist.' },
    { kind: 'paragraph', text: 'She understood immediately.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Idiot.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You sound relieved.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'I sound murderous.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Very similar vowels.', accent: 'primary' },
    { kind: 'paragraph', text: 'Wei Cang ordered Xu Kai chained beside her.' },
    { kind: 'paragraph', text: 'Xu Kai sat down voluntarily before they finished.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You had better have a plan.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I had several. Getting caught was the least stupid.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'That is not comforting.', accent: 'secondary' },
    { kind: 'paragraph', text: 'Above them, very faintly, three tracking bells began to ring.' },
    { kind: 'paragraph', text: 'Xu Kai smiled.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'It will be.', accent: 'primary' },
  ],
};

const newChapters = [chapter45, chapter46, chapter47, chapter48, chapter49, chapter50, chapter51, chapter52, chapter53, chapter54];

export const seasons: Season[] = baseSeasons.map((season) => {
  if (season.number !== 1) {
    return season;
  }

  return {
    ...season,
    subtitle: 'A dangerous civilian acquires a National-Tier supervisor and eventually has to rescue her.',
    description: 'Xu Kai solves crises through observation, manipulation, economics, social engineering, and shameless conversation. When Jian Yue is deliberately removed from the board, the country discovers that the civilian she kept protecting is much harder to stop than anyone expected.',
    chapters: [...season.chapters, ...newChapters],
  };
});
