import type { Chapter, Season } from '../domain/types';
import { seasons as baseSeasons } from './story-v3';

const chapter15: Chapter = {
  id: 's01-c15',
  season: 1,
  number: 15,
  title: 'The Third Pillar Has Opinions',
  summary: 'National Tier #3 Yan Shuo returns from the eastern frontier expecting a dangerous mastermind. Xu Kai disappoints him immediately and then refuses to behave properly about it.',
  readingMinutes: 10,
  tags: ['yan-shuo', 'five-pillars', 'xu-kai', 'jian-yue', 'banter'],
  segments: [
    { kind: 'paragraph', text: 'Yan Shuo entered the capital through the East Gate with two thousand cavalry, six broken banners, and the kind of reputation that made ordinary people step away from windows.' },
    { kind: 'paragraph', text: 'Xu Kai met him while buying pears.' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'That is him?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Unfortunately.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Oi. That sounded unfriendly.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'It was accurate.', accent: 'secondary' },
    { kind: 'paragraph', text: 'Yan Shuo dismounted.' },
    { kind: 'paragraph', text: 'He was broad-shouldered, sun-darkened, and wore frontier armor that had been repaired so often the original plates were probably a minority.' },
    { kind: 'paragraph', text: 'A long spear rested across the saddle behind him.' },
    { kind: 'paragraph', text: 'The street had gone silent.' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'You are Xu Kai.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I have been accused of that.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'You look disappointing.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You look expensive.', accent: 'primary' },
    { kind: 'paragraph', text: 'Three cavalry officers looked at the sky.' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'Expensive?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Two thousand horses. Frontier steel. Supply wagons. Replacement tack. You must cost the Treasury a fortune every time you have an opinion.', accent: 'primary' },
    { kind: 'paragraph', text: 'Yan Shuo stared at him.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'I warned you.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'You said he was irritating.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'I was being diplomatic.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You? Diplomatic?', accent: 'primary' },
    { kind: 'paragraph', text: 'Jian Yue took one pear from his bag.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Theft.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Tax.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Tyranny.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'You two always like this?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'No.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Yes.', accent: 'primary' },
    { kind: 'paragraph', text: 'Yan Shuo looked between them once.' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'I see.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You see nothing.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'I have eyes.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Use them elsewhere.', accent: 'secondary' },
    { kind: 'paragraph', text: 'Xu Kai bought another pear.' },
    { kind: 'break', label: 'The Hall of Five' },
    { kind: 'paragraph', text: 'By noon all five Pillars were in the same room for the first time in eleven months.' },
    { kind: 'paragraph', text: 'Han Zhen sat at the head of the table. Jian Yue sat on his right. Yan Shuo sat opposite her. Lu Chen had already arranged three dossiers. Bai Ren had arranged snacks.' },
    { kind: 'paragraph', text: 'Xu Kai sat in the empty sixth chair.' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'That chair is not yours.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'It was empty.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'It is ceremonial.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Then it has finally achieved practical employment.', accent: 'primary' },
    { kind: 'paragraph', text: 'Bai Ren ate a sesame cake to hide a smile.' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'This is the man who found White Bridge?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'He found the structure behind it.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'And Qingshi?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Him.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'Seven assassins?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Me.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I provided moral support.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You complained about soup.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Morale is complicated.', accent: 'primary' },
    { kind: 'paragraph', text: 'Yan Shuo put both hands on the table.' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'Then explain the east.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Lu Chen slid a dossier toward Xu Kai.' },
    { kind: 'paragraph', text: 'Eight supply convoys had vanished over four months along the eastern frontier.' },
    { kind: 'paragraph', text: 'No bodies. No burned wagons. No captured drivers. No ransom demands.' },
    { kind: 'paragraph', text: 'Just grain, medicine, winter cloth, and military iron disappearing between fortified posts.' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'I have three possibilities. Smugglers, enemy raiders, or traitors in my quartermaster corps.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Four.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'Name it.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Your convoys did not vanish.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'I am missing eight convoys.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You are missing eight deliveries. That is not the same thing.', accent: 'primary' },
    { kind: 'paragraph', text: 'Yan Shuo sat back.' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Meaning?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Who confirmed the convoys departed?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'Quartermaster seals at the eastern depots.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Who confirmed they failed to arrive?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'Frontier post commanders.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'And between those two statements, everyone invented wagons traveling on roads.', accent: 'primary' },
    { kind: 'paragraph', text: 'Silence settled over the Hall.' },
    { kind: 'dialogue', speaker: 'Bai Ren', text: 'I like this one.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'You liked him when he insulted my chair.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Bai Ren', text: 'That helped.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'You think the records are false.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I think paper is very obedient. It tells you whatever the writer wants.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'Come east.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'No.', accent: 'primary' },
    { kind: 'paragraph', text: 'Yan Shuo blinked.' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'No?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You asked too quickly. It makes the assignment look unpleasant.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'It is a military investigation.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Exactly.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'He is going.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Oi.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'What?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'We discussed consent.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'We discussed you not getting murdered.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Related but distinct topics.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'She is coming too.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Obviously.', accent: 'secondary' },
    { kind: 'paragraph', text: 'Xu Kai looked from one National Tier to the other.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I miss having choices.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'You used them irresponsibly.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Yan Shuo laughed for the first time.' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'We leave at dawn.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Civilization ends before breakfast.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'I will bring buns.', accent: 'secondary' },
    { kind: 'paragraph', text: 'Xu Kai looked at her.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Fine. The nation may survive.', accent: 'primary' },
  ],
};

const chapter16: Chapter = {
  id: 's01-c16',
  season: 1,
  number: 16,
  title: 'The War Game Xu Kai Refused to Play',
  summary: 'Yan Shuo tries to test Xu Kai with a military exercise on the road east. Xu Kai refuses the premise, annoys every officer present, and finds a real problem instead.',
  readingMinutes: 10,
  tags: ['yan-shuo', 'strategy', 'road-east', 'jian-yue', 'wit'],
  segments: [
    { kind: 'paragraph', text: 'Yan Shuo waited until the capital walls disappeared behind them before beginning the test.' },
    { kind: 'paragraph', text: 'He did not call it a test.' },
    { kind: 'paragraph', text: 'This was the first sign that it was one.' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'Suppose five thousand enemy cavalry cross the Yu River here.', accent: 'neutral' },
    { kind: 'paragraph', text: 'He pointed at a campaign map spread over a travel table beside the road.' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'You command twelve hundred infantry, four hundred archers, and one hundred cavalry. The nearest reinforcement is two days away. What do you do?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Go home.', accent: 'primary' },
    { kind: 'paragraph', text: 'Four officers stared at him.' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'You cannot go home.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Then whoever wrote this scenario is vindictive.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Answer him.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I did.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'You would retreat?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I would ask why five thousand cavalry crossed a river nobody crosses in autumn.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'Because they are invading.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'That is motive, not logistics.', accent: 'primary' },
    { kind: 'paragraph', text: 'Xu Kai tapped the map.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'The Yu floods after mountain rain. Your cavalry would arrive exhausted, half their fodder would be wet, and every village for fifty li would know they crossed.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'Assume the river is passable.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Why?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'Because it is an exercise.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Then exercise better.', accent: 'primary' },
    { kind: 'paragraph', text: 'Jian Yue covered her mouth.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Are you laughing?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'No.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Your face is betraying the state.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'Fine. The river is passable because scouts confirmed it.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Whose scouts?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'Mine.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'How many?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'Three teams.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'When?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'Yesterday.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Then I ask why your fictional army has better intelligence than your real quartermaster corps.', accent: 'primary' },
    { kind: 'paragraph', text: 'The officers stopped smiling.' },
    { kind: 'paragraph', text: 'Yan Shuo did too.' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'Explain.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You told me yesterday that eight convoys vanished. How often were their routes scouted?', accent: 'primary' },
    { kind: 'paragraph', text: 'No one answered.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'There it is.', accent: 'primary' },
    { kind: 'paragraph', text: 'Yan Shuo turned to his logistics captain.' },
    { kind: 'dialogue', speaker: 'Captain Du', text: 'Supply roads are considered secure territory, General.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Secure is often the word people use right before they stop looking.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'How often?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Captain Du', text: 'Monthly.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'The Yu gets three scout teams for an imaginary invasion and my grain road gets one inspection a month.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Your fictional soldiers feel very loved.', accent: 'primary' },
    { kind: 'paragraph', text: 'Yan Shuo folded the map.' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'You avoided the exercise.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I improved it.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'You are unbearable.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Now you understand.', accent: 'secondary' },
    { kind: 'break', label: 'Later that afternoon' },
    { kind: 'paragraph', text: 'They stopped at a military waystation where forty replacement horses were waiting.' },
    { kind: 'paragraph', text: 'Xu Kai walked past the horses and stopped beside the feed shed.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Why is the barley from the south?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Captain Du', text: 'It is not.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Then southern farmers have learned to grow eastern dust.', accent: 'primary' },
    { kind: 'paragraph', text: 'He rubbed a grain husk between his fingers.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Red clay. The eastern depots sit on grey loam. Southern transit yards use red clay.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You know soil?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I know laundry. Red clay ruins hems.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'Why would southern feed be issued here under eastern marks?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'That is a better exercise.', accent: 'primary' },
    { kind: 'paragraph', text: 'Yan Shuo looked toward the waystation commander.' },
    { kind: 'paragraph', text: 'The commander had begun sweating.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'And now we have a participant.', accent: 'primary' },
    { kind: 'paragraph', text: 'The investigation moved inside.' },
    { kind: 'break', label: 'Sunset' },
    { kind: 'paragraph', text: 'The waystation commander was not a traitor.' },
    { kind: 'paragraph', text: 'He was simply buying cheaper southern barley, pocketing the difference, and falsifying supply origin stamps.' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'So he is corrupt.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Very.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'But unrelated to the missing convoys.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Probably.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'Probably?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Corruption is social. One man learns the stamps are meaningless, then another learns manifests can lie, then a third discovers nobody checks the road.', accent: 'primary' },
    { kind: 'paragraph', text: 'Yan Shuo looked back at the folded war map.' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'Secure territory.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'My favorite kind of lie. Everyone helps maintain it.', accent: 'primary' },
    { kind: 'paragraph', text: 'Jian Yue handed Xu Kai a bun.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Reward?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You missed lunch.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Concern.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Logistics.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'That was terrible.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Stay out of it.', accent: 'secondary' },
    { kind: 'paragraph', text: 'Yan Shuo decided the eastern road might be more entertaining than expected.' },
  ],
};

const chapter17: Chapter = {
  id: 's01-c17',
  season: 1,
  number: 17,
  title: 'A War Won with Laundry',
  summary: 'Xu Kai reaches the first eastern depot and ignores the weapons, seals, and manifests. Instead he asks to see the soldiers laundry.',
  readingMinutes: 10,
  tags: ['logistics', 'eastern-frontier', 'wit', 'yan-shuo', 'jian-yue'],
  segments: [
    { kind: 'paragraph', text: 'Eastern Depot Six contained enough grain to feed ten thousand soldiers for a month.' },
    { kind: 'paragraph', text: 'It also contained twelve clerks, eighty guards, two quartermasters, and one deeply offended laundry woman.' },
    { kind: 'dialogue', speaker: 'Laundry Mistress Fen', text: 'You came from the capital to inspect socks?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'At last, someone understands me.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'He does not speak for the government.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Frequently he does not speak for himself either.', accent: 'secondary' },
    { kind: 'paragraph', text: 'Mistress Fen narrowed her eyes at all three of them.' },
    { kind: 'dialogue', speaker: 'Laundry Mistress Fen', text: 'National Tiers or not, do not step on my clean sheets.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Yan Shuo stepped backward.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Power recognizes power.', accent: 'primary' },
    { kind: 'paragraph', text: 'The missing convoy manifests showed departures from Depot Six on three occasions.' },
    { kind: 'paragraph', text: 'Each departure listed thirty-two drivers, sixteen guards, and eight wagon teams.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'How many uniforms did you wash before each convoy?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Laundry Mistress Fen', text: 'Convoy guards wash their own clothes.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'All of them?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Laundry Mistress Fen', text: 'Men who spend six days on the road smell like regret. Yes, all of them.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'And before the dates on these manifests?', accent: 'primary' },
    { kind: 'paragraph', text: 'Mistress Fen opened a battered ledger.' },
    { kind: 'paragraph', text: 'She had charged soap by barracks and day for nine years.' },
    { kind: 'paragraph', text: 'On the first missing convoy date, twelve guard uniforms were washed.' },
    { kind: 'paragraph', text: 'On the second, nine.' },
    { kind: 'paragraph', text: 'On the third, none.' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'The manifests list sixteen guards each time.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Paper is obedient.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'But socks are honest?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Socks have very little political ambition.', accent: 'primary' },
    { kind: 'paragraph', text: 'Mistress Fen nodded solemnly.' },
    { kind: 'dialogue', speaker: 'Laundry Mistress Fen', text: 'True.', accent: 'neutral' },
    { kind: 'paragraph', text: 'They moved to the stable records.' },
    { kind: 'paragraph', text: 'Eight wagon teams should have required sixteen draft horses.' },
    { kind: 'paragraph', text: 'The stable master remembered four.' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'So the convoys never left.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Some wagons left. Enough to make witnesses remember movement. Not enough to carry the listed cargo.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Where did the grain go?', accent: 'secondary' },
    { kind: 'paragraph', text: 'Xu Kai walked outside.' },
    { kind: 'paragraph', text: 'The depot stood on a low ridge above three roads.' },
    { kind: 'paragraph', text: 'One road went east to the forts.' },
    { kind: 'paragraph', text: 'One went west to the capital.' },
    { kind: 'paragraph', text: 'The third went south to market towns and civilian farms.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Who got richer this year?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'That is not a military question.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Which is why your soldiers did not ask it.', accent: 'primary' },
    { kind: 'paragraph', text: 'They spent the afternoon in the nearest market town.' },
    { kind: 'paragraph', text: 'Xu Kai did not ask about stolen grain.' },
    { kind: 'paragraph', text: 'He asked bakers why bread was cheaper.' },
    { kind: 'paragraph', text: 'He asked innkeepers why horse feed had fallen in price.' },
    { kind: 'paragraph', text: 'He asked farmers why iron plow fittings were suddenly easy to buy.' },
    { kind: 'paragraph', text: 'He asked children where merchants stored goods when the official warehouses were full.' },
    { kind: 'paragraph', text: 'By sunset, six people had independently mentioned the same abandoned dye works south of town.' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'We raid it tonight.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'No.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'Again?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You really enjoy arriving before the interesting part.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'What interesting part?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Finding out who comes to buy tomorrow.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'And if they move the goods tonight?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Then your soldiers follow wagons instead of searching warehouses.', accent: 'primary' },
    { kind: 'paragraph', text: 'Yan Shuo crossed his arms.' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'You dislike direct solutions.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I dislike incomplete solutions.', accent: 'primary' },
    { kind: 'paragraph', text: 'Jian Yue looked at him for a moment longer than necessary.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'He is right.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'You say that often now?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'No.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Constantly.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Oi.', accent: 'secondary' },
    { kind: 'paragraph', text: 'Xu Kai stopped walking.' },
    { kind: 'paragraph', text: 'Yan Shuo stopped too.' },
    { kind: 'paragraph', text: 'Jian Yue realized what she had said.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You called me Oi.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'I did not.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'You absolutely did.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'No witnesses.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'I command forty thousand soldiers.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'And?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'No witnesses.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Xu Kai looked wounded.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Cowardice at the highest levels.', accent: 'primary' },
    { kind: 'break', label: 'The next morning' },
    { kind: 'paragraph', text: 'The buyer arrived at the dye works in a magistrate carriage.' },
    { kind: 'paragraph', text: 'He was not an enemy agent.' },
    { kind: 'paragraph', text: 'He was the deputy governor of the entire eastern supply prefecture.' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'Now can I raid it?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Yes.', accent: 'primary' },
    { kind: 'paragraph', text: 'Yan Shuo smiled.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You look too happy.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'Direct solution.', accent: 'neutral' },
    { kind: 'paragraph', text: 'The dye works surrendered in three minutes.' },
  ],
};

const chapter18: Chapter = {
  id: 's01-c18',
  season: 1,
  number: 18,
  title: 'The Village That Hated Heroes',
  summary: 'The trail south leads to a village that resents Yan Shuo and the army. Xu Kai discovers that patriotism is difficult to demand from people who have been billed for it twice.',
  readingMinutes: 11,
  tags: ['village', 'politics', 'yan-shuo', 'jian-yue', 'character'],
  segments: [
    { kind: 'paragraph', text: 'The deputy governor confessed to reselling military goods within an hour.' },
    { kind: 'paragraph', text: 'He insisted he was not stealing from soldiers.' },
    { kind: 'dialogue', speaker: 'Deputy Governor Luo', text: 'The army receives more than it needs.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'My winter posts ration lamp oil.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Deputy Governor Luo', text: 'On paper, allocations are full.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'There is that obedient paper again.', accent: 'primary' },
    { kind: 'paragraph', text: 'The resale network led south through three villages.' },
    { kind: 'paragraph', text: 'The first welcomed Yan Shuo with drums.' },
    { kind: 'paragraph', text: 'The second offered wine.' },
    { kind: 'paragraph', text: 'The third closed every door before he arrived.' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'That is new.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Congratulations. You have achieved local fame.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'They are afraid.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'No.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'No?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Afraid people watch from windows. Angry people make sure you notice the windows are empty.', accent: 'primary' },
    { kind: 'paragraph', text: 'Yan Shuo looked down the silent street.' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'Why would they be angry at me?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Excellent question to ask before bringing soldiers inside.', accent: 'primary' },
    { kind: 'paragraph', text: 'Yan Shuo ordered his escort to remain outside the village.' },
    { kind: 'paragraph', text: 'He, Jian Yue, and Xu Kai walked in alone.' },
    { kind: 'paragraph', text: 'An old woman sweeping an already-clean doorstep ignored them.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Morning.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Old Woman', text: 'Is it?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'So far.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Old Woman', text: 'Wait until the army sends a tax collector.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Yan Shuo stopped.' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'The army does not collect village tax.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Old Woman', text: 'Then someone has been very creative in your name.', accent: 'neutral' },
    { kind: 'paragraph', text: 'She produced three receipts.' },
    { kind: 'paragraph', text: 'Road maintenance levy.' },
    { kind: 'paragraph', text: 'Frontier defense contribution.' },
    { kind: 'paragraph', text: 'Emergency winter horse fodder assessment.' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'None of these exist.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'They exist enough to have receipts.', accent: 'primary' },
    { kind: 'paragraph', text: 'The old woman led them to the village hall.' },
    { kind: 'paragraph', text: 'Within twenty minutes, thirty families had produced similar papers.' },
    { kind: 'paragraph', text: 'Every payment bore the seal of the eastern supply prefecture.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'The same office reselling military supplies.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Sell the army goods. Tax civilians to replace the goods. Charge the state for the replacement. Very efficient.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'Efficient?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Criminals can be organized.', accent: 'primary' },
    { kind: 'paragraph', text: 'Yan Shuo was quiet.' },
    { kind: 'paragraph', text: 'He had spent ten years holding the eastern frontier.' },
    { kind: 'paragraph', text: 'Villagers had painted his spear on festival banners.' },
    { kind: 'paragraph', text: 'Here, children had been told to hide when his soldiers appeared.' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'Why did no one report this?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Village Head', text: 'To whom?', accent: 'neutral' },
    { kind: 'paragraph', text: 'Yan Shuo had no answer.' },
    { kind: 'dialogue', speaker: 'Village Head', text: 'The receipts carried government seals. The collectors wore military cloaks. When we complained at the county office, they told us sacrifice protects the border.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'People tolerate almost anything if you call it duty loudly enough.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Not anything.', accent: 'secondary' },
    { kind: 'paragraph', text: 'Xu Kai looked at her.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'There is a point where duty becomes theft.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Good.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Do not grade me.', accent: 'secondary' },
    { kind: 'break', label: 'Afternoon' },
    { kind: 'paragraph', text: 'Yan Shuo ordered repayment from seized prefectural funds.' },
    { kind: 'paragraph', text: 'The village head did not bow.' },
    { kind: 'dialogue', speaker: 'Village Head', text: 'Money returns. Trust does not.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Yan Shuo accepted the words without anger.' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'Then I will earn it badly and slowly.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Xu Kai looked at him with new interest.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'That was almost intelligent.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'Careful.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I said almost.', accent: 'primary' },
    { kind: 'paragraph', text: 'The old woman from the doorstep handed Yan Shuo a broom.' },
    { kind: 'dialogue', speaker: 'Old Woman', text: 'If you want to start earning, the drainage ditch is blocked.', accent: 'neutral' },
    { kind: 'paragraph', text: 'National Tier #3 stared at the broom.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Power recognizes power.', accent: 'primary' },
    { kind: 'paragraph', text: 'Yan Shuo cleaned the drainage ditch.' },
    { kind: 'paragraph', text: 'Jian Yue helped.' },
    { kind: 'paragraph', text: 'Xu Kai supervised from the shade until Jian Yue threw mud at him.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Oi!', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Supervision.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You weaponized sanitation.', accent: 'primary' },
    { kind: 'paragraph', text: 'For the first time that day, several villagers laughed.' },
    { kind: 'break', label: 'Evening' },
    { kind: 'paragraph', text: 'They ate in the village hall.' },
    { kind: 'paragraph', text: 'The meal was simple, the rice slightly burned, and Jian Yue kept pushing the least-charred portions toward Xu Kai without comment.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You know I can see you doing that.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Doing what?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Managing my rice exposure.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You complain when food is bad.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'And this troubles you?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'It troubles everyone.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'She gave me the burned side.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You are National Tier.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'Apparently fire respects rank.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Xu Kai laughed.' },
    { kind: 'paragraph', text: 'Jian Yue tried not to look pleased that he did.' },
    { kind: 'paragraph', text: 'Outside, the village doors remained open.' },
  ],
};

const chapter19: Chapter = {
  id: 's01-c19',
  season: 1,
  number: 19,
  title: 'Three Generals, Two Lies, and One Goat',
  summary: 'The missing-supply network reaches the frontier itself, where three commanders accuse each other of feeding the enemy. Xu Kai would like everyone to stop talking long enough to listen to a goat.',
  readingMinutes: 11,
  tags: ['frontier', 'mystery', 'goat', 'yan-shuo', 'xu-kai'],
  segments: [
    { kind: 'paragraph', text: 'Fort Shanyin sat where the eastern hills narrowed into a stone throat.' },
    { kind: 'paragraph', text: 'Three generals were waiting inside.' },
    { kind: 'paragraph', text: 'All three were furious.' },
    { kind: 'dialogue', speaker: 'General Pei', text: 'His scouts crossed the line twice last month.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'General Rong', text: 'Because your patrols abandoned the ridge.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'General Ma', text: 'Both of you lost wagons and now want someone else hanged.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Xu Kai sat at the end of the command table eating chestnuts.' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'Stop.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Three generals stopped.' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'One at a time.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Or none. None has merit.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'General Pei', text: 'Who is this civilian?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'A problem.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Her problem.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'State problem.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'General Ma', text: 'Is there a difference?', accent: 'neutral' },
    { kind: 'paragraph', text: 'Jian Yue looked at him.' },
    { kind: 'dialogue', speaker: 'General Ma', text: 'There is a difference.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Xu Kai offered him a chestnut.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Survival instinct. Promising.', accent: 'primary' },
    { kind: 'paragraph', text: 'The accusation was simple.' },
    { kind: 'paragraph', text: 'Military grain had appeared across the border in enemy markets.' },
    { kind: 'paragraph', text: 'Someone was selling state supplies outside the country.' },
    { kind: 'paragraph', text: 'Each of the three generals controlled a road that could move the stolen goods.' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'One of these routes is compromised.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Maybe.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'You dislike certainty.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I dislike borrowing it from angry people.', accent: 'primary' },
    { kind: 'paragraph', text: 'He asked to see the seized grain sacks.' },
    { kind: 'paragraph', text: 'The bags carried eastern army markings.' },
    { kind: 'paragraph', text: 'The rope knots matched army standard.' },
    { kind: 'paragraph', text: 'The wax inventory tags looked authentic.' },
    { kind: 'dialogue', speaker: 'General Rong', text: 'Proof.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Of what?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'General Rong', text: 'Our supplies crossed the border.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'The sacks crossed the border.', accent: 'primary' },
    { kind: 'paragraph', text: 'He opened one.' },
    { kind: 'paragraph', text: 'Millet poured onto the table.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Do your soldiers eat this?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'General Pei', text: 'Of course.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'This exact grade?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'General Pei', text: 'Millet is millet.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'That sounded dangerous.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Finally, someone respects agriculture.', accent: 'primary' },
    { kind: 'paragraph', text: 'He carried a handful outside.' },
    { kind: 'paragraph', text: 'A tethered pack goat immediately pulled against its rope.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Interesting.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'It is hungry.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'That goat has ignored three army feed bins since we arrived.', accent: 'primary' },
    { kind: 'paragraph', text: 'Everyone looked at the goat.' },
    { kind: 'paragraph', text: 'The goat looked pleased with its new importance.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Where was it raised?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Stable Boy', text: 'South valley, sir.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'And this millet?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Stable Boy', text: 'Smells like south-valley grain.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'General Ma', text: 'You can smell the difference?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Stable Boy', text: 'Goats can.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Today we respect expertise.', accent: 'primary' },
    { kind: 'paragraph', text: 'Yan Shuo crouched beside the spilled grain.' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'The army buys northern millet for the frontier.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Because it stores longer in cold weather.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'So someone filled army sacks with civilian grain and sold them across the border.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Which means the enemy market evidence was planted.', accent: 'primary' },
    { kind: 'paragraph', text: 'The three generals stopped glaring at each other.' },
    { kind: 'dialogue', speaker: 'General Rong', text: 'To make us suspect treason.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'To make you do more than suspect it.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'Fight each other.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Xu Kai nodded.' },
    { kind: 'paragraph', text: 'A horn sounded from the eastern wall.' },
    { kind: 'paragraph', text: 'One short blast. Two long.' },
    { kind: 'paragraph', text: 'Every military officer in the yard changed expression.' },
    { kind: 'dialogue', speaker: 'General Pei', text: 'Border riders.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Minutes later, scouts brought in three wounded cavalrymen.' },
    { kind: 'paragraph', text: 'Their patrol had been attacked near Willow Pass by soldiers wearing the colors of the neighboring state of Liangbei.' },
    { kind: 'dialogue', speaker: 'General Rong', text: 'There. That is your proof.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'How many attackers?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Wounded Scout', text: 'Twenty. Maybe thirty.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'Did you see unit markings?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Wounded Scout', text: 'No, General. Only colors.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Yan Shuo looked at Xu Kai.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Do not.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'Do not what?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Have the satisfying reaction someone prepared for you.', accent: 'primary' },
    { kind: 'paragraph', text: 'Outside the walls, war horns began answering each other across the hills.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'If Liangbei really attacked our patrol, we cannot ignore it.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Agreed.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'You agree?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Ignoring it would be stupid.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'And attacking?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Potentially more stupid.', accent: 'primary' },
    { kind: 'paragraph', text: 'Yan Shuo exhaled through his nose.' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'I preferred you when I thought you were merely annoying.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Growth is painful.', accent: 'primary' },
    { kind: 'paragraph', text: 'The goat ate the evidence.' },
    { kind: 'dialogue', speaker: 'General Ma', text: 'Should we stop it?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'No. It has contributed more than most committees.', accent: 'primary' },
    { kind: 'paragraph', text: 'By nightfall, both sides of the border were mobilizing.' },
  ],
};

const newChapters = [chapter15, chapter16, chapter17, chapter18, chapter19];

export const seasons: Season[] = baseSeasons.map((season) => {
  if (season.number !== 1) {
    return season;
  }

  return {
    ...season,
    subtitle: 'A dangerous civilian acquires a National-Tier supervisor and accidentally becomes a national policy problem.',
    description: 'Xu Kai solves crises through observation, manipulation, economics, social engineering, and shameless conversation while Jian Yue, National Tier #2, insists that following him everywhere is merely responsible supervision.',
    chapters: [...season.chapters, ...newChapters],
  };
});
