import type { Chapter, Season } from '../domain/types';
import { seasons as baseSeasons } from './story-v11';

const chapter65: Chapter = {
  id: 's01-c65',
  season: 1,
  number: 65,
  title: 'The Weather Xu Kai Refused to Explain',
  summary: 'The Hall of Five wants to know what Black Rain means. Jian Yue already knows enough to realize Xu Kai is about to lie professionally.',
  readingMinutes: 10,
  tags: ['black-rain', 'hall-of-five', 'xu-kai', 'jian-yue', 'mystery'],
  segments: [
    { kind: 'paragraph', text: 'The black envelope remained in the center of the Hall of Five like a sixth person with poor manners.' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'What is Black Rain?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Weather.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'No.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Worth trying.', accent: 'primary' },
    { kind: 'paragraph', text: 'Han Zhen read the single line again.' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: '“The man who ended Black Rain in one night.” That is not weather.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Bai Ren', text: 'Could be very dramatic weather.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'Do not help him.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Bai Ren', text: 'I am helping the weather.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Jian Yue sat beside Xu Kai and did not look at him.' },
    { kind: 'paragraph', text: 'This was deliberate.' },
    { kind: 'paragraph', text: 'If she looked at him, Lu Chen would notice that she already knew the question was dangerous.' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'The wax is uncommon.', accent: 'neutral' },
    { kind: 'paragraph', text: 'He scraped a thumbnail across the white seal.' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Bone ash, rice wax, and cedar oil.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You make stationery unpleasant.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Military cipher offices used this mixture eight to twelve years ago.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Xu Kai stopped tapping the table.' },
    { kind: 'paragraph', text: 'Jian Yue noticed that too.' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'You recognize it.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I recognize many regrettable things.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'Such as?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Your campaign breakfasts.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'I walked into that.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Han Zhen placed one hand over the envelope.' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'Enough.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Xu Kai looked at him.' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'If this concerns national security, you tell us.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'It concerned national security seven years ago.', accent: 'primary' },
    { kind: 'paragraph', text: 'The room changed.' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Seven years.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Approximately.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'The same period your legal identity begins.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'History has a terrible habit of occurring near other history.', accent: 'primary' },
    { kind: 'paragraph', text: 'Jian Yue finally looked at him.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Is whoever sent this dangerous now?', accent: 'secondary' },
    { kind: 'paragraph', text: 'Xu Kai met her eyes.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Possibly.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'That was not a joke.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'No.', accent: 'primary' },
    { kind: 'paragraph', text: 'The other four Pillars noticed the answer.' },
    { kind: 'dialogue', speaker: 'Bai Ren', text: 'That may be the most alarming thing he has said.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I once criticized Yue\'s noodles.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You survived by luck.', accent: 'secondary' },
    { kind: 'paragraph', text: 'Xu Kai folded the black paper.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Black Rain was a contingency doctrine.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'For what?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'For the collapse of government.', accent: 'primary' },
    { kind: 'paragraph', text: 'Silence.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Distributed cells. Sealed target lists. Independent confirmation codes. If the capital was compromised, local teams were supposed to remove officials believed to be collaborating with an enemy power.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'I have never heard of this.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'That was considered a feature.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Who created it?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Director Gu Zhaolin. Office of Special Measures.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'There is no Office of Special Measures.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Not anymore.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'Why?', accent: 'neutral' },
    { kind: 'paragraph', text: 'Xu Kai looked at the black envelope.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Because Black Rain activated when it was not supposed to.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'And you stopped it.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Mostly.', accent: 'primary' },
    { kind: 'paragraph', text: 'Jian Yue heard the word he chose.' },
    { kind: 'paragraph', text: 'Mostly.' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'How?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Paperwork.', accent: 'primary' },
    { kind: 'paragraph', text: 'Jian Yue nearly choked.' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Paperwork.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Very aggressive paperwork.', accent: 'primary' },
    { kind: 'paragraph', text: 'Under the table, Jian Yue kicked his ankle.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Oi.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Later.', accent: 'secondary' },
    { kind: 'paragraph', text: 'Lu Chen\'s eyes moved between them.' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'I hate that word now.', accent: 'neutral' },
    { kind: 'paragraph', text: 'A clerk entered before he could ask more.' },
    { kind: 'paragraph', text: 'He carried another black envelope.' },
    { kind: 'paragraph', text: 'This one was addressed to Jian Yue.' },
  ],
};

const chapter66: Chapter = {
  id: 's01-c66',
  season: 1,
  number: 66,
  title: 'Only Oi Gets the Second Page',
  summary: 'The message to Jian Yue proves the sender knows she is close to Xu Kai. He finally tells her what “ending Black Rain” actually cost.',
  readingMinutes: 10,
  tags: ['black-rain', 'romance', 'secret', 'jian-yue', 'xu-kai'],
  segments: [
    { kind: 'paragraph', text: 'Jian Yue opened her envelope in Xu Kai\'s kitchen because she refused to let Lu Chen stare at her while she read it.' },
    { kind: 'paragraph', text: 'Xu Kai made tea badly on purpose.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You are using too many leaves.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I am under emotional pressure.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You are ruining tea.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Same thing.', accent: 'primary' },
    { kind: 'paragraph', text: 'She unfolded the paper.' },
    { kind: 'paragraph', text: 'ASK HIM WHAT HAPPENED AT THE NINTH BELL.' },
    { kind: 'paragraph', text: 'Below it was a second line.' },
    { kind: 'paragraph', text: 'ASK HIM WHY HE LEFT GU ZHAOLIN ALIVE.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Did you?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'The tea needs time.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Xu Kai.', accent: 'secondary' },
    { kind: 'paragraph', text: 'He put the kettle down.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Yes.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Why?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Because killing him would not have stopped Black Rain.', accent: 'primary' },
    { kind: 'paragraph', text: 'He leaned against the counter.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'That was the point of the system. No cell knew the others. Every team had its own list, code book, fallback signal, and deadline. Gu could die at sunset and fifty people would still be murdered by midnight.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'So what did you do?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Made every cell believe the others had been compromised.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'In one night?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'It was a long night.', accent: 'primary' },
    { kind: 'paragraph', text: 'He told her about copied confirmation strips, forged courier routes, bells rung out of sequence, and three false evacuation orders.' },
    { kind: 'paragraph', text: 'He told her about changing street signs so two assassination teams walked into each other.' },
    { kind: 'paragraph', text: 'He told her about paying a funeral troupe to play the emergency cancellation hymn in the wrong district until six cells froze waiting for verification.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You stopped a state assassination network with musicians.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Excellent musicians.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'And the ninth bell?', accent: 'secondary' },
    { kind: 'paragraph', text: 'The humor left him.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'By the ninth bell, every cell but one had stood down.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Gu\'s?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'His Rain Guard.', accent: 'primary' },
    { kind: 'paragraph', text: 'She waited.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'They were not interested in paperwork.', accent: 'primary' },
    { kind: 'paragraph', text: 'Jian Yue understood.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'How many?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Enough.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Xu Kai.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Twelve.', accent: 'primary' },
    { kind: 'paragraph', text: 'She stared at him.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Twelve what?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'People who would have made Yan Shuo unhappy.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'National Tier?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'The classification was less tidy then.', accent: 'primary' },
    { kind: 'paragraph', text: 'Jian Yue closed her eyes.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'I hate learning things about you.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'That seems healthy.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Did you kill them?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'No.', accent: 'primary' },
    { kind: 'paragraph', text: 'That answer came immediately.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I broke the Guard. I did not kill them.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'And Gu?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'He was already dying.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'From you?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'From his own people.', accent: 'primary' },
    { kind: 'paragraph', text: 'That surprised her.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'They discovered he had altered the activation conditions. Black Rain was supposed to protect the state from occupation. Gu used it to remove political enemies during a succession dispute.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Why leave him alive?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Because forty-three cells still needed his cancellation seals.', accent: 'primary' },
    { kind: 'paragraph', text: 'Jian Yue sat down.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'So the terrifying martial story is still mostly administration.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I have standards.', accent: 'primary' },
    { kind: 'paragraph', text: 'She read her message again.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Whoever sent this knows too much.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Yes.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Do you know who?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I know who used white wax.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Name.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Ning Sui. Cipher clerk. Black Rain courier coordinator.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Alive?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Apparently everyone has been disrespecting death lately.', accent: 'primary' },
    { kind: 'paragraph', text: 'A knock came from the front door.' },
    { kind: 'paragraph', text: 'Three slow knocks. Two fast.' },
    { kind: 'paragraph', text: 'Xu Kai went very still.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'That is her.', accent: 'primary' },
  ],
};

const chapter67: Chapter = {
  id: 's01-c67',
  season: 1,
  number: 67,
  title: 'The Woman in Funeral White',
  summary: 'Ning Sui arrives at Xu Kai\'s door carrying an old cipher box and absolutely no interest in being intimidated by Jian Yue.',
  readingMinutes: 9,
  tags: ['ning-sui', 'black-rain', 'jian-yue', 'xu-kai', 'cipher'],
  segments: [
    { kind: 'paragraph', text: 'Ning Sui wore white because she had been attending her own funeral for seven years.' },
    { kind: 'paragraph', text: 'This was how she explained it.' },
    { kind: 'dialogue', speaker: 'Ning Sui', text: 'It saves wardrobe decisions.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You still make normal explanations impossible.', accent: 'primary' },
    { kind: 'paragraph', text: 'She looked thirty-something, perhaps older, with cropped dark hair and the patient expression of someone who had spent years correcting other people\'s codes.' },
    { kind: 'paragraph', text: 'She carried a lacquered cipher box under one arm.' },
    { kind: 'paragraph', text: 'Jian Yue stood between her and Xu Kai without discussing it.' },
    { kind: 'dialogue', speaker: 'Ning Sui', text: 'National Tier #2.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Former corpse.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Ning Sui', text: 'He has good taste now.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Jian Yue narrowed her eyes.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'This conversation has become dangerous in an unexpected direction.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Ning Sui', text: 'Relax. I knew him when he owned one shirt.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'One?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Textile economics were difficult.', accent: 'primary' },
    { kind: 'paragraph', text: 'Ning Sui placed the cipher box on his judgmental table.' },
    { kind: 'dialogue', speaker: 'Ning Sui', text: 'Black Rain moved last week.', accent: 'neutral' },
    { kind: 'paragraph', text: 'The room became serious.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Where?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Ning Sui', text: 'Three provinces. Five old dead-drop sites opened. Two legacy couriers received confirmation strips.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Targets?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Ning Sui', text: 'Unknown.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Trigger phrase?', accent: 'primary' },
    { kind: 'paragraph', text: 'Ning Sui opened the box.' },
    { kind: 'paragraph', text: 'Inside were six strips of black paper marked in silver ink.' },
    { kind: 'dialogue', speaker: 'Ning Sui', text: '“The roof remains dry.”', accent: 'neutral' },
    { kind: 'paragraph', text: 'Xu Kai swore.' },
    { kind: 'paragraph', text: 'Jian Yue looked genuinely impressed.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You know that word.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I know several.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Rarely in that order.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Ning Sui', text: 'That phrase was never in the active code book.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'It was Gu\'s private reset.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Meaning he is alive.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Or someone opened his sealed archive.', accent: 'primary' },
    { kind: 'paragraph', text: 'Ning Sui removed one more item from the box.' },
    { kind: 'paragraph', text: 'A narrow copper token stamped with nine falling lines.' },
    { kind: 'dialogue', speaker: 'Ning Sui', text: 'This was found in a dead drop yesterday.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Rain Guard command token.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You said you broke them.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I did.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Ning Sui', text: 'You broke twelve people. The institution had twenty-one names.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Xu Kai looked at her sharply.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Nine were reserve?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Ning Sui', text: 'Compartmentalization.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I hate competent bureaucracy.', accent: 'primary' },
    { kind: 'paragraph', text: 'Jian Yue picked up one of the black strips.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Why contact him instead of State Security?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Ning Sui', text: 'Because Black Rain was designed to survive State Security.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'And him?', accent: 'secondary' },
    { kind: 'paragraph', text: 'Ning Sui looked at Xu Kai.' },
    { kind: 'dialogue', speaker: 'Ning Sui', text: 'It was not designed to survive him.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Jian Yue did not like how much that sentence explained.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'We tell Lu Chen enough to mobilize quietly.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Enough?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'If he knows every old code term, he will notice the parts I do not want noticed.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Your strength.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Among other administrative irregularities.', accent: 'primary' },
    { kind: 'paragraph', text: 'Ning Sui looked between them.' },
    { kind: 'dialogue', speaker: 'Ning Sui', text: 'She knows.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Unfortunately.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Unfortunately?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You have become impossible to lie to.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Good.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Ning Sui', text: 'This is adorable.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Leave.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Ning Sui', text: 'We just established a national emergency.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Then stand farther away.', accent: 'secondary' },
  ],
};

const chapter68: Chapter = {
  id: 's01-c68',
  season: 1,
  number: 68,
  title: 'The Hall Receives Half a Truth',
  summary: 'Xu Kai briefs the Five on Black Rain while Jian Yue discovers that protecting his secret requires becoming a much better liar.',
  readingMinutes: 9,
  tags: ['hall-of-five', 'black-rain', 'secrets', 'lu-chen', 'jian-yue'],
  segments: [
    { kind: 'paragraph', text: 'Xu Kai told the Hall of Five the truth in carefully measured portions.' },
    { kind: 'paragraph', text: 'Lu Chen noticed within forty seconds.' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'You are omitting something.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I omit many things. Breakfast details. Private correspondence. Yan Shuo\'s poetry.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'I do not write poetry.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'The nation is grateful.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'You are still omitting something.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Jian Yue drank tea.' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'Focus.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Ning Sui stood beside a map marked with five old dead drops.' },
    { kind: 'dialogue', speaker: 'Ning Sui', text: 'Legacy activation movement has appeared in South Yu, River Province, and the Grey March.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'How many former cells remain viable?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Ning Sui', text: 'We believed zero.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Bai Ren', text: 'A reassuring number.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Ning Sui', text: 'It is less reassuring now.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Xu Kai circled the five sites.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'These are not activation points.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'Why not?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Too obvious. Whoever opened them wants old Black Rain people to notice.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'A summons.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Or bait.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'For you.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I am very popular among extinct institutions.', accent: 'primary' },
    { kind: 'paragraph', text: 'Han Zhen looked at Ning Sui.' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'What happened seven years ago when Xu Kai reached Gu Zhaolin?', accent: 'neutral' },
    { kind: 'paragraph', text: 'Ning Sui looked at Xu Kai.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'We discussed the codes.', accent: 'primary' },
    { kind: 'paragraph', text: 'Under the table, Jian Yue pinched the bridge of her nose.' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Discussed.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Intensely.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Ning Sui', text: 'That is one word for it.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'The details are irrelevant to identifying the current operator.', accent: 'secondary' },
    { kind: 'paragraph', text: 'Lu Chen looked at her.' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'You know the details.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'No.', accent: 'secondary' },
    { kind: 'paragraph', text: 'The lie was terrible.' },
    { kind: 'paragraph', text: 'Everyone heard it.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Oi.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'What?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'We should practice this skill.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Shut up.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Bai Ren', text: 'She definitely knows.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'Later.', accent: 'neutral' },
    { kind: 'paragraph', text: 'He tapped the Grey March.' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'Why there?', accent: 'neutral' },
    { kind: 'paragraph', text: 'Xu Kai did not answer immediately.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Because that is where Black Rain ended.', accent: 'primary' },
    { kind: 'paragraph', text: 'Ning Sui placed a second map over the first.' },
    { kind: 'paragraph', text: 'An old city appeared beneath modern roads.' },
    { kind: 'paragraph', text: 'Yunqiao.' },
    { kind: 'dialogue', speaker: 'Ning Sui', text: 'The original command house was under the western archive district.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Was?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Ning Sui', text: 'The district burned during Black Rain.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Mostly after.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Why mostly?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'There were structural disagreements.', accent: 'primary' },
    { kind: 'paragraph', text: 'Jian Yue stared at him.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Not helping?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'No.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'We go to Yunqiao.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Too many Pillars will scare away whoever opened the drops.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'Then who goes?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Me.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Me.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I enjoy how nobody asks the civilian.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You are coming.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'There. Oppression restored.', accent: 'primary' },
  ],
};

const chapter69: Chapter = {
  id: 's01-c69',
  season: 1,
  number: 69,
  title: 'The City That Stopped Using Umbrellas',
  summary: 'Xu Kai returns to Yunqiao, where an old superstition about Black Rain has outlived the people who created it.',
  readingMinutes: 10,
  tags: ['yunqiao', 'black-rain', 'travel', 'mystery', 'jian-yue'],
  segments: [
    { kind: 'paragraph', text: 'Yunqiao had no umbrellas.' },
    { kind: 'paragraph', text: 'It was raining when they arrived.' },
    { kind: 'paragraph', text: 'This made the absence more noticeable.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Why is everyone getting wet?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Local tradition.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Explain.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'During Black Rain, couriers carried black oil-paper umbrellas. People learned to cross the street when they saw one.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Ning Sui', text: 'Then someone killed a family under a red umbrella by mistake.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'After that, umbrellas became unpopular generally.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'That is horrible.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Superstition usually has a receipt.', accent: 'primary' },
    { kind: 'paragraph', text: 'He had become quieter as the city walls approached.' },
    { kind: 'paragraph', text: 'Jian Yue had stopped asking whether he was fine.' },
    { kind: 'paragraph', text: 'She had learned that the question gave him an opportunity to lie.' },
    { kind: 'paragraph', text: 'Instead she walked beside him.' },
    { kind: 'break', label: 'Western archive district' },
    { kind: 'paragraph', text: 'The command house was gone.' },
    { kind: 'paragraph', text: 'A public bathhouse stood over the site.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'History has improved.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'There was a secret assassination headquarters here.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Now there are towels.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Ning Sui', text: 'The archive tunnel entrance should still exist below the furnace room.', accent: 'neutral' },
    { kind: 'paragraph', text: 'The bathhouse owner recognized Ning Sui.' },
    { kind: 'paragraph', text: 'He did not look pleased.' },
    { kind: 'dialogue', speaker: 'Bathhouse Owner', text: 'You people promised never to come back.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Ning Sui', text: 'I personally promised to remain dead.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Bathhouse Owner', text: 'You are doing poorly.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Xu Kai handed him money.' },
    { kind: 'dialogue', speaker: 'Bathhouse Owner', text: 'What is that for?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Future inconvenience.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Bathhouse Owner', text: 'How much inconvenience?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I brought Lu Chen.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'I am standing here.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Bathhouse Owner', text: 'Not enough money.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Xu Kai added two coins.' },
    { kind: 'dialogue', speaker: 'Bathhouse Owner', text: 'Acceptable.', accent: 'neutral' },
    { kind: 'break', label: 'Below the furnace room' },
    { kind: 'paragraph', text: 'The old tunnel smelled like wet brick and forgotten government.' },
    { kind: 'paragraph', text: 'Ning Sui lit a lamp.' },
    { kind: 'paragraph', text: 'Black paint marked nine falling lines on the first arch.' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Recent.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'How recent?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Days.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Xu Kai crouched beside the paint.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Wrong brush.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Ning Sui', text: 'What?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Black Rain marks used split horsehair. This is goat.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You know that by looking?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'No. One is stuck in the paint.', accent: 'primary' },
    { kind: 'paragraph', text: 'He plucked out a pale hair.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'I preferred the impressive version.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Reality is often cheaper.', accent: 'primary' },
    { kind: 'paragraph', text: 'They followed the marks deeper.' },
    { kind: 'paragraph', text: 'At the old cipher chamber, someone had placed twenty-one chairs in a circle.' },
    { kind: 'paragraph', text: 'Twelve were broken.' },
    { kind: 'paragraph', text: 'Nine were intact.' },
    { kind: 'paragraph', text: 'On the center table lay a single white wax seal.' },
    { kind: 'dialogue', speaker: 'Ning Sui', text: 'This is for the reserve Guard.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'No.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'No?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'It is for me.', accent: 'primary' },
    { kind: 'paragraph', text: 'He turned the seal over.' },
    { kind: 'paragraph', text: 'Scratched into the underside were four words.' },
    { kind: 'paragraph', text: 'YOU MISSED THE NINTH.' },
  ],
};

const chapter70: Chapter = {
  id: 's01-c70',
  season: 1,
  number: 70,
  title: 'Nine Chairs and One Bad Memory',
  summary: 'The reserve Rain Guard was larger than Xu Kai knew. Someone wants him to believe the missing ninth survivor is the one rebuilding Black Rain.',
  readingMinutes: 10,
  tags: ['rain-guard', 'black-rain', 'investigation', 'xu-kai', 'lu-chen'],
  segments: [
    { kind: 'paragraph', text: 'Lu Chen photographed the room with memory.' },
    { kind: 'paragraph', text: 'Xu Kai tried to leave with his.' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Sit.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I dislike that verb from you.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Nine reserve members. Names.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I did not know there were nine.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Ning Sui', text: 'Neither did I.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Then who did?', accent: 'neutral' },
    { kind: 'paragraph', text: 'Nobody answered.' },
    { kind: 'paragraph', text: 'Jian Yue walked around the intact chairs.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Why break twelve?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Symbolism.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'I hate symbolism.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Because it usually means someone wants you to think instead of investigate.', accent: 'primary' },
    { kind: 'paragraph', text: 'He picked up one broken chair leg.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'These were smashed recently.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Agreed.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'So whoever staged this knows there were twelve people I defeated.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Defeated how?', accent: 'secondary' },
    { kind: 'paragraph', text: 'Lu Chen looked at her.' },
    { kind: 'paragraph', text: 'She realized the mistake.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Strategically.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'You remain terrible at this.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'We are training.', accent: 'primary' },
    { kind: 'paragraph', text: 'Ning Sui examined the white wax seal.' },
    { kind: 'dialogue', speaker: 'Ning Sui', text: 'Not mine.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Same mixture.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Ning Sui', text: 'Different cedar. Mine comes from River Province. This is Grey March cedar.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Local imitation.', accent: 'primary' },
    { kind: 'paragraph', text: 'Lu Chen opened a wall cabinet.' },
    { kind: 'paragraph', text: 'Inside sat twenty-one narrow slots.' },
    { kind: 'paragraph', text: 'Twenty were empty.' },
    { kind: 'paragraph', text: 'One held a black lacquer name tile.' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Qin Fei.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Xu Kai did not react.' },
    { kind: 'paragraph', text: 'Which was a reaction.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You know the name.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Rain Guard deputy.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Ning Sui', text: 'Officially died during Black Rain.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Officially died after trying to stab Gu.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'You saw the body?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'No.', accent: 'primary' },
    { kind: 'paragraph', text: 'Lu Chen made a face that for him counted as celebration.' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Of course.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Do not enjoy this.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'You have spent months handing me dead people who are alive.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Administrative trend.', accent: 'primary' },
    { kind: 'paragraph', text: 'Jian Yue turned the name tile over.' },
    { kind: 'paragraph', text: 'A fresh line had been carved into the back.' },
    { kind: 'paragraph', text: 'ONE OF US REMEMBERED WHY IT RAINED.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'That sounds like a threat.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Too literary.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Meaning?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Qin Fei hated metaphors.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Ning Sui', text: 'He once filed a complaint about poetic cipher phrases.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You had bureaucrats complaining that secret murder codes were too poetic.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Civil service is resilient.', accent: 'primary' },
    { kind: 'paragraph', text: 'He put the tile down.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Someone wants us to hunt Qin Fei.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Should we?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Yes.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You just said it is bait.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Bait still tells you where the fisherman is not looking.', accent: 'primary' },
    { kind: 'paragraph', text: 'Ning Sui smiled faintly.' },
    { kind: 'dialogue', speaker: 'Ning Sui', text: 'There he is.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Do not encourage him.', accent: 'secondary' },
  ],
};

const chapter71: Chapter = {
  id: 's01-c71',
  season: 1,
  number: 71,
  title: 'How to Hunt a Dead Assassin with Laundry',
  summary: 'Qin Fei has been dead for seven years. Xu Kai starts with laundry because apparently death still requires clean clothes.',
  readingMinutes: 10,
  tags: ['qin-fei', 'investigation', 'laundry', 'wit', 'yunqiao'],
  segments: [
    { kind: 'paragraph', text: 'Lu Chen searched death registries.' },
    { kind: 'paragraph', text: 'Ning Sui searched old courier ledgers.' },
    { kind: 'paragraph', text: 'Jian Yue searched armories.' },
    { kind: 'paragraph', text: 'Xu Kai went to a laundry.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Again?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Clothing continues to betray civilization.', accent: 'primary' },
    { kind: 'paragraph', text: 'The laundry district served bathhouses, barracks, inns, magistrate offices, and anyone who preferred not to smell like Yunqiao rain.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Qin Fei had one habit.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Besides secret assassination?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'He hated starch.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'This is your lead.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Do not mock textile intelligence.', accent: 'primary' },
    { kind: 'paragraph', text: 'At the third laundry, an old washerwoman remembered a difficult customer.' },
    { kind: 'dialogue', speaker: 'Washerwoman', text: 'Tall man. Grey coats. Pays extra to keep the collars soft.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Scar on the right hand?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Washerwoman', text: 'No scar.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Xu Kai paused.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Not him?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Qin Fei had half his right palm burned.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Washerwoman', text: 'Then wrong dead assassin.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You are taking this very well.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Washerwoman', text: 'I wash magistrate clothes. Nothing surprises me.', accent: 'neutral' },
    { kind: 'paragraph', text: 'She produced a delivery ledger.' },
    { kind: 'paragraph', text: 'The grey coats went to a book warehouse near the north canal.' },
    { kind: 'paragraph', text: 'The account name was Qin Fei.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Someone is using his name.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Loudly.', accent: 'primary' },
    { kind: 'paragraph', text: 'They did not go to the warehouse.' },
    { kind: 'paragraph', text: 'Instead Xu Kai bought every available collar-starch order in the district.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Why?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Because whoever is pretending to be Qin Fei expects us to follow the address.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'So?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'So we change something unrelated and see who notices.', accent: 'primary' },
    { kind: 'paragraph', text: 'Within two hours, a boy from the north-canal warehouse arrived asking why the laundry had changed the grey-coat treatment.' },
    { kind: 'paragraph', text: 'Jian Yue caught him before he reached the door.' },
    { kind: 'dialogue', speaker: 'Boy', text: 'I only deliver messages!', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Then deliver one now.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Boy', text: 'To who?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'The person who cares about unstarching a dead man\'s collar.', accent: 'primary' },
    { kind: 'paragraph', text: 'The boy stared at him.' },
    { kind: 'dialogue', speaker: 'Boy', text: 'You are weird.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Professional hazard.', accent: 'primary' },
    { kind: 'paragraph', text: 'The message went out.' },
    { kind: 'paragraph', text: 'They followed the second courier instead of the boy.' },
    { kind: 'paragraph', text: 'He led them nowhere near the north-canal warehouse.' },
    { kind: 'paragraph', text: 'He went to the city cemetery.' },
    { kind: 'paragraph', text: 'At Qin Fei\'s grave, someone was waiting.' },
    { kind: 'paragraph', text: 'A man with a burned right palm.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You look terrible.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Qin Fei', text: 'You look annoying.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Jian Yue\'s hand went to her sword.' },
    { kind: 'dialogue', speaker: 'Qin Fei', text: 'If I wanted him dead, Lady Jian, you would have found a much more interesting grave.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Try me.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Oi. He hates metaphors. That was practically a peace offering.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Qin Fei', text: 'I still hate you.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Good. Continuity.', accent: 'primary' },
  ],
};

const chapter72: Chapter = {
  id: 's01-c72',
  season: 1,
  number: 72,
  title: 'The Ninth Man Was Hiding from the Eighth',
  summary: 'Qin Fei is alive, furious, and not the person rebuilding Black Rain. He has been hiding because another Rain Guard survivor has been hunting the old reserve list.',
  readingMinutes: 11,
  tags: ['qin-fei', 'rain-guard', 'black-rain', 'reveal', 'jian-yue'],
  segments: [
    { kind: 'paragraph', text: 'Qin Fei refused to talk at his own grave.' },
    { kind: 'dialogue', speaker: 'Qin Fei', text: 'It feels disrespectful.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'To whom?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Qin Fei', text: 'Me.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You are difficult to mourn.', accent: 'primary' },
    { kind: 'paragraph', text: 'They moved to an empty shrine storehouse.' },
    { kind: 'paragraph', text: 'Qin Fei sat with his back to the wall and both hands visible.' },
    { kind: 'paragraph', text: 'Jian Yue remained close enough to reach him first.' },
    { kind: 'dialogue', speaker: 'Qin Fei', text: 'You told her.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Told her what?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Qin Fei', text: 'Do not insult me. She is guarding your secret, not your body.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Jian Yue stared at him.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'How can you tell?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Qin Fei', text: 'You stand differently around men you think need protection.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Jian Yue looked offended by the existence of observational skill.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I like him again.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You did not like him five minutes ago.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'People grow.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Qin Fei', text: 'I remained alive because one of the reserve Guard began killing the others.', accent: 'neutral' },
    { kind: 'paragraph', text: 'That ended the joke.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Name.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Qin Fei', text: 'Jiang Tai.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Ning Sui', text: 'Reserve designation Eight.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Qin Fei', text: 'He found me three years ago. Asked whether Gu left a second doctrine archive.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Did he?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Qin Fei', text: 'I did not know.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'And when you said that?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Qin Fei', text: 'He tried to remove my remaining hand.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Jian Yue glanced at the burn scar.' },
    { kind: 'dialogue', speaker: 'Qin Fei', text: 'I became less cooperative.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Reasonable.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Qin Fei', text: 'Since then, reserve Four and Six disappeared. Seven was found dead last winter.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Ning Sui', text: 'Why did none of you contact me?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Qin Fei', text: 'Because you were dead.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Ning Sui', text: 'Fair.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Xu Kai paced once across the small room.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Jiang Tai wants the reserve list and Gu\'s second archive.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Why reactivate old drops?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'To flush survivors.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Qin Fei', text: 'And you.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Xu Kai stopped.' },
    { kind: 'dialogue', speaker: 'Qin Fei', text: 'He is obsessed with the fact that you ended us without killing us.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Why?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Qin Fei', text: 'Because Jiang Tai believes mercy is what broke Black Rain.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'That is a very stupid sentence.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Qin Fei', text: 'He has had seven years to make it worse.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Qin Fei reached inside his coat.' },
    { kind: 'paragraph', text: 'Jian Yue\'s sword was halfway out before he produced a folded scrap of oilcloth.' },
    { kind: 'dialogue', speaker: 'Qin Fei', text: 'Relax.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'No.', accent: 'secondary' },
    { kind: 'paragraph', text: 'Inside the oilcloth was half a map.' },
    { kind: 'paragraph', text: 'The missing half had been torn away along a river line.' },
    { kind: 'dialogue', speaker: 'Qin Fei', text: 'Gu gave this to me before the ninth bell.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'What is it?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Qin Fei', text: 'The location of the second doctrine archive.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'And the other half?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Qin Fei', text: 'Reserve Eight.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Jian Yue looked at Xu Kai.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'So Jiang Tai is not rebuilding Black Rain.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Not yet.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'He is looking for the instructions.', accent: 'secondary' },
    { kind: 'paragraph', text: 'Xu Kai unfolded the half-map.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Then we should reach them first.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Qin Fei', text: 'You do not know where the other half points.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'No.', accent: 'primary' },
    { kind: 'paragraph', text: 'He smiled.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'But Jiang Tai thinks we do.', accent: 'primary' },
  ],
};

const newChapters = [chapter65, chapter66, chapter67, chapter68, chapter69, chapter70, chapter71, chapter72];

export const seasons: Season[] = baseSeasons.map((season) => {
  if (season.number !== 1) {
    return season;
  }

  return {
    ...season,
    subtitle: 'A dangerous civilian acquires a National-Tier supervisor and accidentally becomes a national policy problem.',
    description: 'Xu Kai solves crises through observation, manipulation, economics, social engineering, and shameless conversation while Jian Yue, National Tier #2, now secretly knows that the civilian she once protected can also stand in front of her.',
    chapters: [...season.chapters, ...newChapters],
  };
});
