import type { Season } from '../domain/types';

export const seasons: Season[] = [
  {
    id: 'season-01',
    number: 1,
    title: 'The Most Dangerous Civilian',
    subtitle: 'A rebellion ends. The government becomes concerned.',
    description: 'Xu Kai dismantles a rebellion without visibly throwing a punch. The court responds by assigning National Tier #2 Jian Yue to supervise him. This goes poorly for everyone involved.',
    chapters: [
      {
        id: 's01-c01',
        season: 1,
        number: 1,
        title: 'A Rebellion for the Price of Cabbage',
        summary: 'Qingshi has been occupied for eleven days. Xu Kai is mostly offended by the vegetable prices.',
        readingMinutes: 8,
        tags: ['xu-kai', 'rebellion', 'wit', 'opening'],
        segments: [
          { kind: 'paragraph', text: 'The rebellion had lasted eleven days, sealed three city gates, replaced the magistrate, arrested seventeen officials, and convinced six thousand armed men that they were founding a new age.' },
          { kind: 'paragraph', text: 'Xu Kai\'s chief complaint was the cabbage.' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'Twelve copper?' , accent: 'primary' },
          { kind: 'dialogue', speaker: 'Auntie Sun', text: 'Fourteen if you keep looking at me like that.' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'Yesterday it was seven.' , accent: 'primary' },
          { kind: 'dialogue', speaker: 'Auntie Sun', text: 'Yesterday the rebels had not decided paper promises count as money.' },
          { kind: 'paragraph', text: 'Auntie Sun slapped a square of grey military scrip onto the vegetable stall. A red seal occupied half the paper. The other half promised repayment after the glorious stabilization of Qingshi.' },
          { kind: 'dialogue', speaker: 'Auntie Sun', text: 'They buy vegetables with these. My landlord wants silver. My supplier wants copper. My husband wants to complain. Only one of those three accepts rebellion money.' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'Your husband?' , accent: 'primary' },
          { kind: 'dialogue', speaker: 'Auntie Sun', text: 'He accepts anything if it means he gets to complain.' },
          { kind: 'paragraph', text: 'Xu Kai picked up a cabbage, weighed it in one hand, and looked toward the eastern watchtower. A rebel banner hung above the wall. Beneath it, two soldiers were arguing with a noodle seller who had started charging triple for military scrip.' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'How many stalls are still taking the paper at full value?' , accent: 'primary' },
          { kind: 'dialogue', speaker: 'Auntie Sun', text: 'Idiots? Maybe five.' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'Excellent.' , accent: 'primary' },
          { kind: 'dialogue', speaker: 'Auntie Sun', text: 'That was not a compliment.' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'It was not for them.' , accent: 'primary' },
          { kind: 'break', label: 'An hour later' },
          { kind: 'paragraph', text: 'The first thing Xu Kai did to end the rebellion was buy a cabbage.' },
          { kind: 'paragraph', text: 'The second thing he did was convince Auntie Sun to rewrite her price board.' },
          { kind: 'dialogue', speaker: 'Auntie Sun', text: 'Eight copper. Thirty in military scrip. You are trying to get me arrested.' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'No. I am trying to make everyone else copy you before anyone decides whose idea it was.' , accent: 'primary' },
          { kind: 'dialogue', speaker: 'Auntie Sun', text: 'And why would they?' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'Because you are greedy, respected, and loud.' , accent: 'primary' },
          { kind: 'dialogue', speaker: 'Auntie Sun', text: 'You really know how to ask for favors.' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'I can add beautiful.' , accent: 'primary' },
          { kind: 'dialogue', speaker: 'Auntie Sun', text: 'Put the board up.' },
          { kind: 'paragraph', text: 'By noon, nineteen stalls had copied the price. By mid-afternoon, forty-three had. By sunset, the military scrip had not officially lost a single copper of value and was practically worthless everywhere soldiers wanted to spend it.' },
          { kind: 'paragraph', text: 'This created what the rebel command later described as an unexpected morale complication.' },
          { kind: 'paragraph', text: 'Xu Kai called it Tuesday.' },
          { kind: 'break', label: 'The South Garrison' },
          { kind: 'paragraph', text: 'Captain He had the build of a gatehouse and the patience of a wet cat. He stared across his desk at Xu Kai, then at the cabbage Xu Kai had brought with him.' },
          { kind: 'dialogue', speaker: 'Captain He', text: 'Who are you?' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'Hungry.' , accent: 'primary' },
          { kind: 'dialogue', speaker: 'Captain He', text: 'You asked for a military audience.' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'I asked the guard whether the captain knew his men had not received silver in nine days. He decided that sounded like a military audience.' , accent: 'primary' },
          { kind: 'paragraph', text: 'Captain He stopped looking at the cabbage.' },
          { kind: 'dialogue', speaker: 'Captain He', text: 'The treasury pays every seventh day.' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'Then you are two days late.' , accent: 'primary' },
          { kind: 'dialogue', speaker: 'Captain He', text: 'I can count.' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'Good. That puts you above whoever falsified the western regiment ledger.' , accent: 'primary' },
          { kind: 'paragraph', text: 'Silence settled over the room with the soft, satisfying weight of a trap closing.' },
          { kind: 'dialogue', speaker: 'Captain He', text: 'What ledger?' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'The one Clerk Wen drinks himself stupid over every evening because Commander Bo ordered him to move three hundred taels into a supply account that has no supplier.' , accent: 'primary' },
          { kind: 'dialogue', speaker: 'Captain He', text: 'That is a serious accusation.' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'No. An accusation is when I say Commander Bo stole it. I am merely saying the money is gone, the paperwork is bad, and you are the officer whose signature sits beneath both.' , accent: 'primary' },
          { kind: 'paragraph', text: 'Captain He stood.' },
          { kind: 'dialogue', speaker: 'Captain He', text: 'You should leave.' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'Probably.' , accent: 'primary' },
          { kind: 'dialogue', speaker: 'Captain He', text: 'Now.' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'Before I go, the clerk drinks at the Blue Heron. Third table from the kitchen. He starts confessing to furniture after the fourth cup.' , accent: 'primary' },
          { kind: 'paragraph', text: 'Xu Kai left the cabbage on the desk.' },
          { kind: 'paragraph', text: 'Captain He stared at it for a long time.' },
          { kind: 'break', label: 'That evening' },
          { kind: 'paragraph', text: 'The Blue Heron had never hosted a conspiracy before, but it adapted quickly.' },
          { kind: 'dialogue', speaker: 'Clerk Wen', text: 'I did not steal anything.' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'I know.' , accent: 'primary' },
          { kind: 'dialogue', speaker: 'Clerk Wen', text: 'Then why are you sitting here?' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'Because Captain He thinks you did.' , accent: 'primary' },
          { kind: 'paragraph', text: 'Clerk Wen turned pale.' },
          { kind: 'dialogue', speaker: 'Clerk Wen', text: 'He what?' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'To be fair, I helped.' , accent: 'primary' },
          { kind: 'dialogue', speaker: 'Clerk Wen', text: 'You helped him think I stole military silver?' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'Only briefly. If everything goes well, within an hour he will realize Commander Bo stole it.' , accent: 'primary' },
          { kind: 'dialogue', speaker: 'Clerk Wen', text: 'Commander Bo did steal it.' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'See? We are making excellent progress.' , accent: 'primary' },
          { kind: 'paragraph', text: 'Clerk Wen looked at his cup, then at Xu Kai, then at the door.' },
          { kind: 'dialogue', speaker: 'Clerk Wen', text: 'Who sent you?' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'A woman selling overpriced vegetables.' , accent: 'primary' },
          { kind: 'dialogue', speaker: 'Clerk Wen', text: 'I am serious.' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'So is Auntie Sun.' , accent: 'primary' },
          { kind: 'paragraph', text: 'Ten minutes later, Clerk Wen was copying three pages of the treasury ledger from memory onto the back of a wine menu.' },
          { kind: 'paragraph', text: 'Twenty minutes later, Captain He entered the Blue Heron with four soldiers.' },
          { kind: 'paragraph', text: 'Thirty minutes later, those four soldiers were asking why their families were being paid in paper while Commander Bo had purchased two estates outside the city.' },
          { kind: 'paragraph', text: 'An hour later, Xu Kai was no longer in the tavern.' },
          { kind: 'break', label: 'The next morning' },
          { kind: 'paragraph', text: 'Someone painted a pig wearing Commander Bo\'s helmet on the western barracks wall.' },
          { kind: 'paragraph', text: 'Someone else added a purse of silver beneath the pig.' },
          { kind: 'paragraph', text: 'By breakfast, the image had appeared on seven walls.' },
          { kind: 'paragraph', text: 'By lunch, soldiers were calling their own commander General Pig.' },
          { kind: 'paragraph', text: 'By dinner, Commander Bo had arrested Captain He for sedition.' },
          { kind: 'paragraph', text: 'This turned out to be a mistake.' },
          { kind: 'break', label: 'The rebel command hall' },
          { kind: 'dialogue', speaker: 'Commander Bo', text: 'Who is Xu Kai?' },
          { kind: 'dialogue', speaker: 'Clerk Wen', text: 'A civilian.' },
          { kind: 'dialogue', speaker: 'Commander Bo', text: 'A civilian does not collapse military discipline in two days.' },
          { kind: 'dialogue', speaker: 'Clerk Wen', text: 'Apparently this one does.' },
          { kind: 'paragraph', text: 'Outside, several hundred soldiers were demanding Captain He\'s release, their missing pay, and a clarification regarding the pig.' },
          { kind: 'dialogue', speaker: 'Commander Bo', text: 'Find him.' },
          { kind: 'break', label: 'Across the city' },
          { kind: 'paragraph', text: 'Xu Kai sat beside Auntie Sun\'s vegetable stall eating noodles.' },
          { kind: 'dialogue', speaker: 'Auntie Sun', text: 'They are looking for you.' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'That feels ungrateful.' , accent: 'primary' },
          { kind: 'dialogue', speaker: 'Auntie Sun', text: 'You ruined their money, exposed their commander, and got half the western barracks shouting about a pig.' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'I did not draw the pig.' , accent: 'primary' },
          { kind: 'dialogue', speaker: 'Auntie Sun', text: 'Did you tell the theatre boys that Commander Bo hates pigs?' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'That was private cultural information.' , accent: 'primary' },
          { kind: 'paragraph', text: 'A distant bell rang from the southern wall.' },
          { kind: 'paragraph', text: 'Then another.' },
          { kind: 'paragraph', text: 'Then all three watchtowers began ringing at once.' },
          { kind: 'dialogue', speaker: 'Auntie Sun', text: 'Government army?' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'Not yet.' , accent: 'primary' },
          { kind: 'dialogue', speaker: 'Auntie Sun', text: 'Then what is that?' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'Captain He taking the western gate.' , accent: 'primary' },
          { kind: 'dialogue', speaker: 'Auntie Sun', text: 'How do you know?' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'Because if I were him, I would do it before Commander Bo remembers he has archers.' , accent: 'primary' },
          { kind: 'paragraph', text: 'Auntie Sun stared at him.' },
          { kind: 'dialogue', speaker: 'Auntie Sun', text: 'You planned all this?' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'No.' , accent: 'primary' },
          { kind: 'dialogue', speaker: 'Auntie Sun', text: 'No?' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'Plans are fragile. I just gave everyone a reason to do what they already wanted to do.' , accent: 'primary' },
          { kind: 'paragraph', text: 'The western gate opened before sunset.' },
          { kind: 'paragraph', text: 'Commander Bo fled through the northern gate and was arrested by his own unpaid cavalry.' },
          { kind: 'paragraph', text: 'The rebellion ended on the thirteenth day.' },
          { kind: 'paragraph', text: 'Xu Kai finally bought his cabbage for eight copper.' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'See? Government restored.' , accent: 'primary' },
          { kind: 'dialogue', speaker: 'Auntie Sun', text: 'You are the worst customer I have ever had.' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'And yet your prices are reasonable again.' , accent: 'primary' },
          { kind: 'paragraph', text: 'Three days later, the Ministry of State Security opened a file on Xu Kai.' },
          { kind: 'paragraph', text: 'The first line read: Combat ability — negligible or unknown.' },
          { kind: 'paragraph', text: 'The second read: Strategic threat — extreme.' },
          { kind: 'paragraph', text: 'The third had been underlined twice.' },
          { kind: 'paragraph', text: 'Recommendation: National-Tier supervision.' },
        ],
      },
      {
        id: 's01-c02',
        season: 1,
        number: 2,
        title: 'The Woman Everyone Bows To',
        summary: 'National Tier #2 arrives to investigate Xu Kai. He greets her with one deeply inadvisable word.',
        readingMinutes: 9,
        tags: ['jian-yue', 'oi', 'national-tier', 'banter'],
        segments: [
          { kind: 'paragraph', text: 'When Jian Yue entered the teahouse, twenty-seven people stood up.' },
          { kind: 'paragraph', text: 'One old man nearly overturned his table doing it.' },
          { kind: 'paragraph', text: 'A waiter dropped a spoon.' },
          { kind: 'paragraph', text: 'The owner personally abandoned the kitchen.' },
          { kind: 'paragraph', text: 'Xu Kai remained seated because his dumpling had just arrived.' },
          { kind: 'dialogue', speaker: 'Teahouse Owner', text: 'Lady Jian. This humble establishment is honored.' },
          { kind: 'dialogue', speaker: 'Jian Yue', text: 'Sit. All of you.' , accent: 'secondary' },
          { kind: 'paragraph', text: 'Everyone sat.' },
          { kind: 'paragraph', text: 'Except Xu Kai, who had never stood up.' },
          { kind: 'paragraph', text: 'Jian Yue noticed.' },
          { kind: 'paragraph', text: 'It was difficult not to notice the only man in Qingshi eating dumplings while National Tier #2 stood three paces away.' },
          { kind: 'dialogue', speaker: 'Jian Yue', text: 'Xu Kai?' , accent: 'secondary' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'Depends who is asking.' , accent: 'primary' },
          { kind: 'dialogue', speaker: 'Jian Yue', text: 'Jian Yue.' , accent: 'secondary' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'My condolences.' , accent: 'primary' },
          { kind: 'paragraph', text: 'The teahouse became so quiet that the dropped spoon finally stopped spinning on the floor.' },
          { kind: 'dialogue', speaker: 'Jian Yue', text: 'For what?' , accent: 'secondary' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'Having everyone announce your name like thunder should arrive afterward.' , accent: 'primary' },
          { kind: 'paragraph', text: 'Jian Yue looked at the empty chair opposite him.' },
          { kind: 'dialogue', speaker: 'Jian Yue', text: 'May I?' , accent: 'secondary' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'You frightened the owner. I suspect the chair belongs to you now.' , accent: 'primary' },
          { kind: 'paragraph', text: 'She sat.' },
          { kind: 'paragraph', text: 'Jian Yue wore no armor. She did not need it. A dark crimson sword rested at her side, plain enough to be mistaken for modest until one noticed nobody in the room was willing to breathe loudly near it.' },
          { kind: 'paragraph', text: 'Xu Kai offered her a dumpling.' },
          { kind: 'dialogue', speaker: 'Jian Yue', text: 'No.' , accent: 'secondary' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'Good. There are only six.' , accent: 'primary' },
          { kind: 'dialogue', speaker: 'Jian Yue', text: 'I came to question you about the Qingshi rebellion.' , accent: 'secondary' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'That sounds less enjoyable than dumplings.' , accent: 'primary' },
          { kind: 'dialogue', speaker: 'Jian Yue', text: 'Captain He says you caused the western garrison to mutiny.' , accent: 'secondary' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'Commander Bo caused the western garrison to mutiny. I merely improved communication.' , accent: 'primary' },
          { kind: 'dialogue', speaker: 'Jian Yue', text: 'Clerk Wen says you deliberately exposed the missing treasury silver.' , accent: 'secondary' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'He exposed it. I bought him wine.' , accent: 'primary' },
          { kind: 'dialogue', speaker: 'Jian Yue', text: 'The merchants say you organized the rejection of military scrip.' , accent: 'secondary' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'I bought one cabbage.' , accent: 'primary' },
          { kind: 'dialogue', speaker: 'Jian Yue', text: 'You expect me to believe a cabbage ended a rebellion?' , accent: 'secondary' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'No. That would be disrespectful to the dumplings.' , accent: 'primary' },
          { kind: 'paragraph', text: 'Her eyes narrowed.' },
          { kind: 'paragraph', text: 'Around them, twenty-seven people discovered urgent reasons to stare at their own tables.' },
          { kind: 'dialogue', speaker: 'Jian Yue', text: 'Do you always answer questions like this?' , accent: 'secondary' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'Only when the questions already know their own answers.' , accent: 'primary' },
          { kind: 'paragraph', text: 'For the first time, Jian Yue stopped looking irritated.' },
          { kind: 'paragraph', text: 'Not impressed. Not amused. Simply attentive.' },
          { kind: 'dialogue', speaker: 'Jian Yue', text: 'Fine. Then answer one you do not know. Why did you do it?' , accent: 'secondary' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'The cabbage was twelve copper.' , accent: 'primary' },
          { kind: 'dialogue', speaker: 'Jian Yue', text: 'I am serious.' , accent: 'secondary' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'So was I.' , accent: 'primary' },
          { kind: 'paragraph', text: 'Jian Yue folded her arms.' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'The rebellion was already rotting. Soldiers had paper instead of pay. Officers were stealing. Merchants hated the scrip. Half the city was waiting for someone else to move first. I moved a cabbage.' , accent: 'primary' },
          { kind: 'dialogue', speaker: 'Jian Yue', text: 'And if Captain He had arrested you?' , accent: 'secondary' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'He wanted Commander Bo more than he wanted me.' , accent: 'primary' },
          { kind: 'dialogue', speaker: 'Jian Yue', text: 'If Clerk Wen had refused to talk?' , accent: 'secondary' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'He had spent nine nights drinking at the same table and apologizing to a wooden pillar.' , accent: 'primary' },
          { kind: 'dialogue', speaker: 'Jian Yue', text: 'If the merchants had kept accepting the scrip?' , accent: 'secondary' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'Then I would have found a better cabbage.' , accent: 'primary' },
          { kind: 'paragraph', text: 'Something dangerously close to amusement touched Jian Yue\'s mouth.' },
          { kind: 'paragraph', text: 'It vanished before anyone else could be certain.' },
          { kind: 'dialogue', speaker: 'Jian Yue', text: 'You enjoy this.' , accent: 'secondary' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'Thinking?' , accent: 'primary' },
          { kind: 'dialogue', speaker: 'Jian Yue', text: 'Making everyone around you miserable.' , accent: 'secondary' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'That is more of a side benefit.' , accent: 'primary' },
          { kind: 'paragraph', text: 'A waiter placed tea between them with trembling hands.' },
          { kind: 'paragraph', text: 'Jian Yue lifted her cup.' },
          { kind: 'dialogue', speaker: 'Jian Yue', text: 'The Ministry considers you dangerous.' , accent: 'secondary' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'That feels excessive.' , accent: 'primary' },
          { kind: 'dialogue', speaker: 'Jian Yue', text: 'You dismantled a provincial rebellion in two days.' , accent: 'secondary' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'Thirteen. I only became involved for the interesting part.' , accent: 'primary' },
          { kind: 'dialogue', speaker: 'Jian Yue', text: 'You manipulated military officers, merchants, civil clerks, and civilians without holding any authority over them.' , accent: 'secondary' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'Authority is very expensive. Conversation is free.' , accent: 'primary' },
          { kind: 'dialogue', speaker: 'Jian Yue', text: 'Which is precisely why they are concerned.' , accent: 'secondary' },
          { kind: 'paragraph', text: 'Xu Kai ate another dumpling.' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'So what happens now?' , accent: 'primary' },
          { kind: 'dialogue', speaker: 'Jian Yue', text: 'I supervise you.' , accent: 'secondary' },
          { kind: 'paragraph', text: 'Xu Kai paused halfway through chewing.' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'You personally?' , accent: 'primary' },
          { kind: 'dialogue', speaker: 'Jian Yue', text: 'Yes.' , accent: 'secondary' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'National Tier #2 has nothing better to do?' , accent: 'primary' },
          { kind: 'dialogue', speaker: 'Jian Yue', text: 'At present, apparently not.' , accent: 'secondary' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'This country has serious staffing problems.' , accent: 'primary' },
          { kind: 'dialogue', speaker: 'Jian Yue', text: 'You are the staffing problem.' , accent: 'secondary' },
          { kind: 'paragraph', text: 'He considered that.' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'Fair.' , accent: 'primary' },
          { kind: 'paragraph', text: 'Jian Yue placed an official travel order on the table.' },
          { kind: 'dialogue', speaker: 'Jian Yue', text: 'You will accompany me to the capital tomorrow morning.' , accent: 'secondary' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'No.' , accent: 'primary' },
          { kind: 'paragraph', text: 'The room stopped breathing again.' },
          { kind: 'dialogue', speaker: 'Jian Yue', text: 'No?' , accent: 'secondary' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'Tomorrow is market day.' , accent: 'primary' },
          { kind: 'dialogue', speaker: 'Jian Yue', text: 'I am not asking.' , accent: 'secondary' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'That is poor conversational design.' , accent: 'primary' },
          { kind: 'paragraph', text: 'A faint pressure rolled through the teahouse.' },
          { kind: 'paragraph', text: 'The windows trembled.' },
          { kind: 'paragraph', text: 'Three cups rattled against their saucers. The waiter behind the counter went white.' },
          { kind: 'paragraph', text: 'Xu Kai looked down at his tea.' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'Oi.' , accent: 'primary' },
          { kind: 'paragraph', text: 'The pressure vanished.' },
          { kind: 'paragraph', text: 'Jian Yue stared at him.' },
          { kind: 'dialogue', speaker: 'Jian Yue', text: 'What did you just call me?' , accent: 'secondary' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'Oi.' , accent: 'primary' },
          { kind: 'dialogue', speaker: 'Jian Yue', text: 'I have a name.' , accent: 'secondary' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'Congratulations.' , accent: 'primary' },
          { kind: 'paragraph', text: 'Somewhere behind them, the teahouse owner quietly sat on the floor.' },
          { kind: 'dialogue', speaker: 'Jian Yue', text: 'People have been executed for less.' , accent: 'secondary' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'By you?' , accent: 'primary' },
          { kind: 'dialogue', speaker: 'Jian Yue', text: 'Not yet.' , accent: 'secondary' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'Good. I would hate to damage your record.' , accent: 'primary' },
          { kind: 'paragraph', text: 'Jian Yue\'s fingers tightened around the teacup.' },
          { kind: 'paragraph', text: 'It cracked.' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'You owe them a cup.' , accent: 'primary' },
          { kind: 'dialogue', speaker: 'Jian Yue', text: 'Tomorrow. Sunrise. South gate.' , accent: 'secondary' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'Can we make it after breakfast?' , accent: 'primary' },
          { kind: 'dialogue', speaker: 'Jian Yue', text: 'Sunrise.' , accent: 'secondary' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'Cruel woman.' , accent: 'primary' },
          { kind: 'paragraph', text: 'Jian Yue stood.' },
          { kind: 'dialogue', speaker: 'Jian Yue', text: 'And stop calling me Oi.' , accent: 'secondary' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'Of course, Oi.' , accent: 'primary' },
          { kind: 'paragraph', text: 'The door closed behind her hard enough to shake dust from the frame.' },
          { kind: 'paragraph', text: 'Xu Kai reached for the last dumpling.' },
          { kind: 'dialogue', speaker: 'Teahouse Owner', text: 'Sir.' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'Mm?' , accent: 'primary' },
          { kind: 'dialogue', speaker: 'Teahouse Owner', text: 'Please never do that in my establishment again.' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'Break a cup?' , accent: 'primary' },
          { kind: 'dialogue', speaker: 'Teahouse Owner', text: 'Survive like that.' },
        ],
      },
      {
        id: 's01-c03',
        season: 1,
        number: 3,
        title: 'Please Stop Protecting Me',
        summary: 'Jian Yue begins her supervision. A group of assassins discovers that Xu Kai is inconvenient to kill for several different reasons.',
        readingMinutes: 9,
        tags: ['xu-kai', 'jian-yue', 'assassins', 'secret-strength', 'romance'],
        segments: [
          { kind: 'paragraph', text: 'Xu Kai arrived at the south gate twenty-three minutes after sunrise carrying breakfast.' },
          { kind: 'paragraph', text: 'Jian Yue had been waiting for twenty-four.' },
          { kind: 'dialogue', speaker: 'Jian Yue', text: 'You are late.' , accent: 'secondary' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'I brought buns.' , accent: 'primary' },
          { kind: 'dialogue', speaker: 'Jian Yue', text: 'That does not change time.' , accent: 'secondary' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'Have you tried one?' , accent: 'primary' },
          { kind: 'paragraph', text: 'She looked at the paper bag.' },
          { kind: 'dialogue', speaker: 'Jian Yue', text: 'No.' , accent: 'secondary' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'Then your conclusion lacks evidence.' , accent: 'primary' },
          { kind: 'paragraph', text: 'Jian Yue took one.' },
          { kind: 'paragraph', text: 'Xu Kai smiled.' },
          { kind: 'dialogue', speaker: 'Jian Yue', text: 'Do not look pleased.' , accent: 'secondary' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'You accepted a bribe.' , accent: 'primary' },
          { kind: 'dialogue', speaker: 'Jian Yue', text: 'It is a bun.' , accent: 'secondary' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'Corruption always starts small.' , accent: 'primary' },
          { kind: 'paragraph', text: 'They left Qingshi on horseback with two Ministry agents following at a respectful distance.' },
          { kind: 'paragraph', text: 'By midmorning, Jian Yue had learned three things.' },
          { kind: 'paragraph', text: 'First, Xu Kai could ride perfectly well but preferred complaining about the saddle.' },
          { kind: 'paragraph', text: 'Second, he recognized every edible roadside plant and none of the official military banners.' },
          { kind: 'paragraph', text: 'Third, silence did not discourage him.' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'Oi.' , accent: 'primary' },
          { kind: 'dialogue', speaker: 'Jian Yue', text: 'No.' , accent: 'secondary' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'I have not asked anything yet.' , accent: 'primary' },
          { kind: 'dialogue', speaker: 'Jian Yue', text: 'I am getting ahead of the problem.' , accent: 'secondary' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'How proactive.' , accent: 'primary' },
          { kind: 'dialogue', speaker: 'Jian Yue', text: 'My name is Jian Yue.' , accent: 'secondary' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'I remember.' , accent: 'primary' },
          { kind: 'dialogue', speaker: 'Jian Yue', text: 'Use it.' , accent: 'secondary' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'That sounds unnecessarily intimate.' , accent: 'primary' },
          { kind: 'paragraph', text: 'Her horse sped up.' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'Oi, wait.' , accent: 'primary' },
          { kind: 'dialogue', speaker: 'Jian Yue', text: 'Walk.' , accent: 'secondary' },
          { kind: 'break', label: 'By evening' },
          { kind: 'paragraph', text: 'Rain forced them into a roadside inn two hours before the nearest town.' },
          { kind: 'paragraph', text: 'Jian Yue disliked the place before she crossed the threshold.' },
          { kind: 'paragraph', text: 'Xu Kai disliked the soup.' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'Too much ginger.' , accent: 'primary' },
          { kind: 'dialogue', speaker: 'Jian Yue', text: 'Three men near the door are armed.' , accent: 'secondary' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'That does not excuse the ginger.' , accent: 'primary' },
          { kind: 'dialogue', speaker: 'Jian Yue', text: 'Two upstairs. One behind the kitchen curtain.' , accent: 'secondary' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'Six assassins?' , accent: 'primary' },
          { kind: 'dialogue', speaker: 'Jian Yue', text: 'Seven.' , accent: 'secondary' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'Where is seven?' , accent: 'primary' },
          { kind: 'dialogue', speaker: 'Jian Yue', text: 'Serving you soup.' , accent: 'secondary' },
          { kind: 'paragraph', text: 'Xu Kai looked up at the innkeeper.' },
          { kind: 'paragraph', text: 'The innkeeper froze with the ladle still in his hand.' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'That explains the ginger.' , accent: 'primary' },
          { kind: 'dialogue', speaker: 'Jian Yue', text: 'Stay behind me.' , accent: 'secondary' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'I dislike that sentence.' , accent: 'primary' },
          { kind: 'dialogue', speaker: 'Jian Yue', text: 'You dislike most useful sentences.' , accent: 'secondary' },
          { kind: 'paragraph', text: 'The first dart left the second-floor railing.' },
          { kind: 'paragraph', text: 'Jian Yue did not draw her sword.' },
          { kind: 'paragraph', text: 'Two fingers rose. The dart stopped between them.' },
          { kind: 'paragraph', text: 'The second assassin moved before the first dart hit the floor.' },
          { kind: 'paragraph', text: 'This time Jian Yue drew.' },
          { kind: 'paragraph', text: 'Crimson steel flashed once.' },
          { kind: 'paragraph', text: 'Three tables split neatly down the middle. The assassin did not. His weapon simply vanished from his hand, cut into four pieces before he understood that the fight had begun.' },
          { kind: 'dialogue', speaker: 'Jian Yue', text: 'Alive if possible.' , accent: 'secondary' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'How considerate.' , accent: 'primary' },
          { kind: 'dialogue', speaker: 'Jian Yue', text: 'That instruction was not for you.' , accent: 'secondary' },
          { kind: 'paragraph', text: 'The inn erupted.' },
          { kind: 'paragraph', text: 'One attacker came through the kitchen. Two dropped from the stairs. Another kicked open the rear door. The innkeeper abandoned his ladle and reached under the counter for a short blade.' },
          { kind: 'paragraph', text: 'Jian Yue stepped forward.' },
          { kind: 'paragraph', text: 'For the next six breaths, the room belonged to her.' },
          { kind: 'paragraph', text: 'She moved with the brutal economy of someone who had long ago stopped confusing speed with haste. A wrist turned. A knee buckled. A sword spun into a ceiling beam. The flat of her blade struck one man hard enough to fold him over a table without opening his skin.' },
          { kind: 'paragraph', text: 'Xu Kai continued eating.' },
          { kind: 'dialogue', speaker: 'Assassin', text: 'You!' },
          { kind: 'paragraph', text: 'The seventh man had never intended to fight Jian Yue.' },
          { kind: 'paragraph', text: 'He slipped behind the chaos, crossed the room in silence, and drove a narrow black blade toward Xu Kai\'s throat.' },
          { kind: 'paragraph', text: 'Jian Yue was facing the other direction.' },
          { kind: 'paragraph', text: 'Xu Kai sighed.' },
          { kind: 'paragraph', text: 'The assassin\'s blade stopped.' },
          { kind: 'paragraph', text: 'Not against armor.' },
          { kind: 'paragraph', text: 'Not against a hidden weapon.' },
          { kind: 'paragraph', text: 'Between Xu Kai\'s chopsticks.' },
          { kind: 'paragraph', text: 'The assassin stared.' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'This is why I dislike fighting.' , accent: 'primary' },
          { kind: 'paragraph', text: 'He twisted his wrist.' },
          { kind: 'paragraph', text: 'The black blade snapped without a sound.' },
          { kind: 'dialogue', speaker: 'Assassin', text: 'You—' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'Quiet.' , accent: 'primary' },
          { kind: 'paragraph', text: 'For one instant, there was nothing playful in Xu Kai\'s face.' },
          { kind: 'paragraph', text: 'The assassin stopped breathing.' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'If she turns around and sees you standing this close to me, she is going to become extremely irritating.' , accent: 'primary' },
          { kind: 'paragraph', text: 'The assassin tried to retreat.' },
          { kind: 'paragraph', text: 'Xu Kai tapped the table once with a chopstick.' },
          { kind: 'paragraph', text: 'The man\'s knees folded beneath him.' },
          { kind: 'paragraph', text: 'He hit the floor just as Jian Yue turned.' },
          { kind: 'dialogue', speaker: 'Jian Yue', text: 'Xu Kai!' , accent: 'secondary' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'Present.' , accent: 'primary' },
          { kind: 'paragraph', text: 'She crossed the room so quickly the air snapped behind her.' },
          { kind: 'dialogue', speaker: 'Jian Yue', text: 'Are you hurt?' , accent: 'secondary' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'Emotionally. The soup remains disappointing.' , accent: 'primary' },
          { kind: 'dialogue', speaker: 'Jian Yue', text: 'I am serious.' , accent: 'secondary' },
          { kind: 'paragraph', text: 'She grabbed his wrist, checked his pulse, then his shoulders, then the front of his robe for blood.' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'Oi.' , accent: 'primary' },
          { kind: 'dialogue', speaker: 'Jian Yue', text: 'What?' , accent: 'secondary' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'Dinner first.' , accent: 'primary' },
          { kind: 'paragraph', text: 'She released him as if his sleeve had caught fire.' },
          { kind: 'dialogue', speaker: 'Jian Yue', text: 'Idiot.' , accent: 'secondary' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'That sounded affectionate.' , accent: 'primary' },
          { kind: 'dialogue', speaker: 'Jian Yue', text: 'It was a diagnosis.' , accent: 'secondary' },
          { kind: 'paragraph', text: 'Her gaze dropped to the unconscious assassin beside him.' },
          { kind: 'dialogue', speaker: 'Jian Yue', text: 'What happened to him?' , accent: 'secondary' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'He slipped.' , accent: 'primary' },
          { kind: 'dialogue', speaker: 'Jian Yue', text: 'He slipped.' , accent: 'secondary' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'Violently.' , accent: 'primary' },
          { kind: 'paragraph', text: 'Jian Yue crouched beside the man. His weapon lay in two pieces.' },
          { kind: 'dialogue', speaker: 'Jian Yue', text: 'His blade broke.' , accent: 'secondary' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'Poor craftsmanship.' , accent: 'primary' },
          { kind: 'paragraph', text: 'She picked up half the blade.' },
          { kind: 'paragraph', text: 'Blacksteel.' },
          { kind: 'paragraph', text: 'Military grade.' },
          { kind: 'paragraph', text: 'Not poor craftsmanship.' },
          { kind: 'paragraph', text: 'Jian Yue slowly looked at him.' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'Very unlucky craftsmanship?' , accent: 'primary' },
          { kind: 'dialogue', speaker: 'Jian Yue', text: 'You are hiding something.' , accent: 'secondary' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'Several things. There are buns in my travel bag, for example.' , accent: 'primary' },
          { kind: 'dialogue', speaker: 'Jian Yue', text: 'Xu Kai.' , accent: 'secondary' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'Jian Yue.' , accent: 'primary' },
          { kind: 'paragraph', text: 'She blinked.' },
          { kind: 'dialogue', speaker: 'Jian Yue', text: 'You used my name.' , accent: 'secondary' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'Do not make it strange.' , accent: 'primary' },
          { kind: 'paragraph', text: 'The tips of her ears turned red.' },
          { kind: 'dialogue', speaker: 'Jian Yue', text: 'I did not make anything strange.' , accent: 'secondary' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'You are currently blushing over basic identification.' , accent: 'primary' },
          { kind: 'dialogue', speaker: 'Jian Yue', text: 'I am angry.' , accent: 'secondary' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'Your ears are furious.' , accent: 'primary' },
          { kind: 'dialogue', speaker: 'Jian Yue', text: 'I can still arrest you.' , accent: 'secondary' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'For surviving?' , accent: 'primary' },
          { kind: 'dialogue', speaker: 'Jian Yue', text: 'For making it difficult.' , accent: 'secondary' },
          { kind: 'paragraph', text: 'One of the Ministry agents groaned from behind an overturned table.' },
          { kind: 'dialogue', speaker: 'Ministry Agent', text: 'Lady Jian... all seven are alive.' },
          { kind: 'dialogue', speaker: 'Jian Yue', text: 'Bind them. We question them at dawn.' , accent: 'secondary' },
          { kind: 'paragraph', text: 'She looked back at Xu Kai.' },
          { kind: 'dialogue', speaker: 'Jian Yue', text: 'You are sleeping in the room beside mine.' , accent: 'secondary' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'Scandalous.' , accent: 'primary' },
          { kind: 'dialogue', speaker: 'Jian Yue', text: 'For security.' , accent: 'secondary' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'Of course.' , accent: 'primary' },
          { kind: 'dialogue', speaker: 'Jian Yue', text: 'And I am keeping watch outside.' , accent: 'secondary' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'You know I survived before meeting you.' , accent: 'primary' },
          { kind: 'dialogue', speaker: 'Jian Yue', text: 'I have reviewed your decisions. I consider that statistically suspicious.' , accent: 'secondary' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'You worry too much, Oi.' , accent: 'primary' },
          { kind: 'dialogue', speaker: 'Jian Yue', text: 'I am not worried.' , accent: 'secondary' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'Naturally.' , accent: 'primary' },
          { kind: 'dialogue', speaker: 'Jian Yue', text: 'You are a state security concern.' , accent: 'secondary' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'How romantic.' , accent: 'primary' },
          { kind: 'dialogue', speaker: 'Jian Yue', text: 'Go to sleep.' , accent: 'secondary' },
          { kind: 'paragraph', text: 'Later that night, Xu Kai opened his door.' },
          { kind: 'paragraph', text: 'Jian Yue sat against the opposite wall with her sword across her knees, eyes closed but very much awake.' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'Oi.' , accent: 'primary' },
          { kind: 'dialogue', speaker: 'Jian Yue', text: 'What now?' , accent: 'secondary' },
          { kind: 'paragraph', text: 'He tossed something toward her.' },
          { kind: 'paragraph', text: 'She caught it without opening her eyes.' },
          { kind: 'paragraph', text: 'A steamed bun.' },
          { kind: 'dialogue', speaker: 'Xu Kai', text: 'For the corruption.' , accent: 'primary' },
          { kind: 'dialogue', speaker: 'Jian Yue', text: 'Go to sleep, idiot.' , accent: 'secondary' },
          { kind: 'paragraph', text: 'Her voice was still sharp.' },
          { kind: 'paragraph', text: 'She ate the bun anyway.' },
        ],
      },
    ],
  },
];
