import type { Chapter, Season } from '../domain/types';
import { seasons as baseSeasons } from './story-v8';

const chapter40: Chapter = {
  id: 's01-c40',
  season: 1,
  number: 40,
  title: 'Oi Starts an Administrative Incident',
  summary: 'Gao Wen moves first by seizing a witness. Jian Yue responds with all the restraint expected from National Tier #2, which is not much.',
  readingMinutes: 10,
  tags: ['jian-yue', 'gao-wen', 'qiao-min', 'romance', 'politics'],
  segments: [
    { kind: 'paragraph', text: 'Qiao Min was arrested the next morning for being dead incorrectly.' },
    { kind: 'paragraph', text: 'The formal charge was pension fraud.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Technically accurate.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Do not admire it.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'The Revenue Ministry filed the complaint at dawn.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Gao knows.', accent: 'primary' },
    { kind: 'paragraph', text: 'Qiao Min had been moved to the Revenue Ministry\'s internal detention annex before Lu Chen could claim him as a state-security witness.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Then we go get him.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'We need an order.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'I am an order.', accent: 'secondary' },
    { kind: 'paragraph', text: 'Xu Kai looked delighted.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'That may be the most National-Tier sentence ever spoken.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Are you coming?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Absolutely.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'No.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'This is discrimination against civilians.', accent: 'primary' },
    { kind: 'paragraph', text: 'They went anyway.' },
    { kind: 'break', label: 'Revenue Ministry annex' },
    { kind: 'paragraph', text: 'The annex guards were brave until Jian Yue arrived.' },
    { kind: 'dialogue', speaker: 'Guard Captain', text: 'Lady Jian, we have no authority to release the prisoner.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'I did not ask who could release him.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Guard Captain', text: 'Then what are you asking?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Who decided to put him here.', accent: 'secondary' },
    { kind: 'paragraph', text: 'The captain swallowed.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'She is doing excellent diplomacy.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'By her standards.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Gao Wen appeared before anyone broke a door.' },
    { kind: 'dialogue', speaker: 'Gao Wen', text: 'Lady Jian. You are obstructing a lawful detention.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You are detaining a witness in an investigation involving your own ministry.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Gao Wen', text: 'He is accused of defrauding the state.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'By accepting a pension under the identity your ministry continued paying after declaring him dead twice.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Gao Wen', text: 'That is why we investigate.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You are investigating why you paid him?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Gao Wen', text: 'Why he accepted it.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Very economical division of blame.', accent: 'primary' },
    { kind: 'paragraph', text: 'Gao Wen turned to Jian Yue.' },
    { kind: 'dialogue', speaker: 'Gao Wen', text: 'You are a Pillar of the nation, not this man\'s private enforcer.', accent: 'neutral' },
    { kind: 'paragraph', text: 'The corridor cooled.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Choose your next sentence carefully.', accent: 'secondary' },
    { kind: 'paragraph', text: 'Xu Kai stopped smiling.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Oi.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'What?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'He is baiting you.', accent: 'primary' },
    { kind: 'paragraph', text: 'She looked at him.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'If you threaten him, he gets to become the reasonable official standing against an emotional Pillar.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'I am not emotional.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You are holding the doorframe hard enough to redesign it.', accent: 'primary' },
    { kind: 'paragraph', text: 'She looked at her hand.' },
    { kind: 'paragraph', text: 'The wood was cracking.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Old building.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Naturally.', accent: 'primary' },
    { kind: 'paragraph', text: 'Gao Wen\'s expression did not change.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Keep him.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'What?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'For six hours.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Gao Wen', text: 'You are granting me permission?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'No. I am giving you a deadline.', accent: 'primary' },
    { kind: 'paragraph', text: 'Gao Wen finally stopped smiling.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'At the seventh hour, his detention becomes part of a public jurisdiction hearing before the Finance Council and the Hall of Five.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Gao Wen', text: 'On whose authority?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Mine, apparently. I have a temporary office now. Terrible decision by everyone involved.', accent: 'primary' },
    { kind: 'paragraph', text: 'Lu Chen produced the appointment order.' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Temporary Imperial Examiner.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Jian Yue looked at Xu Kai.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You said you did not want the office.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I also did not want breakfast yesterday. Life is compromise.', accent: 'primary' },
    { kind: 'paragraph', text: 'They left without Qiao Min.' },
    { kind: 'paragraph', text: 'Jian Yue was furious for three streets.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'If he harms Qiao Min—', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'He will not.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'How do you know?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Because now half the capital is counting the hours.', accent: 'primary' },
    { kind: 'paragraph', text: 'She exhaled.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Oi.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'What now?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Thank you.', accent: 'primary' },
    { kind: 'paragraph', text: 'She looked away.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'State security.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Of course.', accent: 'primary' },
  ],
};

const chapter41: Chapter = {
  id: 's01-c41',
  season: 1,
  number: 41,
  title: 'The Ministry Audits Itself',
  summary: 'Xu Kai forces the Revenue Ministry to perform the one thing it fears more than accusation: a complete audit under public observation.',
  readingMinutes: 11,
  tags: ['audit', 'revenue-ministry', 'politics', 'gao-wen', 'five-pillars'],
  segments: [
    { kind: 'paragraph', text: 'The public jurisdiction hearing began at the seventh hour because Xu Kai was petty enough to ring a bell.' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'Was the bell necessary?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Deeply.', accent: 'primary' },
    { kind: 'paragraph', text: 'The Imperial Finance Council occupied one side of the chamber.' },
    { kind: 'paragraph', text: 'The Five Pillars occupied the other.' },
    { kind: 'paragraph', text: 'Gao Wen stood at the center with six ministry directors and the confidence of a man who had spent decades preparing for rooms like this.' },
    { kind: 'paragraph', text: 'Xu Kai brought no documents.' },
    { kind: 'dialogue', speaker: 'Finance Councillor', text: 'Examiner Xu, where is your evidence?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'In the Revenue Ministry.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Finance Councillor', text: 'That is the institution you accuse.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Exactly. Saves walking.', accent: 'primary' },
    { kind: 'paragraph', text: 'Gao Wen frowned.' },
    { kind: 'dialogue', speaker: 'Gao Wen', text: 'State your accusation clearly.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'No.', accent: 'primary' },
    { kind: 'paragraph', text: 'Several councillors whispered.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Accusations are convenient. They tell everyone what evidence to hide and what defense to prepare.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'Then what are you requesting?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'An audit.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Gao Wen', text: 'Of what period?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'All seven years since Heshan.', accent: 'primary' },
    { kind: 'paragraph', text: 'The chamber changed.' },
    { kind: 'dialogue', speaker: 'Finance Councillor', text: 'That would involve tens of thousands of accounts.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Good thing we have a Revenue Ministry.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Gao Wen', text: 'This is theater.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'No. Theater has better chairs.', accent: 'primary' },
    { kind: 'paragraph', text: 'Lu Chen distributed a short list.' },
    { kind: 'paragraph', text: 'It contained nine names.' },
    { kind: 'paragraph', text: 'Every name belonged to an accountant, clerk, courier, or provincial auditor officially dead but still appearing somewhere in the state payment system.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'We do not need to inspect every coin. We need to ask why dead people keep getting paid.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Gao Wen', text: 'Administrative errors happen.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Nine times, all connected to offices that handled relief reconciliation?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Gao Wen', text: 'Correlation.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'My favorite word when someone dislikes arithmetic.', accent: 'primary' },
    { kind: 'paragraph', text: 'The Finance Council approved a limited audit by a narrow vote.' },
    { kind: 'paragraph', text: 'Then Xu Kai requested that the Revenue Ministry perform it themselves.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'What?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Trust the professionals.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You trust no one.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Correct.', accent: 'primary' },
    { kind: 'paragraph', text: 'He turned to the Council.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Let Revenue inspect its own records under observers from State Security, the military, and the Finance Council.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Gao Wen', text: 'You expect us to convict ourselves?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'No. I expect departments to protect themselves.', accent: 'primary' },
    { kind: 'paragraph', text: 'Gao Wen stared at him.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'If this scheme has lasted years, different directors know different pieces. The moment they realize the audit is real, they will start proving the problem belongs to someone else.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'They will produce evidence against each other.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Government cooperation.', accent: 'primary' },
    { kind: 'paragraph', text: 'Bai Ren laughed openly.' },
    { kind: 'dialogue', speaker: 'Bai Ren', text: 'I still like him.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'We know.', accent: 'neutral' },
    { kind: 'break', label: 'By evening' },
    { kind: 'paragraph', text: 'Three Revenue directors had submitted sealed memoranda blaming four other offices.' },
    { kind: 'paragraph', text: 'Two provincial treasurers requested immunity before anyone accused them.' },
    { kind: 'paragraph', text: 'A retired auditor arrived carrying six boxes and an attitude.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You started a panic.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'No. I announced that someone might count.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Same thing, apparently.', accent: 'secondary' },
    { kind: 'paragraph', text: 'Qiao Min was released before sunset.' },
    { kind: 'paragraph', text: 'Gao Wen called it a jurisdictional courtesy.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'He survived his third death.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Do not make that a tradition.', accent: 'secondary' },
  ],
};

const chapter42: Chapter = {
  id: 's01-c42',
  season: 1,
  number: 42,
  title: 'Three Receipts and a Funeral',
  summary: 'The audit produces too much evidence. Xu Kai ignores almost all of it and follows three receipts to a funeral attended by people who should hate one another.',
  readingMinutes: 10,
  tags: ['receipts', 'funeral', 'investigation', 'gao-wen', 'wit'],
  segments: [
    { kind: 'paragraph', text: 'By the second day of the audit, Lu Chen had twenty-three boxes of documents and one headache.' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'There are too many irregularities.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Luxury problem.', accent: 'primary' },
    { kind: 'paragraph', text: 'Xu Kai ignored the bribes, false mileage claims, ghost employees, duplicate wagon repairs, suspicious tax exemptions, and a provincial office that had purchased the same desk seventeen times.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Why ignore all of that?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Because corruption is noisy. I want the quiet thing.', accent: 'primary' },
    { kind: 'paragraph', text: 'He found it in three receipts.' },
    { kind: 'paragraph', text: 'Each came from a different province.' },
    { kind: 'paragraph', text: 'Each paid for archival ink.' },
    { kind: 'paragraph', text: 'Each used the same private carrier: Willow Cartage.' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Willow Cartage dissolved eight years ago.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Very productive corpse.', accent: 'primary' },
    { kind: 'paragraph', text: 'The owner of Willow Cartage had also died eight years ago.' },
    { kind: 'paragraph', text: 'His funeral anniversary was that afternoon.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You want to attend a dead merchant\'s memorial because someone bought ink?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'When you say it like that, it sounds healthy.', accent: 'primary' },
    { kind: 'break', label: 'The funeral meal' },
    { kind: 'paragraph', text: 'The memorial was held at a private ancestral hall outside the western market.' },
    { kind: 'paragraph', text: 'Xu Kai arrived with Jian Yue wearing plain clothes that fooled nobody.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You look extremely anonymous.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Be quiet.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'A mysterious civilian woman with a sword everyone recognizes.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'I can leave.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You would miss the food.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'I am here to protect you.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'From dumplings?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Potentially.', accent: 'secondary' },
    { kind: 'paragraph', text: 'The guest list was more useful than the incense.' },
    { kind: 'paragraph', text: 'Two former provincial treasurers attended.' },
    { kind: 'paragraph', text: 'So did a retired relief commissioner, an archive contractor, and Assistant Director Meng.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'They all knew the dead merchant.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Or they know each other.', accent: 'primary' },
    { kind: 'paragraph', text: 'Gao Wen arrived last.' },
    { kind: 'paragraph', text: 'That surprised even Xu Kai.' },
    { kind: 'dialogue', speaker: 'Gao Wen', text: 'Mister Xu. Lady Jian.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Small funeral.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Gao Wen', text: 'The deceased was once a useful man.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Still seems useful.', accent: 'primary' },
    { kind: 'paragraph', text: 'Gao Wen did not ask what he meant.' },
    { kind: 'paragraph', text: 'That was answer enough.' },
    { kind: 'paragraph', text: 'During the meal, Xu Kai deliberately told three different guests that the audit had found Willow Cartage payments in three provinces.' },
    { kind: 'paragraph', text: 'One denied knowing the company.' },
    { kind: 'paragraph', text: 'One immediately left.' },
    { kind: 'paragraph', text: 'The retired relief commissioner dropped his cup.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'That one.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'The cup?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'The man attached to it.', accent: 'primary' },
    { kind: 'paragraph', text: 'They followed the commissioner after the memorial.' },
    { kind: 'paragraph', text: 'He went nowhere secret.' },
    { kind: 'paragraph', text: 'He went directly to Gao Wen\'s residence.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'That seems almost too easy.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Because it is.', accent: 'primary' },
    { kind: 'paragraph', text: 'Ten minutes later, the same commissioner left through the front gate carrying a sealed letter.' },
    { kind: 'paragraph', text: 'Lu Chen\'s agents followed him.' },
    { kind: 'paragraph', text: 'The letter went to the Imperial Archive.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Not the Finance Council.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Why the Archive?', accent: 'secondary' },
    { kind: 'paragraph', text: 'Xu Kai thought about Mei Rong.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Because Gao is not only afraid of accounts.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'He is afraid of the original records.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Or someone who knows how they were rewritten.', accent: 'primary' },
  ],
};

const chapter43: Chapter = {
  id: 's01-c43',
  season: 1,
  number: 43,
  title: 'The Price of a Name',
  summary: 'Gao Wen offers Xu Kai something the state has never been able to give him: a lead on his original family record. The price is Heshan.',
  readingMinutes: 11,
  tags: ['xu-kai', 'identity', 'gao-wen', 'jian-yue', 'emotional'],
  segments: [
    { kind: 'paragraph', text: 'Gao Wen asked Xu Kai to come alone.' },
    { kind: 'paragraph', text: 'Jian Yue laughed.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'No.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'He asked me.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'And I answered.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'Technically he requested privacy, not solitude.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Good.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I feel represented.', accent: 'primary' },
    { kind: 'paragraph', text: 'They compromised by placing Jian Yue in the next room with a door she could hear through.' },
    { kind: 'paragraph', text: 'Gao Wen knew she was there.' },
    { kind: 'paragraph', text: 'This improved everyone\'s honesty.' },
    { kind: 'dialogue', speaker: 'Gao Wen', text: 'I found something about you.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Condolences.', accent: 'primary' },
    { kind: 'paragraph', text: 'Gao Wen placed a narrow strip of old census paper on the table.' },
    { kind: 'paragraph', text: 'It listed a family from a mountain district destroyed by landslides twelve years ago.' },
    { kind: 'paragraph', text: 'One child had no death confirmation.' },
    { kind: 'paragraph', text: 'Given name: Kai.' },
    { kind: 'paragraph', text: 'Age matched.' },
    { kind: 'paragraph', text: 'Physical description was vague enough to be useful and specific enough to hurt.' },
    { kind: 'dialogue', speaker: 'Gao Wen', text: 'The family name was Shen.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Xu Kai did not touch the paper.' },
    { kind: 'dialogue', speaker: 'Gao Wen', text: 'Shen Kai may have been your birth name.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'May have been.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Gao Wen', text: 'There are surviving relatives.', accent: 'neutral' },
    { kind: 'paragraph', text: 'The next room was completely silent.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'And what would you like in exchange for my childhood?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Gao Wen', text: 'End Heshan.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'That is expensive.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Gao Wen', text: 'So is truth.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'No. Truth is usually free. Controlling access to it is expensive.', accent: 'primary' },
    { kind: 'paragraph', text: 'Gao Wen folded his hands.' },
    { kind: 'dialogue', speaker: 'Gao Wen', text: 'You think I am protecting theft.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You are.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Gao Wen', text: 'I am protecting continuity.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'By blackmailing the people who stole.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Gao Wen', text: 'By ensuring governors, tax commissioners, military suppliers, and provincial treasurers could be controlled instead of publicly destroyed.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You made corruption useful.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Gao Wen', text: 'I made corrupt men predictable.', accent: 'neutral' },
    { kind: 'paragraph', text: 'For the first time, Gao Wen sounded tired rather than polished.' },
    { kind: 'dialogue', speaker: 'Gao Wen', text: 'You have no idea what happens when half a provincial administration collapses at once.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Children lose grain either way.', accent: 'primary' },
    { kind: 'paragraph', text: 'Gao Wen looked at him.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'That is the part people like you keep calling small because the numbers look larger from your office.', accent: 'primary' },
    { kind: 'paragraph', text: 'Silence settled between them.' },
    { kind: 'dialogue', speaker: 'Gao Wen', text: 'Take the record. End the inquiry. I will give you the location of the surviving Shen family.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Xu Kai stared at the census strip.' },
    { kind: 'paragraph', text: 'The door opened.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'No.', accent: 'secondary' },
    { kind: 'paragraph', text: 'Gao Wen looked at her.' },
    { kind: 'dialogue', speaker: 'Gao Wen', text: 'This is not your decision.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'I know.', accent: 'secondary' },
    { kind: 'paragraph', text: 'She looked at Xu Kai.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Take all the time you need. But do not let him make you think your name belongs to him.', accent: 'secondary' },
    { kind: 'paragraph', text: 'Xu Kai said nothing.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You chose Xu. You answer to Xu Kai. That is yours whether Shen is true or not.', accent: 'secondary' },
    { kind: 'paragraph', text: 'Gao Wen watched them with an unreadable expression.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Oi.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'What?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'You ruined my dramatic internal conflict.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Good.', accent: 'secondary' },
    { kind: 'paragraph', text: 'Xu Kai finally picked up the census strip.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I will verify this.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Gao Wen', text: 'And Heshan?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I am going to make your week substantially worse.', accent: 'primary' },
    { kind: 'paragraph', text: 'Jian Yue smiled before remembering she was supposed to be stern.' },
  ],
};

const chapter44: Chapter = {
  id: 's01-c44',
  season: 1,
  number: 44,
  title: 'The Sixth Chair',
  summary: 'Xu Kai ends the Heshan case by making Gao Wen choose between protecting his network and exposing it himself. The Five then make an administrative decision nobody will admit is sentimental.',
  readingMinutes: 12,
  tags: ['arc-finale', 'gao-wen', 'five-pillars', 'xu-kai', 'jian-yue'],
  segments: [
    { kind: 'paragraph', text: 'Xu Kai did not expose Gao Wen.' },
    { kind: 'paragraph', text: 'He exposed everyone else first.' },
    { kind: 'paragraph', text: 'The limited audit became public in pieces.' },
    { kind: 'paragraph', text: 'Three provincial treasurers were suspended.' },
    { kind: 'paragraph', text: 'Two retired commissioners lost immunity petitions because they had lied in them.' },
    { kind: 'paragraph', text: 'Assistant Director Meng resigned so quickly he forgot to collect his coat.' },
    { kind: 'paragraph', text: 'The coat was eventually returned by government courier because even scandal had procedures.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You are letting Gao Wen remain in office.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'For today.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'I dislike today.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'His network is collapsing.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Which is why he is finally useful.', accent: 'primary' },
    { kind: 'paragraph', text: 'They summoned Gao Wen to the Hall of Five.' },
    { kind: 'paragraph', text: 'He came alone.' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'Vice Minister Gao. You are accused of concealing systemic fraud, coercing officials through undisclosed misconduct, interfering with evidence, and obstructing a state-security investigation.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Gao Wen', text: 'I expected a longer list.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Bai Ren', text: 'We edited for clarity.', accent: 'neutral' },
    { kind: 'paragraph', text: 'Xu Kai placed two sealed documents on the table.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Two choices.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Gao Wen', text: 'You enjoy pretending people have choices.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I learned from government.', accent: 'primary' },
    { kind: 'paragraph', text: 'He tapped the first document.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'This is Lu Chen\'s case. It names you as the center of a coercion network and recommends immediate detention.', accent: 'primary' },
    { kind: 'paragraph', text: 'He tapped the second.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'This is your confession.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Gao Wen', text: 'I have not written one.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Yet.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'You are offering him leniency?', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I am offering him work.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'Explain.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Gao Wen knows every official he controlled, every secret he buried, every office that depended on the arrangement, and which ones are still stealing.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'You want him to dismantle his own network.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Publicly, under supervision, before he resigns.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Gao Wen', text: 'And if I refuse?', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Then Lu Chen gets the fun version.', accent: 'primary' },
    { kind: 'paragraph', text: 'Lu Chen looked almost offended by the description.' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'There is no fun version.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'For you there is.', accent: 'primary' },
    { kind: 'paragraph', text: 'Gao Wen looked around the Hall.' },
    { kind: 'paragraph', text: 'Han Zhen gave nothing away.' },
    { kind: 'paragraph', text: 'Yan Shuo looked impatient.' },
    { kind: 'paragraph', text: 'Bai Ren looked curious.' },
    { kind: 'paragraph', text: 'Lu Chen looked prepared.' },
    { kind: 'paragraph', text: 'Jian Yue looked like leniency was a personal insult.' },
    { kind: 'dialogue', speaker: 'Gao Wen', text: 'You think reform is cleaner than punishment.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'No. I think punishment is easier.', accent: 'primary' },
    { kind: 'paragraph', text: 'Gao Wen looked at him for a long time.' },
    { kind: 'dialogue', speaker: 'Gao Wen', text: 'You really were that boy at Heshan.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Unfortunately.', accent: 'primary' },
    { kind: 'paragraph', text: 'Gao Wen chose the confession.' },
    { kind: 'break', label: 'Three weeks later' },
    { kind: 'paragraph', text: 'Gao Wen resigned after naming thirty-one officials, eleven contractors, four retired administrators, and one sitting governor.' },
    { kind: 'paragraph', text: 'He was placed under restricted residence pending trial.' },
    { kind: 'paragraph', text: 'Qiao Min received a legal identity for the first time in nine years and immediately complained about the forms.' },
    { kind: 'paragraph', text: 'Mei Rong was formally reprimanded for forging a foreign personnel file and unofficially thanked by three departments that denied doing so.' },
    { kind: 'paragraph', text: 'Heshan Relief House received a state memorial grant.' },
    { kind: 'paragraph', text: 'Auntie Lan refused the proposed plaque because the wording was stupid.' },
    { kind: 'paragraph', text: 'Nobody successfully argued with her.' },
    { kind: 'break', label: 'Hall of Five' },
    { kind: 'paragraph', text: 'Xu Kai entered and stopped.' },
    { kind: 'paragraph', text: 'There were still six chairs.' },
    { kind: 'paragraph', text: 'The sixth had been moved to the table.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'That seems ominous.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'Sit down.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I liked it better when you objected.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Yan Shuo', text: 'Sit.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Bai Ren', text: 'We voted.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Again without me?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Lu Chen', text: 'You are not a Pillar.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Then why am I at the table?', accent: 'primary' },
    { kind: 'paragraph', text: 'Nobody answered immediately.' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'Your temporary examiner appointment is extended indefinitely.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'That sounds like employment.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'It is.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I object.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Han Zhen', text: 'Salary increased by twenty percent.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'I withdraw my objection.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Cheap.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Consistent.', accent: 'primary' },
    { kind: 'paragraph', text: 'Jian Yue was the only Pillar who had voted against the indefinite appointment.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Oi. Still trying to protect me from paperwork?', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'From idiots who will send you into danger because you are useful.', accent: 'secondary' },
    { kind: 'paragraph', text: 'The room became quiet.' },
    { kind: 'paragraph', text: 'Jian Yue realized she had said that aloud.' },
    { kind: 'dialogue', speaker: 'Bai Ren', text: 'Historic record.', accent: 'neutral' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'I will kill the record.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Concern survives another meeting.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'State security.', accent: 'secondary' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Naturally.', accent: 'primary' },
    { kind: 'paragraph', text: 'He sat in the sixth chair.' },
    { kind: 'paragraph', text: 'It was not a Pillar\'s seat.' },
    { kind: 'paragraph', text: 'Not officially.' },
    { kind: 'paragraph', text: 'But for the first time, nobody told him it was not his.' },
    { kind: 'break', label: 'That evening' },
    { kind: 'paragraph', text: 'A sealed letter waited at Xu Kai\'s house.' },
    { kind: 'paragraph', text: 'No ministry seal.' },
    { kind: 'paragraph', text: 'No sender.' },
    { kind: 'paragraph', text: 'Inside was a single line.' },
    { kind: 'paragraph', text: 'SHEN KAI DIED TWELVE YEARS AGO.' },
    { kind: 'paragraph', text: 'Xu Kai read it twice.' },
    { kind: 'paragraph', text: 'Then Jian Yue knocked on the wall between their houses.' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Oi.', accent: 'secondary' },
    { kind: 'paragraph', text: 'Xu Kai looked up.' },
    { kind: 'paragraph', text: 'It was the first time she had called him that.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'That is mine.', accent: 'primary' },
    { kind: 'dialogue', speaker: 'Jian Yue', text: 'Open the door.', accent: 'secondary' },
    { kind: 'paragraph', text: 'He folded the letter and smiled despite himself.' },
    { kind: 'dialogue', speaker: 'Xu Kai', text: 'Coming, Oi.', accent: 'primary' },
  ],
};

const newChapters = [chapter40, chapter41, chapter42, chapter43, chapter44];

export const seasons: Season[] = baseSeasons.map((season) => {
  if (season.number !== 1) {
    return season;
  }

  return {
    ...season,
    chapters: [...season.chapters, ...newChapters],
  };
});
